### PR TITLE
Meteor Showers plugin Improvements

### PR DESCRIPTION
**Pull request by worachate001**
### Description
The plugin is already great but would be better, the main issue of current version is the date of maximum ZHR and activity period that incorrectly unchanged. The dates must be computed from solar longitude, not the other way around. This version will correct it and can be used to predict past/future dates. It will also provide a more realistic information for annual meteor showers and meteor outbursts.

The database of showers (showers.json) is revised and updated to version 2 with data mainly from IMO. Additional data comes from IAU Meteor Data Center (MDC), especially the rate of radiant drift. There are 110+ established meteor showers (well-confirmed showers whose names have been officially approved during the General Assembly of IAU). In this version, meteor showers that appear in IMO calendars and IAU's established showers are priority.

### Notes:

1. **Maximum Date**: Date and Time of maximum ZHR, calculated from location of the Earth in its orbit with respect to meteor stream in space (represented by J2000 solar longitude). It's incorrect way of implementation to use the fixed date, a good example was 1833 Leonids storm that took place on November 12/13 as seen from North America, not on November 18 as shown in the database. Ancient records also indicate that dates shouldn't be fixed (Perseids occurred in late-July during year 10xx, not August 12/13, for example).

2. **Activity Dates**: Same as maximum date. Range of dates must move along with it. Changes are significant for hundreds of years from present day.

3. **Current ZHR**: This should give a better idea of how ZHR changes over time (lower than ZHRmax when far away from the center of meteoroid stream). This new version will use Gaussian (for low ZHR) and Lorentz distribution (for high ZHR) with different slope values for the curve of each shower (previous version uses only generic Gaussian distribution function for all showers).

4. **Local hourly rate**: Hourly rate of a meteor shower for current location on Earth - altitude of radiant and limiting magnitude are both taken into account. Lower radiant altitude means fewer meteors are observable (see https://www.imo.net/observations/methods/visual-observation/major/). This should give users a more realistic expected rate for each shower at any given date and time. It helps to determine which is the best night (and best time for some showers) to observe a meteor shower.

5. Combination of all the above allows Stellarium to simulate and predict meteor showers and meteor storms for any location on Earth with better accuracy. 1966 November 17 Leonid meteor storm, for example, was visible at peak rate in Americas, not elsewhere. The old version incorrectly shows Leonid storm everywhere in the world and throughout 25 days of activity!

6. **Antihelion** or anthelion (ANT) is now included (issue #1637). The shower is active throughout the year, note that it looks like IMO will omit it when Taurid complex becomes active during mid-September to mid-December (of present-day).

7. Some meteor showers found in the first version have been removed with various reasons (see below).

8. **IAU number** of meteor showers are now included.

9. **Search dialog** for meteor showers is changed to allow wider range of years.

10. Fluxtimator https://leonid.arc.nasa.gov/estimator.html is a good example of the result of predicted meteor showers. It allows you to calculate the expected shower rate for a given date and a given location. It's a Java applet, if you have trouble running it in modern browsers, try an extension in Chrome browser. 

11. Numerical data of meteor outbursts (Leonids, etc.) in our new database come from Jenniskens P., Meteor Showers and their Parent Comets, Cambridge University Press (2006).

12. Possible future improvement: moonlight is another factor that can reduce observable meteor rate (by decreasing limiting magnitude of the night sky) - I have to find a proper method and references to implement it.

13. I have to replace the file showers.json in user folder manually to make it work (updated: we are using different name to avoid the conflict). 

I guess we have two months until next major release (if there is no more hotfix), so we have plenty of time to fix any bugs that we may encounter during this development.

-------------------------------------------------------------

**List of showers found in version 1 but removed in version 2**
Autumn Arietids (not found in IAU database, probably the same with SOA Southern October delta Arietids, non-established)
August Caelids (non-established, not found in IMO calendars)
alpha-Pisces Australids (not found in IAU database/IMO calendars)
alpha-Scorpiids (not found in IAU database/IMO calendars)
delta Cancrids (probably the same with 96 NCC Northern delta Cancrids, not found in IMO calendars)
delta Leonids (=NDL Northern delta Leonids, non-established, not found in IMO calendars)
eta-Craterids (not found in IAU database/IMO calendars)
epsilon Gruids (non-established, not found in IMO calendars)
June Lyrids (non-established, not found in IMO calendars)
June Scutids (=SCU Scutids, non-established, not found in IMO calendars)
May Librids (=Northern Librids-Lupids?, non-established, not found in IMO calendars)
Ophiuchids (not found in IAU database, IMO calendars)
pi-Virginids (=NVI Northern March Virginids?, non-established, not found in IMO calendars)
rho-Geminids (RGE) (non-established / not found in IMO calendars)
Southern iota-Aquariids (non-established / not found in IMO calendars)
theta-Centaurids (non-established / not found in IMO calendars)
theta-Virginids (=ATV April theta Virginids, non-established, not found in IMO calendars)
chi-Orionids (=ORN Northern chi Orionids, non-established, not found in IMO calendars)
gamma-Aquariids (not found in IAU database, IMO calendars)
theta-Ophiuchids (not found in IAU database, IMO calendars, related to Scorpiid-Sagittariid Complex/Antihelion)

-------------------------------------------------------------
**List of showers found in version 1 but renamed in version 2**
(name changed to match with IAU database)
Lyrids = 006 LYR April Lyrids
alpha-Aurigids = 206 AUR Aurigids
Arietids = 171 ARI Daytime Arietids
δ-Aurigids = 224 DAU October δ-Aurigids
Monocerotids = 19 MON December Monocerotids
Sextantids = 221 DSX Daytime Sextantids

-------------------------------------------------------------
**List of newly included showers in version 2**
July Pegasids (175 JPE) (found in IMO calendars)
July γ-Draconids (184 GDR) (found in IMO calendars)
October Camelopardalids (281 OCT) (found in IMO calendars)
δ-Aurigids (224 DAU) (found in IMO calendars)

I will make this draft for now in case there are suggestions for additional improvements and corrections from our reviewers. I also have to check the database to make sure that every data are correct.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?
**Test Configuration**:
* Operating system: Windows 10
* Graphics Card: Nvidia Geforce RTX

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [x] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by worachate001** [comment]
I forgot that I have to update the SUG to reflect the change. It shouldn't take much time to finish.

**Comment by gzotti** [comment]
This is a great read! Thank you for your valuable improvements. I personally don't do much in the Meteors field and never went deep into this plugin, but if you managed to better replay historical records, this is very much welcome!

On point 13, you wrote you have updated database to version 2. This should make auto-updating easier: Check version on load, discard data and load defaults from program installation folder if wrong version. A problem may be users who keep old program versions and want to run both. On loading the new file, would they see problems, or just updated data? I.e., did the actual format change?

**Comment by alex-w** [comment]
Please check http://www.ta3.sk/IAUC22DB/MDC2007/Roje/roje_lista.php?corobic_roje=0&sort_roje=0 also

**Comment by worachate001** [comment]
@gzotti The format has changed. It looks like when the program starts, the file will be downloaded from https://stellarium.org/json/showers.json. If we replace the file with version 2, the problem may arise for people using older versions. I'm not sure how to properly handle this. We may have to use different file name like showers2.json ?

**Comment by worachate001** [comment]
> Please check http://www.ta3.sk/IAUC22DB/MDC2007/Roje/roje_lista.php?corobic_roje=0&sort_roje=0 also

Many of the new data come from that database.

**Comment by gzotti** [comment]
That's a possibility. Maybe not showers2, but MeteorShowers1.json. First, the name is clearer, and second, the number part could then act as further version number. But I never checked, is version number stored anywhere in the file and checked somewhere? Note that we still are "before version 1.0", so we can make changes that need not be compatible with earlier 0.* versions.  We will probably also rename a few properties, action names etc for better harmonisation before 1.0.   @alex-w ?

**Comment by alex-w** [comment]
> @gzotti The format has changed. It looks like when the program starts, the file will be downloaded from https://stellarium.org/json/showers.json. If we replace the file with version 2, the problem may arise for people using older versions. I'm not sure how to properly handle this. We may have to use different file name like showers2.json ?

We may have to use different file name for meteor showers data, but in this case we should add code to update URL of source data within plugin (see [example](https://github.com/Stellarium/stellarium/blob/295376a2dd1caf0367a11ce387253ec89b29ba8a/src/core/modules/NebulaMgr.cpp#L248)). In any way please describe new format in the Stellarium User Guide.

The next one important question: how to update the renewed JSON file correctly?

**Comment by alex-w** [comment]
> That's a possibility. Maybe not showers2, but MeteorShowers1.json. First, the name is clearer, and second, the number part could then act as further version number. 

The name "MeteorShowers.json" is clear and acceptable.

>But I never checked, is version number stored anywhere in the file and checked somewhere? 

Yes, the number of format version is verified within plugins.

> Note that we still are "before version 1.0", so we can make changes that need not be compatible with earlier 0.* versions. We will probably also rename a few properties, action names etc for better harmonisation before 1.0. @alex-w ?

The version of format is not related to version of program ;)

**Comment by alex-w** [comment]
A quick check: ZHR for Leonids have weird values for years 1833 and 1966 - why?

**Comment by alex-w** [comment]
Please add missing info into Help tab also

**Comment by worachate001** [comment]
> A quick check: ZHR for Leonids have weird values for years 1833 and 1966 - why?

What weird? Can you please be more specific?

**Comment by worachate001** [comment]
> Please add missing info into Help tab also

Yes, I forgot that too. Now I have to update both User Guide and Help tab and create a new MeteorShowers.json.

I have a question, Should we call this the version 3.0 of the plugin? We're currently at 2.0.6.

**Comment by alex-w** [comment]
> I have a question, Should we call this the version 3.0 of the plugin? We're currently at 2.0.6.

3.0 of course

**Comment by alex-w** [comment]
> > A quick check: ZHR for Leonids have weird values for years 1833 and 1966 - why?
> 
> What weird? Can you please be more specific?

1833 year: ZHR = 6000, but in historical chronicles (according wikipedia) we have 240000 in 9 hours, so, ZHR=26666.

**Comment by worachate001** [comment]
> > > A quick check: ZHR for Leonids have weird values for years 1833 and 1966 - why?
> > 
> > 
> > What weird? Can you please be more specific?
> 
> 1833 year: ZHR = 6000, but in historical chronicles (according wikipedia) we have 240000 in 9 hours, so, ZHR=26666.

There are wide-range of ZHR from various sources. These values are taken from Jenniskens P., Meteor Showers and their Parent Comets, Cambridge University Press (2006).

An opinion by the author at https://adsabs.harvard.edu/full/1995A%26A...295..206J (page 213-214)  indicated that ZHR=150,000 for 1966 is too high, it should be 10 times lower.

For 1833 storm of ZHR=6,000, he cited H. S. Sawyer, The Leonid shower of 1833. J. R. Astron. Soc. Canada 56 (1962), 215–221.

**Comment by alex-w** [comment]
> > > > A quick check: ZHR for Leonids have weird values for years 1833 and 1966 - why?
> > > 
> > > 
> > > What weird? Can you please be more specific?
> > 
> > 
> > 1833 year: ZHR = 6000, but in historical chronicles (according wikipedia) we have 240000 in 9 hours, so, ZHR=26666.
> 
> There are wide-range of ZHR from various sources. These values are taken from Jenniskens P., Meteor Showers and their Parent Comets, Cambridge University Press (2006).
> 
> An opinion by the author at https://adsabs.harvard.edu/full/1995A%26A...295..206J (page 213-214) indicated that ZHR=150,000 for 1966 is too high, it should be 10 times lower.
> 
> For 1833 storm of ZHR=6,000, he cited H. S. Sawyer, The Leonid shower of 1833. J. R. Astron. Soc. Canada 56 (1962), 215–221.

Well, probably we should add some notification for ZHR of the Leonid showers, because I saw ZHR over 100000 in some Russian books (I can re-check these data).

**Comment by worachate001** [comment]
I found an article by Peter Brown, The Leonid Meteor Shower: Historical Visual Observations

He disagreed with Jenniskens.

### 1833
The only precise numerical value for the 1833 display given by Olmsted (1834)...
... These observations (probably the best
numerically available for the peak of the 1833 display) imply
peak ZHRs in the range of 50,000–70,000. This is also consis-
tent with interpretation of the observation reported by Olmsted
(1834) from Boston almost an hour later of 38,000 as a lower
limit to the peak activity.
...The first vestiges of the shower were recorded
reliably near 13.3 Nov 1833, while the display continued into
daylight over the eastern United States until at least 13.5 Nov
1833. The best estimate of maximum is 13.4 UT Nov 1833 with
a peak rate of 60,000.

Other sources quote 50,000–150,000/h for the peak
(Kazimirchak-Polonaskaya et al. 1968, Yeomans 1981, Kresak
1980) but the basis for these values is not discussed in these
works.

### 1966
The highest rates were reported by Milon (1967) from a group
of observers under ideal skies at Kitt Peak in the United States.
Other observers in less ideal conditions reported rates 2 to 4 times
lower (Ashbrook 1967). However, given the large numbers of
Leonids visible, the very subjective methods of determining the
rates at the peak, the wide variation in reported ZHRs (from
45,000 to 160,000) at the peak and the uncertain range of ob-
serving conditions from the few observers who reported usable
information, it seems worth stressing that the actual peak mag-
nitude of the 1966 storm purely from visual data is uncertain to
at least a factor of 2; a best guess from all available visual obser-
vations would place the peak ZHR of the storm between 75,000
and 100,000. It is instructive to note that the lower limit for the
peak flux deduced from radar observations in 1966 by Brown
et al. (1997a) is equivalent to a minimum peak ZHR of 80,000.

_There are no visual observations from the peak which support
the conclusion of Jenniskens (1995) that actual peak ZHRs never
exceeded 15,000 during the storm. The widely quoted peak value
of 144,000 (cf. Yeomans 1981, Kazimirchak-Polonaskaya 1968)
is based largely on the account from Milon (1967) which, within
error, is not unrealistic, although it is certainly the highest count
made by any group of observers._

I will try to gather more information from other sources.

**Comment by gzotti** [comment]
Very good! Please add at least the references to the User Guide chapter. It is always good to state where our data and models come from.

**Comment by alex-w** [comment]
@worachate001 maybe in additional to other changes in the format of data possible change the format for fields "radiantAlpha", "radiantDelta", "driftAlpha", "driftDelta" too?

**Comment by alex-w** [comment]
I think the short info about "Local hourly rate" and "Current ZHR" in Help window for many users will be helpful also.

**Comment by worachate001** [comment]
> @worachate001 maybe in additional to other changes in the format of data possible change the format for fields "radiantAlpha", "radiantDelta", "driftAlpha", "driftDelta" too?

Thanks for suggestion, I was wondering it might be a reason behind that while working on the plugin. Anyway, I agree to change them  (will also try to explain that ZHRs in the Help window).

**Review by alex-w — APPROVED** [review]
Thank you very much!

@gzotti is it OK for you?

**Pull request merged**
