### PR TITLE
Allow compilation by disabling cmake flag WITH_QTWEBENGINE

### LINKED ISSUE #2004: Cannot build OnlineQueries on Raspberry Pi
### Expected Behaviour

install qtwebengine5-dev, then build as usual

### Actual Behaviour

package qtwebengine5-dev does not exist for RPi/Raspbian Buster

It seems we need a solution when QtWebengine cannot be found on some platform. Detect with cmake, set some variable, and call the URL with the system webbrowser. There is apparently a related issue for Mac/ARM.

### System
* Stellarium version: master as of 2021-10-31
* Operating system: Raspbian  Buster

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

### PR DESCRIPTION
**Pull request by gzotti**
### Description

On some platforms (ARM based) the QtWebEngine seems to be missing. The CMAKE flag WITH_QTWEBENGINE can now be set to false on those to disable the webbrowser view internal to the OnlineQueries plugin. The websites will instead be queried inside the system's default web browser.

* Currently this flag has to be manually set. It may be possible to set the flag as consequence of cmake being unable to find the QtWebEngine modules, and emit a warning to the developer during compilation. 

* If there is some style guide for cmake, I surely did something wrong! Advice?

Fixes #2004, #1982 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 10; Raspberry Pi 4.
* Graphics Card: irrelevant.

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — CHANGES_REQUESTED** [review]
Please update BUILDING.md also

**Comment by alex-w** [comment]
This PR fixed issue #1982 partially, because the latest one contains 2 problem: no module on Apple Silicon chips and regress in Qt 5.15.x.

**Comment by gzotti** [comment]
Do you know how to unset the flag if cmake cannot find the QtWebEngine module? This setting should emit a well-visible warning as well, so that it can be installed if available and the user just had forgotten.

What kind of regress has happened in 5.15? Mac only or all platforms? (I have not tried building this on 5.15 yet.)

**Comment by alex-w** [comment]
> Do you know how to unset the flag if cmake cannot find the QtWebEngine module? This setting should emit a well-visible warning as well, so that it can be installed if available and the user just had forgotten.

First problem: standard cmake cannot check the architecture of target platform (see solution [here](https://stackoverflow.com/questions/11944060/how-to-detect-target-architecture-using-cmake)), the second problem - on some platforms (e.g. linux) you may just not installed it in system, but it exists as package in repository or it just not installed from standard Qt installer. Of course you may change the logic of your cmake script to enable/disable flag WITH_QTWEBENGINE (see FIND_PACKAGE docs + you may add MESSAGE(STATUS ...) to inform the user).

> What kind of regress has happened in 5.15? Mac only or all platforms? (I have not tried building this on 5.15 yet.)

Right now I've tested it on linux and mac and I can reproduce the issue on mac only. It may be related to deprecation brige Qt-OpenGL on the Mac or changes the requirement of OpenGL version (3.2 + enable core profile).

**Comment by alex-w** [comment]
Important note: the regress on Mac may be not related to the QtWebEngine module!

**Comment by gzotti** [comment]
Ad (1) The logic may be:
```
if QtWebEngine module not found:
disable WITH_QTWEBENGINE
emit warning message to the user who tries to compile: "It seems you have not installed QtWebEngine, or it may not be available on this platform. Disabling its use."

```
This warning should not rush by but be visible as one of the last messages. 

Ad (2) please try to compile this on a Mac with 5.15 to see if QtWebEngine changed to the worse. Else, this OpenGL deprecation may hit us. It will do so sooner or later, at least on this platform.

**Comment by alex-w** [comment]
Building with option WITH_QTWEBENGINE=Off has no issues on Mac. Maybe this is related to OpenGL context (I didn't check details for implementation of independence the window of OnlineQuery plugin)?

**Review by alex-w — APPROVED** [review]
Thanks!

**Comment by alex-w** [comment]
Just for note: same problem (missing build dependencies) for architectures s390x and ppc64el

**Comment by gzotti** [comment]
Yes, I have also received the flood from canonical. The complete solution for CI would be to let cmake detect the presence of qtwebengine-dev, and if not found react with disabling the feature, plus emitting a warning (in case the human compiling on a "good" platform has forgot to install the available package). 

To be realistic: How many instance of Stellarium are running on s390x and ppc64el?

**Pull request merged**
