### PR TITLE
Separate data from presentation in eclipse KML generator

### PR DESCRIPTION
**Pull request by 10110111**
### Description
This refactoring will make the generation of the map more flexible:

* Easier to fix problems (which I've found a few),
* Possible to implement output in other formats than KML (e.g. an SVG map).

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] Housekeeping

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Did you fix compiling Qt5-based versions?

**Comment by 10110111** [comment]
> Did you fix compiling Qt5-based versions?

If you mean the missing `optional` include, yes: it's no longer used.

**Comment by alex-w** [comment]
`std::variant` causes issue in MSVC2017

**Comment by 10110111** [comment]
Oh, I should have included it...

**Review by alex-w — APPROVED** [review]
Thanks!

**Pull request merged**
