### PR TITLE
[WIP] Feature: Migrate Directory to use XDG path

### LINKED ISSUE #76: Switch to XDG base directory specification on Linux / Unix
Currently Stellarium is using $HOME/.stellarium for storing configuration and other data.

It's proper to switch to [XDG base directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) spec instead.

### PR DESCRIPTION
**Pull request by rharriso**
## TODO

* [ ] Create separate `data` directory.
* [ ] Migrate module and data folders to data directory
* [ ] Tests for updates to `StelFileMgr`
    * [ ] Data migration
    * [ ] Directory Defaults and arguments. 
* [x] Test for new `getEnv` utility function
* [ ] Test on windows
* [ ] Test on OSX
-----
Move default configuration directory to XDG path. This was discussed in issue #76 and listed again in issued #461 

### Description

This PR provides makes two changes:

* Move Default directory to use `QStandardPaths::AppConfigLocation`
* Create series of dialogs to migrate user data.

The decision of which user directory to use, works as follows.

1. If user directory defined by environment variable, use that dir
2. If legacy directory exists, and `QStandardPaths::AppConfigLocation` does not. Ask user if they want to migrate config.
    a. If yes, copy old config to new location.
    b. If no, ask if they want to delete that directory.    
3. `QStandardPaths::AppConfigLocation` exists, use that dir.

Fixes #76 #461 

### How Has This Been Tested?

Tested on Ubuntu 18.04, can test in OSX and Windows 10.

#### Test With legacy config directory, and no directory at `QStandardPaths::AppConfigLocation`

1. Start application
2. See dialogs as described above:
    * if migrated, see old config moved to new location
    * if deleted, see old config folder removed
    * If ignored, old config files remain in legacy directory.

## Environment

* Ubuntu 18.04
* Graphics Card: Nvidia 1060 (6GB), not relevant to these changes.

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rharriso** [comment]
I need some advice on testing these changes. 

I'm not experienced with C++ development, and it's not clear to me how I would test QT ui interactions. Should I add tests for the functions that return the different possible user paths?

**Comment by alex-w** [comment]
Thanks for patch!

But it has problems. Firstly, the compilation on Windows is broke now: https://ci.appveyor.com/project/alex-w/stellarium/builds/31485985/job/u7irqo8vm21nti84

The second problem - current implementation is not fully compliant to XDG. It is very similar to first iteration for adding XDG support, what I made around 8 years ago and which was declined. You are made the same error as I 8 years ago - according to XDG the data and config data should be placed in different directories, but you are placed it in one location.

**Comment by rharriso** [comment]
Would you prefer that the configuration be split in the same pr or in a follow up task?

**Comment by alex-w** [comment]
As far you started process migration to XDG support, then you might finalize it in same PR.

**Comment by axd1967** [comment]
( See also https://github.com/Stellarium/stellarium/issues/76#issuecomment-709196845 )

**Comment by rharriso** [comment]
@alex-w, sorry I don't if I'll be able to come back around to this.

:/

**Pull request closed without merging**
