### PR TITLE
Translated 2 Strings to Telugu

### PR DESCRIPTION
**Pull request by sripathroy**

### CODE REVIEW

**Comment by sripathroy** [comment]
Changes are made to the Strings Specified. Unsure why the build failed.

**Comment by alex-w** [comment]
Thanks!

**Comment by gzotti** [comment]
sripathroy, translation is most comfortably made on our Launchpad site: 
https://translations.launchpad.net/stellarium/trunk/+lang/te
This saves us (mostly Alexander) much manual work.

Thank you for your contributions!
Regards, Georg

**Comment by sripathroy** [comment]
Shall i close this pull request?

**Comment by alex-w** [comment]
I've added your contribution in the main translations, so, this pull request may be closed now. Thanks for translation!

**Pull request closed without merging**
