### PR TITLE
Restore drawing of orbits on open KeplerOrbits.

### PR DESCRIPTION
**Pull request by gzotti**
### Description
It seems that a change in the orbit code in 2021 suppressed drawing of Kepler orbits.
This should fix it. Objects on Kepler orbits are drawn orbit_good days around the epoch date. 

Another thing to fix here is the removal of the entry "orbit_visualization_period" in ssystem_*.ini. 
For closed orbits with special functions, this should be equal to orbit_period. 
For Kepler orbits, this is governed by orbit_good, or orbital period computed from the elements. 

Fixes # (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

- Check that e.g. Hyakutake (C/1996 B1) and Hale-Bopp (C/1995 O1) show their inner orbits. 
- Load 1000_comets.ini and use SolarSystemObserver to see numerous comet orbits flash in and out of visibility as comets come and go in rapid timelapse. 

**Test Configuration**:
* Operating system: Windows 11
* Graphics Card: Geforce (irrelevant)

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [x] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
It seems also closed KeplerOrbits are not plotted :-(

**Comment by gzotti** [comment]
OK, I hope it's done.

**Comment by gzotti** [comment]
@alex-w , @10110111 any further comments?

**Comment by alex-w** [comment]
Sometimes orbits near perihelion is ugly - is it possible doing them smooth within current PR?

**Comment by gzotti** [comment]
This was always ugly with discrete time intervals and highly elongated ellipses: 2nd law of Kepler... 
Also, the trick for displaying the object inside the orbit when plotted &pm;1/2 orbit_period does not work with "open" orbits when we show the orbit inside the "orbit_good" time only, so the comet/interstellar object does not run on the orbit line. Solving these may be a future issue.

**Review by alex-w — APPROVED** [review]

**Comment by 10110111** [comment]
> This was always ugly with discrete time intervals and highly elongated ellipses: 2nd law of Kepler

The same Kepler's law could be used for smarter discretization. Not necessarily numerically exactly, but at least by estimating the expected length of the orbit segment vs time slice.

**Comment by gzotti** [comment]
Yes, I think it could work to vary mean anomaly with regular steps (not time, just regular angular intervals between the angles for begin and end of requested interval) and find true anomaly from that. Probably the KeplerOrbit class must learn to do that.

**Pull request merged**
