### PR TITLE
WIP: Update Python scripts to Python3 and improve

### LINKED ISSUE #77: Update Python scripts to Python 3
Are there any plans?

I would be interested in it.

### PR DESCRIPTION
**Pull request by IceflowRE**
Iam currently not working anymore on this Wip.
If you want to collaborate or answer some of the open questions below, pelase ping me

---

All python scripts will be updated to python 3 compatibility and improved with new features introduced in python 3.

### Description
Python 2 will reach its end of life "soon".

Dependencies/ Requirements will change from Python 2 to Python 3.6.

Fixes #77 .

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

No Python tests are included currently and its not planned to do this with this PR.
A still working functionality must be proven manually before merging.

## Checklist:

- [x] My code follows the coding style of [PEP 8](https://www.python.org/dev/peps/pep-0008/).
- [ ] **TODO** I have performed a self-review of my own code
- [ ] **TODO** I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Update overview
- Overall a usage for every helper script seems to be missing?
- [ ] plugins/
    - [ ] Exoplanets/util/exoplanets_get.py
        - Update to urllib3
    - [x] RemoteControl/util/update_translationdata.py
    - [x] Satellites/util/name_to_number.py
- [ ] skycultures/western_SnT
    - [ ] generate_constellationship.py
        - reads from STDIN?
        - prints to console?
    - [ ] generate_star_names.py
        - prints to console?
- [ ] utils/
    - [ ] desktop/
        - [ ] desktoppo.py
            - uses multiple .po files, but only one exists?
        - [ ] transconverter.py
            - Add ArgumentParser
            - Rework
    - [ ] DSSToStellarium/
        - Rework
        - Fix imports
        - [ ] createUpperToastLevels.py
        - [ ] dssUtils.py
        - [ ] generateFullPlate.py
        - [ ] prepareAllPlates.py
        - [ ] UTdssUtils.py
    - [ ] dssHeaderToJSON.py
        - `astlib` cannot be installed on Win and python 3, supports only Python 2 (or the installer is broken on python 3), project seems to be abandoned
    - [ ] genSkyTiles.py
        - `astlib` cannot be installed on Win and python 3, supports only Python 2 (or the installer is broken on python 3), project seems to be abandoned
    - [ ] links_check.py
    - [ ] mac_app.py
    - [ ] runAIIDSS.py
    - [ ] skyTile.py

### CODE REVIEW

**Comment by alex-w** [comment]
This pull request **fixes 4 alerts** when merging ab6c4d8b6a490c859e45e5cefebd9aab22891cf5 into 9e19ebbbcbbfd8c0c85089a0c70dd0ed9f8c9317 - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-52e8fc5ae0a4b38a1fbce56b0111ce4af2207d60)

**fixed alerts:**

* 4 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alex-w** [comment]
This pull request **fixes 4 alerts** when merging 54568425befff826542483a5792d02519db2d099 into 9e19ebbbcbbfd8c0c85089a0c70dd0ed9f8c9317 - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-c8f7521561f7a4b41761d5c0fc0e39127a3dbad2)

**fixed alerts:**

* 4 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alex-w** [comment]
I think LGTM checks python2 rules here

**Comment by alex-w** [comment]
What about adding #!/usr/bin/env python3 - I guess it may helpful here.

**Comment by gzotti** [comment]
> 
> 
> I think LGTM checks python2 rules here

You can configure LGTM to check Python3

**Comment by alex-w** [comment]
This pull request **fixes 5 alerts** when merging 01c34306b97d5633074fa8ffbd7db831a8f766b0 into 160c18d58387f01e0b50fd369ff041048fd6422a - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-ed113a1317ebb58531c66c975ba0c1f43e9c5154)

**fixed alerts:**

* 5 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alex-w** [comment]
This pull request **introduces 5 alerts** and **fixes 5** when merging 021889260773e08b9f1f10b2b94e1335b9f23121 into d7a15e41a2a98bb709220c8849805b1c890e0068 - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-da96bf52a8a219ca8c29e21deaa0aafa4f0724c2)

**new alerts:**

* 3 for Unused local variable
* 1 for Unreachable code
* 1 for Wrong number of arguments in a call

**fixed alerts:**

* 5 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by gzotti** [comment]
Any update here? Now it's EOL really soon for Python2. I cannot do a review, though, as I am not familiar with these tools.

**Comment by IceflowRE** [comment]
No i actually stopped here.
1. Iam not familiar with all those tools and some do something i dont even understand
2. Some are using a third party library (`astlib`) who is only Python 2 -> porting those stuff is out of my horizon
3. The progress is written in the first message -> some have questions marks like the printing to the console: why we use python to print to console and (probably) just queuing it to a text file instead of using python power directly or some tools use files which do not longer exist or may be created beforehand
4. Iam open to work on this again, but i need a bit more input of those original tool developer or people who are working with those that we get
    - What are those doing?
    - What can be improved?
    - What can be removed?
I would suggest that to create a something on discord? whatever (i will **not** work with a mailing list)

**Pull request closed without merging**
