### PR TITLE
Nebula nicknames: format and clear some

### PR DESCRIPTION
**Pull request by silas1037**
#11

### CODE REVIEW

**Review by gzotti — APPROVED** [review]
No objection, thanks!

**Review by alex-w — APPROVED** [review]

**Comment by alex-w** [comment]
@silas1037 I have a scan copies of few books to validate the common names of DSO, but I have no time for it. Maybe you can do this work? I can share my books.

**Comment by silas1037** [comment]
> @silas1037 I have a scan copies of few books to validate the common names of DSO, but I have no time for it. Maybe you can do this work? I can share my books.

Of course. You can send links to my mailbox or other ways.

**Comment by alex-w** [comment]
> Of course. You can send links to my mailbox or other ways.

Sorry, I haven't your email address :'( Would you contact to me on address in the my profile?

**Comment by alex-w** [comment]
Oh! I catch your email, thanks!

**Pull request merged**
