### PR TITLE
Update M31 texture and add some DSO textures

### PR DESCRIPTION
**Pull request by sunshuwei**
Update M31 texture and add some DSO textures.
License information has been added to CREDITS.md.

### CODE REVIEW

**Comment by alex-w** [comment]
Some textures just removed - why?

**Comment by sunshuwei** [comment]
I have recovered them.
However, ic2948-trev.png, ic2944-virgo.png, they are Running Chicken Nebula, which are not currently used.
n1365.png, fornax cluster already contains it.

**Comment by alex-w** [comment]
It’s very strange.

**Comment by sunshuwei** [comment]
Maybe forgot to delete them before.
The same is true of sadr.png. It is the same object as GammaCygni-vasey.png.

**Pull request merged**
