### PR TITLE
Switch to v1.4.3 of QXlsx (v1.4.3-stel.0)

### PR DESCRIPTION
**Pull request by alex-w**
QXlsx was updated to version 1.4.3 with patch to use our copy of qtcompress library

### CODE REVIEW

**Comment by gzotti** [comment]
Anything in particular I could test?

**Comment by alex-w** [comment]
Please generate xlsx files (through AstroCalc for example) and open these files in various electronic tables. I've tested it witih LibreOffice Calc, MS Excel and Apple Numbers - everything OK.

**Comment by axd1967** [comment]
(this is an example where the **vendor branch** mechanism can be used.)

**Comment by gzotti** [comment]
The buttons in AstroCalc with labels "Save positions", "Save ephemeris", etc. could be clearer when labeled "Export positions...", "Export ephemeris..." etc. The actual export seems to work well.

**Comment by alex-w** [comment]
> The buttons in AstroCalc with labels "Save positions", "Save ephemeris", etc. could be clearer when labeled "Export positions...", "Export ephemeris..." etc. The actual export seems to work well.

OK, I'll rename the text of labels tonight

**Comment by alex-w** [comment]
@gzotti OK, renaming is done

**Comment by gzotti** [comment]
Thanks, this just looks better. 

I am not fully sure: Is the code else just imported with new versions (with copyright notes removed by the original author!), or did you change something? In the first case, I approve. Else the required copyright notes should remain in the code. And probably some 1-line README with URL of origin or so? Or is the origin of this directory documented elsewhere?

**Pull request merged**
