### PR TITLE
New zoom algo

### PR DESCRIPTION
**Pull request by alex-w**
This patchset fixes the trackpad issue on the macbook pro. The behavior is slightly different that before so would be good to test a bit more to see if it is acceptable in all situation.

The new algo doesn't ease in the zoom animation for small changes, and ease in and out large zoom changes. The previous algorithm systematically eases in when we zoom out and systematically eases out when we zoom in. The problem with easing in small zoom changes is that the behavior then depends a lot on the frequency of wheel events, hence the trackpad bug.

Issue #529

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by silas1037** [comment]
@alex-w 
Have it been tested on arm device (Linux)? 
#529 
I scaled fail on armv7 android.
I afraid the code causes bugs cross-platforms.

**Comment by alex-w** [comment]
I tested on desktop linux only.

@silas1037 are you found a bottleneck for new algorithm?

**Comment by silas1037** [comment]
> @silas1037 are you found a bottleneck for new algorithm?

I just revert [code here](https://github.com/silas1037/stellarium/commit/0b5a83b685c33d1e8cb4123f5bd76836cfa6338f) and got different running results.

old code: armv7 android could zoom in/out 
new code: run fail

**Comment by gzotti** [comment]
Define "fail"? I built and ran Stellarium on my Raspberry 4 (regular current Raspberry OS) yesterday. Zoom with 2-finger shift works. Time drag with Ctrl+2-finger-drag works. Click (identify), double-click (center) work. What else? 

I cannot comment on Android, because we don't support it.

**Comment by silas1037** [comment]
Thanks.

**Comment by alex-w** [comment]
@silas1037 please check the current master - probably I found source of error

**Comment by guillaumechereau** [comment]
@alex-w: you didn't merge the new-zoom-algo branch totally it seems.  Maybe that is the source of the bug?

**Comment by alex-w** [comment]
> you didn't merge the new-zoom-algo branch totally it seems. Maybe that is the source of the bug?

The branch was merged :) The problem is coming when duration is zero, so, I've added workaround to avoid zero in duration value.

**Comment by silas1037** [comment]
> @silas1037 please check the current master - probably I found source of error

Great. It works.

**Pull request merged**
