### PR TITLE
Moon RTS

### LINKED ISSUE #2024: Rise, transit and setting time changes during the same day
Rise, transit and set times of an object should remain constant during the same day. But in Stellarium if you fast forward of some hours, the rise, transit and set time change two or more times in the same day.

### To reproduce
Select an object (e.g. the Moon) when it's just rised over the horizon. Start forwarding time  by hitting the +1 hour button. Monitor the rise, set and transit time in the information list: they will change a couple of times during the same day.

### Discussion
While it could be argue that after an event (e.g. after an object has rised over the horizon) that information could be refered to the next event (the one from the day after), this is not a suitable behaviour in my opinion, since people would like to know when is the time of that event in that specific day. But even so, these times should not change more than one time per dey.

### System
* Stellarium version: 0.21.0
* Operating system: W11
* Graphics Card: Nvidia

### PR DESCRIPTION
**Pull request by worachate001**
### Description
Rise, Transit and Set times of the Moon are not stable throughout the day. I have a solution that seem to effectively fix it. The idea is recompute a few more times at the instance of RTS (no interpolation involved). The algorithms is only applied to the Moon (for now). It may be able to apply to other objects in the future.

Fixes #2024 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Ubuntu 20.04
* Graphics Card: irrelevant

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
Thank you! I have also considered refining our solution using binary search as there is no direct way when taking parallax shift into account. I am busy with other things right now but want to check this in the next days. In principle this is needed for all close and fast objects, fortunately this is only the Moon :-)

**Comment by worachate001** [comment]
@gzotti Yes. My very next target are Phobos and Deimos. I see that there are large errors there.

**Comment by alex-w** [comment]
If you want to fix RTS for Phobos & Deimos also, then some checks should be changed IMHO. For example: `if (getParent()==core->getCurrentPlanet())` to check if selected body is the moon of current planet.

**Comment by worachate001** [comment]
Thanks @alex-w Should we push current PR before looking at other cases?

**Comment by alex-w** [comment]
> Should we push current PR before looking at other cases?

Probably "yes",  because other cases is other cases and all of them do not touches specific bug.

> I think it's looking good now for the Moon.

A quick-check gives perfect data for the Moon! Thanks!

**Review by alex-w — APPROVED** [review]
Thanks!

@gzotti?

**Comment by gzotti** [comment]
Hmm, moon looks perfect now, indeed, however, at cost of setting core->setJD() which initiates all other computations (whole SolarSystem). (using core1 is camouflage to avoid the const thing, but there is only 1 core.) My solution (IIRC) avoided that, but yes, the atmosphere and parallax are bad when we need high accuracy. 

The display in the "Files changed" tab here looks strange and confusing. @worachate001 Did you only insert the if(Earth/Moon) case, or did you also change the result of the more general planet solution? 

I think the next extension could be a variant which finds RTS when sun/moon are sitting "above" the horizon (Just invert h0!), and with center in horizon. Not sure if we need all distinct versions, or rather configure which variant of h0 should be used. 

And then finally variants of all those ideas which takes the landscape into account (start with current solution, then test with landscape->getOpacity(azAlt), increase/decrease time in minute steps to avoid holes in the texture. I envisioned to have this around v0.13... ).

**Comment by worachate001** [comment]
@gzotti I just inset if ((getEnglishName()=="Moon") && (loc.planetName=="Earth")) and keep all the old codes. That means all other objects are using the previous algorithm. I have tested the new method with some normal moons like Io, Europa, ..., it seems to work well, but for fast movers like Phobos/Deimos, we need another solution.

**Comment by gzotti** [comment]
OK, then we can merge this part so far. 
For Mars, we must likely do something else, when the orbital duration is less than the planet's rotation period. Then some principal assumptions fail. Maybe a binary-search for 1/2 orbit durations around "now" for rise/set events. It would be good to do that with only the planet/moon, not the full core, but I cannot work it out now, this gets quite messy pretty soon :-)

**Comment by alex-w** [comment]
> The display in the "Files changed" tab here looks strange and confusing. @worachate001 Did you only insert the if(Earth/Moon) case, or did you also change the result of the more general planet solution?

It looks like EOL or formatting settings issue

**Comment by alex-w** [comment]
OK, @gzotti  I'll merge it

**Pull request merged**
