### PR TITLE
Exoplanet plugin with QtChart

### PR DESCRIPTION
**Pull request by gzotti**
This shall switch the scatter plot in the ExoPlanets plugin from QCustomPlot to QtCharts. 

During development, this displays old and new diagrams side-to-side for comparison. Plotting style, colors, axis labels etc. should be identical to the old version.

### Description

Fixes: Qt6-inflicted deprecation

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win10
* Graphics Card: Geforce 960M

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
@alex-w I have now removed the requirement to explicitly press the "Plot" button, it goes whenever some input changes. 

The only real difference now is the behaviour of QChart for plots with log axes. While QCustomPlot does "something" (I have not found the relevant documentation), QChart plots nothing if at least one value is zero or negative (see metallicity). I am unsure what to do: When creating the series, I could of course filter the values to remove all pairs with zeros/negative numbers if the respective plot axis is set to log. 

The QCustomPLot is also not free from issues. Switching away from log with negative numbers needs another "Plot" press to show all values.

**Comment by alex-w** [comment]
Not all data can be plot with log axes - I didn’t added a mistake-proofing feature (a foolproof concept).

**Comment by gzotti** [comment]
Are you then OK if I remove the old plot and only write in the SUG that "plots with log axes may fail if some values can be 0 or negative"? Else the exclusion scheme may become a bit "messy" ("complex method").

**Comment by alex-w** [comment]
Of course, go ahead

**Comment by gzotti** [comment]
Before merge, I want to go over the SUG chapter and maybe add/change something about the plots. Else I think the code is OK.

**Comment by alex-w** [comment]
Hmm... Stellarium crashes at exit

**Review by alex-w — APPROVED** [review]
The Stellarium crashes at exit in master also, so, the issue is not in this PR

**Comment by gzotti** [comment]
@alex-w In the root CMakeLists.txt we require Qt5PrintSupport, "just for qcustomplot". If no longer required, we could remove it, or is it now used by something else? (XLS?). The PrintSky plugin will need it obviously, in case we create a useful plugin, but this is another branch.

**Comment by alex-w** [comment]
No need Qt5PrintSupport now, you can remove or commented it

**Pull request merged**
