### PR TITLE
[refactoring] "Specific Time"

### LINKED ISSUE #1394: Quick way to jump to the next solstice/equinox
Now that Stellarium has fixed nutation, we can accurately display the time of solstices and equinoxes. It would be great to have a button, or a key command, to jump to the next solstice or equinox point. When I press it, the time is set to 2020-12-21 13:30 UTC, and when I press it again, I go to 2021-03-21 09:37 UTC etc.

### PR DESCRIPTION
**Pull request by alex-w**
### Description
This pull request contain 2 parts:
- [x] The code for compute the time of equinoxes and solstices and set of actions to jump to the solstice/equinox at current, next or previous year. The default hotkeys for actions are not defined.
- [x] The code and actions for jump to the moments of rise, set and transit (include twilight) of selected objects. This code was moved from `StelObjectMgr` class.

The computation the equinoxes and solstices are divided on separate methods now and both solutions are obtained from "Astronomical Algorithms". Valid range -1000..+3000 with zero values outside of it. 

Notes from the [review](https://github.com/Stellarium/stellarium/pull/2497#pullrequestreview-1023516881) of previous solution: 
- [x] You are always computing all 4 dates and then use just one. This is usually not a problem with today's fast PCs, but a principal waste of computing (_fixed by dividing the methods_ -@alex-w)
- [x] Add source! This is from Astronomical Algorithms (2nd ed.), ch.27. (_fixed by adding the info_ -@alex-w)
- [x] It is only for -1000...+3000 and delivers 0 or does nothing outside those dates. Most users only interested in their own lifetimes will not notice. However, a more general approach should find 0/90/180/270 from ecliptical longitudes in our own algorithms, be it `VSOP` or `DE*`. The Calendars plugin has such a function. `Calendar::solarLongitudeAfter()`. It also uses its private version of solar longitude, to stick to its source book, but this and related functions could be used for a more general solution. For now, you can add these functional deficiencies as code and SUG comments, and add into the Doxygen a **todo** note that we don't forget to improve this function later. Or we try to solve it now for good. (_at the moment I've added **todo** notes_ -@alex-w)

Fixes #1394

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Additional features are not implemented and I want to see some comments (votes?) about the "expectations" of these features.

@gzotti @sushoff @worachate001 @Jocelyn1109 @Atque @axd1967 @johnbellora

**Comment by Atque** [comment]
I for one prefer menus over hotkeys. As I said in the previous PR, I would like a menu where the equinox/solstice dates and times are given for a given year, and an arrow or button, which when clicked sets the time to the corresponding equinox/solstice. A similar window could be used for the different stages of twilight (civil, nautical, astronomical), rises/transits/sets of an object and even lunar phases, if there is code to support it.

**Comment by alex-w** [comment]
> I for one prefer menus over hotkeys. As I said in the previous PR, I would like a menu where the equinox/solstice dates and times are shown for a given year, and an arrow or button, which when clicked sets the time to the corresponding equinox/solstice. A similar window could be used for the different stages of twilight (civil, nautical, astronomical), rises/transits/sets of an object and even lunar phases, if there is code to support it.

I planned add “buttons” into AstroCalc/Almanac tool. This PR is first step for the new tool. The features, which I marked as “additional” are optional and both can be implemented later or not implement. I need some feedback or voting for these features.

**Comment by axd1967** [comment]
A quick forward to a specific time at startup feels unneeded to me - I think this will not be used often; also, shortcuts already make this possible. Probably this is also possible with a user-written startup script (I did not check if these new methods can be invoked via scripting; otherwise that would be very recommendable.)


Also
- I still believe that #1328 is an interesting way to extend Stellarium UI (as an alternative to menu actions), even if it will slightly change the behaviour of the F7 dialog (assuming the current - Qt? - behaviour can be tweaked)

**Comment by alex-w** [comment]
Ok, I’ve removed all additional features from description of PR, because both have a low priority at the moment.

**Comment by alex-w** [comment]
@gzotti please review the pull request

**Comment by gzotti** [comment]
> I for one prefer menus over hotkeys. As I said in the previous PR, I would like a menu where the equinox/solstice dates and times are shown for a given year, and an arrow or button, which when clicked sets the time to the corresponding equinox/solstice. A similar window could be used for the different stages of twilight (civil, nautical, astronomical), rises/transits/sets of an object and even lunar phases, if there is code to support it.

As a minimum with only configurable actions this PR may be OK. But with @Atque 's screenshot in the other PR this could also justify another main dialog reachable from the left menu bar. (Shift-F5? F8?) It could show buttons for all those actions. Probably useful to separate this away from the huge AstroCalc dialog, to keep the screen clean. (I had actually considered adding such a quick-access page to the RemoteControl UI)

**Comment by alex-w** [comment]
I had an idea for compact GUI for these actions for one subpage (AstroCalc/Almanac/Seasons) of new tool. But this is task for another PR.

**Comment by gzotti** [comment]
> I had an idea for compact GUI for these actions for one subpage (AstroCalc/Almanac/Seasons) of new tool. But this is task for another PR.

Yes, you wrote that before. But I think a separate small dialog (high, narrow, small buttons, something to move to the right screen edge) would be better, as it covers less of the screen. Indeed, a topic for another PR.

**Review by gzotti — APPROVED** [review]
As first step towards possible GUI changes this looks OK.

**Comment by gzotti** [comment]
> A quick forward to a specific time at startup feels unneeded to me - I think this will not be used often; 

We already have the possibility to start with "system date at XX:XX hours". A new option like "system date at end of civil/nautical twilight" would be fine IMHO. Sure, could also be done in a startup.ssh for "power users".

**Comment by alex-w** [comment]
> > A quick forward to a specific time at startup feels unneeded to me - I think this will not be used often;
> 
> We already have the possibility to start with "system date at XX:XX hours". A new option like "system date at end of civil/nautical twilight" would be fine IMHO. Sure, could also be done in a startup.ssh for "power users".

Yes, but not for regular users.

**Pull request merged**
