### PR TITLE
Extend the JavaScript classes corresponding to Vec3f and Vec3d. See t…

### PR DESCRIPTION
**Pull request by wlaun**
…he comments in StelScriptMgr.cpp.

Added test.testJavaScripting.[ch]pp to test the scripting side.

### Description

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Could you fix code style issues also?

**Comment by wlaun** [comment]
*Do you mean all braces on a line on their own?* I'll do so if it is
necessary but note that I have a small screen and wasting extra lines for
the damn braces and my eyes won't accept small fonts. *Anything else
besides the braces?*

*-W*

**Comment by alex-w** [comment]
All braces and spaces

**Comment by wlaun** [comment]
Please describe *exactly* what you mean by "spaces". Indentation looks good
in emacs. How do you want to have indentation? Don't be so
niggardly with your words.
-W

**Comment by alex-w** [comment]
I'm re-check all spaces in the code and all of them is OK - sorry for false request

**Pull request merged**
