### PR TITLE
Fix styles of QMessageBox and QColorDialog

### PR DESCRIPTION
**Pull request by ultrapre**
Similar PR as #1395

image

image

image

image

image

### CODE REVIEW

**Review by alex-w — CHANGES_REQUESTED** [review]
The text in QMessageBox is very difficult to read with this style - please add QSS rule to resolve this problem.

**Comment by ultrapre** [comment]
> The text in QMessageBox is very difficult to read with this style - please add QSS rule to resolve this problem.

add new rules into .css or remove fix for QMessageBox?

**Comment by alex-w** [comment]
Probably add new rule into .css will be better solution

**Comment by ultrapre** [comment]
@alex-w  How about this:

image

image

**Comment by alex-w** [comment]
Good! Maybe same background style apply to color chooser also?

**Comment by ultrapre** [comment]
Okay, wait for moment

**Review by alex-w — APPROVED** [review]

**Comment by ultrapre** [comment]
https://github.com/Stellarium/stellarium/commit/5a7beec0ceea7af4504eb129deb1ca67d7eadff7#commitcomment-45571558

**Pull request merged**
