### PR TITLE
Tweak screen intersect callback

### LINKED ISSUE #2955: Text of coordinates is clipped at the top of the screen
Text of coordinates is clipped at the top of the screen

### Expected Behaviour
Full text readable on the screen

### Actual Behaviour
For screenshot see attachment

### Steps to reproduce
Start Stellarium, turn on "Equatorial Grid", look at the top of the window

### System
* Stellarium version: Stellarium 1.22.5
* Operating system: windows 10
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
Stellarium Text Clipped

### PR DESCRIPTION
**Pull request by gzotti**
This is a small correction to the screen intersect callback to label SkyLines. It shall avoid loss of a few characters which are shifted out of the actual screen area by shallow angles.

There are two possible ways. Shifting the text, or changing the placement position. Currently it seems the first is enough, but I have left the other way commented out. 

Please TEST! 

### Description

Fixes #2955 (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win11
* Graphics Card: Geforce

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 10110111** [comment]
In the following screenshot, the `75.0000°` at the top (two copies to the left and right of the horizontal center) are still clipped. Also, they seem to be too far from the line that they denote (or do I assign them to the wrong line?).

stellarium-013

Similarly in the following screenshot, the `200.0000°` on the left border is clipped, and the same about `10.0000°` (?) in the lower half of the image. Also notice the `40.0000°` at the top in the left half.

stellarium-014

**Comment by gzotti** [comment]
The solution may not be perfect, but certainly better than before. 

It seems the text angles along the extremes, just where the text would be shifted a lot, come in discrete steps, so that the labels appear detached from their lines, but just at the very edge of visibility. 

Maybe I can add a minimum angle of applicability to avoid this thing:
image

**Comment by gzotti** [comment]
@alex-w @10110111 please also test this one. As long as I don't place the labels completely on the other side of the line (which I don't intend to do), a few pixels may still be clipped off, but IMO the situation is much better now.

**Review by alex-w — APPROVED** [review]
Not complete solution, but acceptable

**Review by 10110111 — APPROVED** [review]
OK, at least the clipping is not as severe as it used to be, although text placement and orientation still leaves a lot to be desired.

**Pull request merged**
