### PR TITLE
Add contact times for lunar eclipses in AstroCal

### PR DESCRIPTION
**Pull request by worachate001**
### Description
Double click an item will also display predicted contact times and additional data for each contact of the eclipse on selected date.

1. Horizontal coordinates of the Moon
2. Zenith latitude/longitude or Sublunar point - useful to draw visiblity map (in the future?)
3. Position angle of contact point
4. Axis distance (distance between the Moon and shadow axis)

### Screenshots (if appropriate):
lunareclipse-circumstances

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Linux Mint 21

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
What are meaning longitude and latitude in second table?

**Comment by alex-w** [comment]
What about export both tables?

**Comment by worachate001** [comment]
> What about export both tables?

By adding another button and export to a separate file?

**Review by alex-w — APPROVED** [review]
Thanks for good addition!

**Review by gzotti — APPROVED** [review]
Looks good! Also easy to understand for the user.
Thank you!

**Pull request merged**
