### PR TITLE
Added support public version of Stellarium

### PR DESCRIPTION
**Pull request by alex-w**
### Description
This pull request introduces splitting version number of Stellarium onto 2 partially independent versions - "inner version" (i.e., 0.22.3) and "public version" (i.e., 22.3) of Stellarium. This solution avoiding troubles for releasing two series of Stellarium in same time - series 0.x for releases, based on Qt5 and series 1.x for releases, based on Qt6. Plus 2 digits for version numbering of the planetarium are used already by many regular users.

As extra feature I've added 2 extra lines into About dialog - "Version..." and "Based on Qt...". The first one contains inner version of the planetarium and the second one contain version of Qt which was used for building the Stellarium. The second extra feature - refactored displaying version number on the splash screen.

The new feature is backward compatible and probably should be merged into master after 1.0 release.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gzotti — APPROVED** [review]
Looks good to me.

**Comment by gzotti** [comment]
I hope we can release 1.0 instead of 0.22.3. Not sure how "1.0" will appear in this PR. Or we simply call the next release already 22.3, but (manually) paint a big 1.0 on the splash screen and the User Guide's cover, just for this release, which will have 0.22.3 (Win 32bit, Ubuntu 18/20) and 1.22.3 (Win64, Mac, Ubuntu 22) builds... 
If there is any blocker, we must keep the release at 0.22.3, though. Maybe I should therefore have the Scripts fixed first. I just fix a few more deprecated pieces, then continue there. So it may be better to wait until after the Script issue is done, early next week or so (hopefully).

**Comment by alex-w** [comment]
OK, I think we can postpone question about version number to the September.

**Comment by gzotti** [comment]
I am quite sure we can give what would have been publicly expected to be 0.22.3 finally the symbolic "1.0" label.  I think all Qt6 troubles have been solved? Scripting, Audio/Video players work again (PR merge pending). I still don't know how to best bring the "1.0" into the limelight. Maybe a special splash screen for this release? Else IMHO this can now be merged to prepare for the equinox release. @xalioth ?

**Comment by alex-w** [comment]
I've added big numbers for splash screen for releases ;)

**Pull request merged**
