### PR TITLE
Nebula nicknames: correct some nicknames from DSC

### PR DESCRIPTION
**Pull request by silas1037**
Malus Cluster is NGC 2547, not NGC 2557, a typo
_HT Page 219_
image

### CODE REVIEW

**Comment by silas1037** [comment]
* correct NGC4699 (HT68) and remove “Lagoon Nebula” to NGC6530 (!= M8)

**Comment by silas1037** [comment]
image

>NGC  5195            _("A Justifiable Replacement for M51") # SD

**Comment by gzotti** [comment]
> Now the name of M51B need to be corrected. But it's better to remove it but not to name M51B as "A Justifiable Replacement for M102"? Or rename to M51B, for search need.
> 
> > NGC  5195            _("A Justifiable Replacement for M51") # SD

Thanks for this. I always wondered what the seemingly stupid name should mean. If we keep it, I will probably consider disabling SD as soon as we allow disabling sources to display.

**Comment by silas1037** [comment]
Maybe it's a typo to NGC1912 (M38 - Starfish Cluster)? I cannot see any special from this mag11 OCL. 

>NGC  1922            _("Starfish Cluster")

**Review by alex-w — APPROVED** [review]

**Pull request merged**
