### PR TITLE
Oculars: begin code cleanup

### PR DESCRIPTION
**Pull request by treaves**
### Description
This is the start of code cleanup.  But as there is so much to do, it's going to take too long to do it at once.  This needs to be merged into master before more work can cinque; I just lost a few days of work due to a bad merge from upstream.

### CODE REVIEW

**Comment by alex-w** [comment]
Please check CI/Linux and CI/AppVeyor reports.

**Comment by gzotti** [comment]
Interesting new syntax, I have never seen the "auto XY() --> type" . Are there real benefits? Cannot say. Makes reading harder for me. 

Do I understand I shall definitely no longer bother with #1521. Fine for me, as long as our intended functionality does not suffer: 

* separate view settings (store+reconfigure a few visibility settings on activation of Ocular or Sensor) 
* optional auto-estimate of telescopic visibility conditions
* store current state of those and restore the cached main view settings on exit to main view.

**Comment by treaves** [comment]
> Please check CI/Linux and CI/AppVeyor reports.

Yes, those build setups are broken. Not the code.

**Comment by treaves** [comment]
> Interesting new syntax, I have never seen the "auto XY() --> type" . Are there real benefits? Cannot say. Makes reading harder for me. 
> 
> 
> 
> Do I understand I shall definitely no longer bother with #1521. Fine for me, as long as our intended functionality does not suffer: 
> 
> 
> 
> * separate view settings (store+reconfigure a few visibility settings on activation of Ocular or Sensor) 
> 
> * optional auto-estimate of telescopic visibility conditions
> 
> * store current state of those and restore the cached main view settings on exit to main view.

There are benefits to the trailing returns. 

Yes, I intend to do that functionality and more.

**Comment by axd1967** [comment]
> Interesting new syntax, I have never seen the "auto XY() --> type" . Are there real benefits? Cannot say. Makes reading harder for me.

https://stackoverflow.com/a/11215414/605463

**Comment by alex-w** [comment]
> > Please check CI/Linux and CI/AppVeyor reports.
> 
> Yes, those build setups are broken. Not the code.

Syntax errors in the code are not code problem. Nice!

**Review by alex-w — CHANGES_REQUESTED** [review]
Please split Q_DISABLE_COPY_MOVE(Class) on 2 macro - Q_DISABLE_COPY(Class) and Q_DISABLE_MOVE(Class)

**Comment by treaves** [comment]
> Do you really need to use macro Q_DISABLE_COPY_MOVE(Class)?

I'll looks at the two separate macros tomorrow. But, yes, they need to be used an any subclass of QObject. And to your other comment, the two build failures are not do to issues in my code; you don't use a semicolon at the end of a macro. Is that why you suggest using the two macros?

**Comment by alex-w** [comment]
> I'll looks at the two separate macros tomorrow. But, yes, they need to be used an any subclass of QObject. 

For what? Which reasons for use this macros? 

> And to your other comment, the two build failures are not do to issues in my code; you don't use a semicolon at the end of a macro. Is that why you suggest using the two macros?

Just forget about 2 macros. You use macros, which was introduced in Qt 5.13 and now 2/3 of CI instances and all instances for building binary packages are broken.

**Comment by treaves** [comment]
> > I'll looks at the two separate macros tomorrow. But, yes, they need to be used an any subclass of QObject.
> 
> For what? Which reasons for use this macros?
> 
> > And to your other comment, the two build failures are not do to issues in my code; you don't use a semicolon at the end of a macro. Is that why you suggest using the two macros?
> 
> Just forget about 2 macros. You use macros, which was introduced in Qt 5.13 and now 2/3 of CI instances and all instances for building binary packages are broken.

Ah.  I did not see they were introduced so recently.  They are needed because of [the rule of three/five/zero](https://en.cppreference.com/w/cpp/language/rule_of_three).  I'll replace them for the time being.

**Comment by gzotti** [comment]
You can test for Qt versions and include/define what's possible. At some point we will have to step up to 5.15 and replace QtScript usage, before we can prepare further moving on to Qt6.

**Comment by treaves** [comment]
> You can test for Qt versions and include/define what's possible. At some point we will have to step up to 5.15 and replace QtScript usage, before we can prepare further moving on to Qt6.

Ya, that's what I pushed earlier.

**Comment by treaves** [comment]
> Do you really need to use macro Q_DISABLE_COPY_MOVE(Class)?

Did you see I put this into a guard?

**Review by alex-w — APPROVED** [review]
Well, it works.

**Comment by alex-w** [comment]
All changes extract to oculars-ng branch

**Pull request merged**
