### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bigboos999**
### Description

Fixes # (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
What is it?

**Comment by gzotti** [comment]
Something for boot time debugging for Windows? Looks like a curious test. IMHO certainly not needed.

**Comment by gzotti** [comment]
@bigboos999 we are going to reject and close this on January 31 if you don't explain what this is and why it improves the project in your opinion.

**Comment by bigboos999** [comment]
@bigboos999

**Pull request closed without merging**
