### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rayw000**
Fix typo

### CODE REVIEW

**Review by alex-w — APPROVED** [review]
Thanks!

**Comment by gzotti** [comment]
Oops, thanks!

**Comment by rayw000** [comment]
Thanks @alex-w 

BTW, seems `WITH_QTWEBENGINE` didn't work well for me.

I built with brew installed Qt 5.15.2. Seemed that it's shipped along with `QtWebEngine`. Line 30 evaluated true in my case.
https://github.com/Stellarium/stellarium/blob/dd006bc4095790dba6ceb7fe485284a6804a9fd4/plugins/OnlineQueries/src/CMakeLists.txt#L28-L37

I've read #2006 and #2049. `-DWITH_QTWEBENGINE=0` didn't work for me, neither `-DWITH_QTWEBENGINE=off`. There was a cmake warning saying
```
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_QTWEBENGINE
```
and issue #1982 was still.

Only fully disabling online queries plugin with option `-DUSE_PLUGIN_ONLINEQUERIES=false` worked for me.

I built on Monterey 12.0.1 with Apple M1 Max chip. I'm trying to find out why.

**Comment by alex-w** [comment]
Issue #1982 happened with Qt 5.15 only and probably this is bug in Qt/macOS.

**Comment by rayw000** [comment]
Oh, I thought we could walk around it by `-DWITH_QTWEBENGINE=off` after reading your reply https://github.com/Stellarium/stellarium/pull/2006#issuecomment-957986750.

**Comment by gzotti** [comment]
I have made another round of corrections, seeing that my Odroid C1 SBC with Ubuntu 18LTS has QWebEngine, shows a webengine panel, but fails to work, emitting error messages to stderr. 

Now 
* We detect QWebEngine availablilty at compile time, emit a warning if not found, but compile anyhow.  
* On systems where QWebEngine is present but buggy, compile with it, but manually disable the built-in QWebEngineView and open the URL in the system webbrowser. 

Now finally the external system webbrowser also works on that (minimal, 5fps) platform. 
The User Guide (sources) includes instructions for users.

**Comment by gzotti** [comment]
The point seems to be that at least on ARM platform, QWebEngine does not work properly before Qt6.2, and also not on X11 platforms with some GLX1.3 problem.

**Pull request merged**
