### PR TITLE
Replace DejaVu fonts by Noto fonts

### LINKED ISSUE #2737: Need to change the default korean font on Windows ver. 1.0
Current font is Gulim which is not suitable for HiDPI.
Malgun Gothic is recommended.
+
image

UI get blurred too.

### PR DESCRIPTION
**Pull request by alex-w**
### Description
This pull request replaces DejaVu fonts by Noto fonts for better support HiDPI devices. Plus selector of font families is visible now by default.

Fixes #2737 (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
My main PC is malfunctioning and I likely cannot test in the next days. But as said before (#2737), you must install the font on Windows first, it's not usually possible to just load the TTF font (not sure if the logic implemented here is actually required!). On my system, both fonts exists and work.

**Comment by alex-w** [comment]
Hmm… I tested it in macOS without installing fonts, plus @Dark-Matter-X tested it in Windows - all works as expected. I can test it at work tomorrow (windows 7) also.

**Comment by alex-w** [comment]
OK, probably few strings in the Stellarium User Guide for installing fonts in different operating systems + enable by default selector for font family will be enough here - no need replace DejaVu fonts. @gzotti is it good idea for you?

**Comment by gzotti** [comment]
If `QFontDatabase::addApplicationFont(notoFont);` works, all is OK. But I had seen there is a Noto CJK font available which was not installed on my system and may be required for the OP. My problems are that my main PC is broken, and that I have Noto installed anyway, so I currently cannot test whether this all works. 
Would it be possible to install the font into the system fonts as installation option? (Check if it exists, install if not; leave it installed or remove on uninstall?)

**Review by gzotti — APPROVED** [review]
I found a Win10 PC without Noto fonts installed. OK from my side!

**Review by gzotti — APPROVED** [review]
OK for me

**Pull request merged**
