### PR TITLE
Provide more screen space for some elements

### LINKED ISSUE #1249: astrocalc - graph tab: include name of selected object in title
**Is your feature request related to a problem? Please describe.**
The Graphs tab is not very user friendly. Where some other tabs take the currently selected object for output, the Graph tab forces the user to select an object. Because of this inconsequent behaviour, I am _often_ looking at the wrong graph.

**Describe the solution you'd like**
Include the name of the selected object in the title

_Note_: consider removing the dropbox and use the selected object, to make the UI more consistent and more easy to use. The dropbox is difficult to use because it does not allow to find an object by keyboard, so the user has to use the mouse to scroll down a lot. (this lack of keyboard detection in popup menus is very strange for Qt)

image

compare this with the other tabs:
image
image
image

but there are more places that has this issue:
image

image

### PR DESCRIPTION
**Pull request by axd1967**
### Description

Changed some input width policies so that more space is used if possible.

See https://github.com/Stellarium/stellarium/issues/1249#issuecomment-708598752

Fixes #1249, #1325

### Screenshots (if appropriate):

image

image

image

image

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Ran on 1920x1080

Note that I did not test this on a small screen; I assume that Qt is intelligent enough to present sufficient (but likely reduced) space to low resolution screens.

**1920x1080**

**Test Configuration**:
* Operating system: KUbuntu 0.20.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Please reverse back changes for graphs tab - your proposal is unusable

**Comment by alex-w** [comment]
GUI is ugly now again - please check look and feel in various languages

**Comment by axd1967** [comment]
> Please revert back changes for graphs tab - your proposal is unusable (do you hear about ergonomics?)

There is nothing wrong with this (see third picture in this issue); on the contrary, now it solves two issues: (1) it draws the attention to the specific behaviour of the tab as it has a different behaviour (which is an ergonomy issue because the other tabs require the user to select a body in Stellarium). (2) it declutters the dialog (in fact, this "Graphs since January of this year..." is far too much and belongs in a tooltip).

> GUI is ugly now again - please check look and feel in various languages ugly now again - please check look and feel in various languages

OK. I tried. Here are some results. Note that I don't know if there exist RTL modes, please indicate these if so.

## dutch
image

image

image

image

## japanese (I think)

image

image

image

image

## other?

**@alex-w can you please provide a screenshot where things are ugly?**

Finally, @alex-w can we please be nice? if there is a problem, any problem, **please stay polite**. if I'm not nice, just kindly point me to my rudeness and we will sort it out. I'm trying to make Stellarium better, and this time in an **active** way, I am HELPING here.

**Comment by alex-w** [comment]
> There is nothing wrong with this (see third picture in this issue); on the contrary, now it solves two issues: (1) it draws the attention to the specific behaviour of the tab as it has a different behaviour (which is an ergonomy issue because the other tabs require the user to select a body in Stellarium). (2) it declutters the dialog (in fact, this "Graphs since January of this year..." is far too much and belongs in a tooltip).

Seriously? Please compare new behaviour of this subtab with behaviour and look of other subtabs. You added follow issues: 1) UI is splitted on 2 parts and this is decreased visibility of parts (yes, **I don't see the celestial body anymore**) 2) behaviour of UI in this subtab now has other rules and it increasing difficulties for understanding and reducing predectible of behavior 3) you was maximized distance of movemets between most frequently used parts of UI. 

According to your "issue 1" we should fully remove this tool or please give us definitions which I asked in #1249. Your "issue 2": I see messy, but don't see decluttering of the dialog. Your proposal for tooltip is perfect to make it difficult for understanding of graphs.

> > GUI is ugly now again - please check look and feel in various languages
>
> OK. I tried. Here are some results. Note that I don't know if there exist RTL modes, please indicate these if so.

So, you do not see problems on your screenshots :-/ On your screenshot you may see huge fields for input and for 99,9% users (who use standard settings) those fields will be HUGE. This may be very strange or you can mark me as a bad guy, but... if you use very specific settings and you change the GUI to get a "good look", then please, PLEASE, check your changes for case, where the user will use standard settings. I really don't want to get a case where 1% of users (or less) will get a "good" GUI and 99% will get a "bad" GUI.

**Comment by axd1967** [comment]
> Seriously? Please compare new behaviour of this subtab with behaviour and look of other subtabs. 

It is already different from the other tabs: in the other subtabs, the user must focus the object, in this tab the user must select the object from a dropdown . This is precisely the problem that I want to cure in a benign way: by moving the selection to a place where it is more visible.

> You added follow issues: 
> 1) UI is splitted on 2 parts and this is decreased visibility of parts (yes, I don't see the celestial body anymore) 

It is very well visible at the top!
AFAIK there is no rule that says that input controls in a UI should be **grouped**. The important thing is that the flow/order is correct and logical.

> 2) behaviour of UI in this subtab now has other rules and it increasing difficulties for understanding and reducing predectible of behavior 

This subtab is already different from the other subtabs (because of the object selection mode).

> 3) you was maximized distance of movemets between most frequently used parts of UI.

Agreed. But for a keyboard user this should be no problem, if the tabbing is well defined.

But the problem is that I (and I'm sure others too) have often been bitten by overlooking it , also because in the other subtabs, there is no dropdown; again, the behaviour of this subtab is different. Especially new users will stumble across this, I'm almost 100% sure of this.

So I propose a solution for this issue:

image

> According to your "issue 1" we should fully remove this tool 

Issue "1" does not ask to remove this tool (I assume you mean the object dropdown). Only to relocate it to a more visible place. **But indeed**: _Ideally, the dropdown should be totally removed and replaced by object selection by focus: this way, all subtabs of the astrocalc Graph tool behave the same way._ 

Even more: I see no reason to provide an object selection dropdown for this subtab.

> or please give us definitions which I asked in #1249. 

to recap from https://github.com/Stellarium/stellarium/issues/1249#issuecomment-688275325 what you want to know:

> Please read your Note 

Note says:
> Note: consider removing the dropbox and use the selected object, to make the UI more consistent and more easy to use. The dropbox is difficult to use because it does not allow to find an object by keyboard, so the user has to use the mouse to scroll down a lot. (this lack of keyboard detection in popup menus is very strange for Qt)

> and write the definitions of phase and phase angle for deep-sky objects and stars. Please explain how changes equatorial coordinates and heliocentric distance of DSO or stars by year. Please give us an example of conjunction of Polaris and Mars (for example).

Sorry, but I really still can't understand this question. I have a feeling that this is not relevant here?
Why would someone want a conjunction between Polaris and Mars?

> Your "issue 2": I see messy, but don't see decluttering of the dialog. Your proposal for tooltip is perfect to make it difficult for understanding of graphs.

The title label in this dialog is taking up needless space and can be moved into a tooltip of the dialog:

image

The information in "Graphs since January 1st of the current year" is too much information, because the user can see that information implicitly in the axes themselve:
image
And it can be moved into a tooltip of e.g. `graphsPlot`
https://github.com/Stellarium/stellarium/blob/b8fc89f2eac5bc7f9f4debf45856cd9671e87bfc/src/gui/astroCalcDialog.ui#L1645-L1652


Meanwhile this title is wasting pixel space that can be devoted to drawing.

Note that the solution for #1249 can already be admired in the first tab :

image


> So, you do not see problems on your screenshots :-/ On your screenshot you may see huge fields for input and for 99,9% users (who use standard settings) those fields will be HUGE. 

I don't think users are happy to see part of their input hidden. If the large field is a problem (let's call this an opinion, right?), then please just make sure the information is 100% visible. 

Because these are NOT OK:

image

image

If "too wide fields" are bad, then these are also bad, but already exist:

image

image

**Comment by alex-w** [comment]
> It is already different from the other tabs: in the other subtabs, the user must focus the object, in this tab the user must select the object from a dropdown . This is precisely the problem that I want to cure in a benign way: by moving the selection to a place where it is more visible.

Making a tool worse because you do not understand something is NOT a better way to change the GUI.

> > 1. UI is splitted on 2 parts and this is decreased visibility of parts (yes, I don't see the celestial body anymore)
> 
> It is very well visible at the top!

Maybe for you, but definitely not for me.

> AFAIK there is no rule that says that input controls in a UI should be **grouped**. The important thing is that the flow/order is correct and logical.

Please read rules of any Human Interface Guideline or works for ergonomics.

> Agreed. But for a keyboard user this should be no problem, if the tabbing is well defined.

Seriously? After increasing messing in keystops by your changes...

> But the problem is that I (and I'm sure others too) have often been bitten by overlooking it , also because in the other subtabs, there is no dropdown; again, the behaviour of this subtab is different. Especially new users will stumble across this, I'm almost 100% sure of this.

At the moment this is "problem" for you one in the world.

> > According to your "issue 1" we should fully remove this tool
> 
> Issue "1" does not ask to remove this tool (I assume you mean the object dropdown). Only to relocate it to a more visible place. **But indeed**: _Ideally, the dropdown should be totally removed and replaced by object selection by focus: this way, all subtabs of the astrocalc Graph tool behave the same way._

This is incredible! Probably you are bad at astronomy. Just for experiment we remove the dropdown list and the user chooses the celestial body through mouse selection. In our sample user selected M31 or Regulus, selected graphs are "Phase vs. Time" (or "Phase angle vs. Time") and "Heliocentric distance vs. Time" and he pressed the button "Draw graphs". Now please give to me definitions for "phase of star", "phase of deep-sky object", "phase angle of star", "phase angle of deep-sky object", "heliocentric distance of star", "heliocentric distance of deep-sky object". I hope you can also suggest to me which graphs will seen by the user after selecting star Vega if choosed graphs are "Distance vs. Time" and "Magnitude vs. Time".

This tool was created especially for Solar system objects and only Solar system objects should be used for it!

> Even more: I see no reason to provide an object selection dropdown for this subtab.

If you do not understand the purpose of the tool then this is not a tool problem.

> Sorry, but I really still can't understand this question. I have a feeling that this is not relevant here?
> Why would someone want a conjunction between Polaris and Mars?

Because this is your proposal...

> The information in "Graphs since January 1st of the current year" is too much information, because the user can see that information implicitly in the axes themselve:

This caption of graphs was added especially as explanatory note after question of users.

> Note that the solution for #1249 can already be admired in the first tab :

I see you do not see any difference between various tools in principle :(

> I don't think users are happy to see part of their input hidden. If the large field is a problem (let's call this an opinion, right?), then please just make sure the information is 100% visible.

Some time ago, when you requested adding extra values for font size, we warned you about possible troubles in the GUI. You just ignored the warning and now you say about "issues". 

> Because these are NOT OK:
> 
> image
> 
> image
> 
> If "too wide fields" are bad, then these are also bad, but already exist:
> 
> image
> 
> image

You do not see principal difference again... :( Please explain why should make input fields huge for generic users, who will use standard font size and where 50-75% of those fields will be just empty. Oh, I forgot: in this case we should increase the minimum resolution for Stellarium. 

You settings is very non typical, but you permanently trying set it as default for whole world :-/

**Comment by axd1967** [comment]
> Maybe for you, but definitely not for me.

Maybe you mean that you just don't like it this way? Shall we call this "an opinion" and leave it there?

image



> > AFAIK there is no rule that says that input controls in a UI should be **grouped**. The important thing is that the flow/order is correct and logical.
> 
> Please read rules of any Human Interface Guideline or works for ergonomics.
> 

Sure. Any? Here you go: https://en.wikipedia.org/wiki/User_interface#Principles_of_quality

image

> > Agreed. But for a keyboard user this should be no problem, if the tabbing is well defined.
> 
> Seriously? After increasing messing in keystops by your changes...

What "keystops"? As far as I can see, tab stops are not well defined - at least not in the changes that I propose. Here is the tab order as present in b6ecec3ac38243c184ec16c06056f105af3b2171

image

(And do you call this tab order OK?)
image

is this one OK? Do you call this "good ergonomy"?
image

> 
> > But the problem is that I (and I'm sure others too) have often been bitten by overlooking it , also because in the other subtabs, there is no dropdown; again, the behaviour of this subtab is different. Especially new users will stumble across this, I'm almost 100% sure of this.
> 
> At the moment this is "problem" for you one in the world.

We disagree. But when I find one other user that had this problem, I will no longer be the only one in the world. 
Honestly, why keep fiddling about this? I observe myself and notice, as an experienced Stellarium user, that this irritates me. Let's rest this, but when we find another user that stumbled over this problem, I will re-raise this issue.

> 
> > > According to your "issue 1" we should fully remove this tool
> > 
> > 
> > Issue "1" does not ask to remove this tool (I assume you mean the object dropdown). Only to relocate it to a more visible place. **But indeed**: _Ideally, the dropdown should be totally removed and replaced by object selection by focus: this way, all subtabs of the astrocalc Graph tool behave the same way._
> 
> This is incredible! Probably you are bad at astronomy. Just for experiment we remove the dropdown list and the user chooses the celestial body through mouse selection. In our sample user selected M31 or Regulus, selected graphs are "Phase vs. Time" (or "Phase angle vs. Time") and "Heliocentric distance vs. Time" and he pressed the button "Draw graphs". Now please give to me definitions for "phase of star", "phase of deep-sky object", "phase angle of star", "phase angle of deep-sky object", "heliocentric distance of star", "heliocentric distance of deep-sky object". I hope you can also suggest to me which graphs will seen by the user after selecting star Vega if choosed graphs are "Distance vs. Time" and "Magnitude vs. Time".
> 
> This tool was created especially for Solar system objects and only Solar system objects should be used for it!

## Ah! Finally!

Now I get it, thank you. **The dropdown obliges the user to select a solar system body.** Which is logical, as you indeed write - I see your point. _But is it really necessary to call me bad at astronomy? Do you really think I'm stupid and would like to compute a phase angle of a star, etc? Could it not be that we have language issues? Am i rude because of language issues?_

Well, the solution is simple: if the user selects Polaris, the tool won't run the calculation, it can show "Polaris is not valid for this calculation" and the calculate button can be disabled. (And remember that the user can also select the object by searching, so there is a powerful interface available to select an SSO).

**But far more simple** is to move the SSO selection to the area that is now occupied by this label
image
This solves two issues:
- contrary to other tabs (where - by the way - its name is not always visible!), indicate that this GUI needs a SSO selection

image
image

image
image

- give it a more prominent position (rather than being stuffed in a corner)

So, to recap: the SSO selection in the Graph tool is important, do we agree on that? Because in that case, it should appear **FIRST**. In a prominent way. It determines the output, and I am living proof that it can be overlooked.


> > The information in "Graphs since January 1st of the current year" is too much information, because the user can see that information implicitly in the axes themselve:
> 
> This caption of graphs was added especially as explanatory note after question of users.

How about a tooltip?

image

> > Meanwhile this title is wasting pixel space that can be devoted to drawing.
> 
> Really? Please see your proposal and explains "magic", who will increasing number of pixels for drawing.

- None if the SSO selection moves to the top (but the price is good, as this clarifies the situation)
- A bit if a tooltip is used

> Some time ago, when you requested adding extra values for font size, we warned you about possible troubles in the GUI. You just ignored the warning and now you say about "issues".

I am struggling with low resolution screens. When I resize to 1024x768, I get this:

image

image

Am I right?  Maybe I'm doing the wrong type of resolution simulation? But is there really not enough space? Is it please possible to provide a 1024x768 screenshot that justifies chopping off values of fields that are otherwise "too large"? 

> 
> > Because these are NOT OK:
> > image
> > image
> > If "too wide fields" are bad, then these are also bad, but already exist:
> > image
> > image
> 
> You do not see principal difference again... :( Please explain why should make input fields huge for generic users, who will use standard font size and where 50-75% of those fields will be just empty. Oh, I forgot: in this case we should increase the minimum resolution for Stellarium. 

1. I don't ask for **huge** fields, I ask for **complete** fields. The degree value is important, even if it would be zero. This is a sound ergonomical issue.
2. it doesn't matter if 50-75% of those fields will be just empty. look at this screenshot:

image

Did anyone complain about those large input fields? I don't think so.

Thank you for your understanding.

**Comment by alex-w** [comment]
> > This is incredible! Probably you are bad at astronomy. Just for experiment we remove the dropdown list and the user chooses the celestial body through mouse selection. In our sample user selected M31 or Regulus, selected graphs are "Phase vs. Time" (or "Phase angle vs. Time") and "Heliocentric distance vs. Time" and he pressed the button "Draw graphs". Now please give to me definitions for "phase of star", "phase of deep-sky object", "phase angle of star", "phase angle of deep-sky object", "heliocentric distance of star", "heliocentric distance of deep-sky object". I hope you can also suggest to me which graphs will seen by the user after selecting star Vega if choosed graphs are "Distance vs. Time" and "Magnitude vs. Time".
> > This tool was created especially for Solar system objects and only Solar system objects should be used for it!
> 
> ## Ah! Finally!
> Now I get it, thank you. **The dropdown obliges the user to select a solar system body.** Which is logical, as you indeed write - I see your point. _But is it really necessary to call me bad at astronomy? Do you really think I'm stupid and would like to compute a phase angle of a star, etc? Could it not be that we have language issues? Am i rude because of language issues?_

I don't know you is stupid or not, but you frequently ignore important parts of discussion or "do not see" parts, which you do not like. The behavior and purpose of this tool was obviously for all except you.
 
> Well, the solution is simple: if the user selects Polaris, the tool won't run the calculation, it can show "Polaris is not valid for this calculation" and the calculate button can be disabled. (And remember that the user can also select the object by searching, so there is a powerful interface available to select an SSO).

I hope you will explain to all users, who will say that this tool do not work or has a bug that all of them are wrong. Or you prefer to add another additional text block with notification? Adding non obvious and hidden behavior into GUI, with hard predictable results, is very bad idea. 

Any GUI should be intuitive and simple, but your proposals make it non intuitive and complicated IMHO.

I'll change the GUI for graphs tool to non intuitive version - as you want, but without your very bad solutions (let's minimize ugly)

> How about a tooltip?

First 2 graphs has tooltips and you just IGNORE them. Previously both graphs has had captions, but both captions was deleted - do you remember WHY those captions was deleted?

> I am struggling with low resolution screens. When I resize to 1024x768, I get this:

Alex, sorry, but your screenshots always look like a bad nightmare. I really do not understand what you mean when you talk about good UI. You changed the font size, you changed the scale of the GUI for all programs and you propose it as etalone. Nobody uses these weird settings except you. 

> 1. I don't ask for **huge** fields, I ask for **complete** fields. The degree value is important, even if it would be zero. This is a sound ergonomical issue.

Due to your strange settings you proposed a solution, who increased input fields for some languages up to 500% for users, who use standard settings. Please explain why those users should get giant input fields in the GUI.

> 2. it doesn't matter if 50-75% of those fields will be just empty. look at this screenshot:

Please compute 50-75% of 500% and explain why it doesn't matter.

**Comment by axd1967** [comment]
@alex-w can you please provide screenshots that demonstrate the size problems in specific languages?

**Comment by alex-w** [comment]
> @alex-w can you please provide screenshots that demonstrate the size problems in specific languages?

For example you can see the size problems on your screenshots already: https://user-images.githubusercontent.com/3529789/96101611-ee135780-0ed5-11eb-9dd6-68f140e32a62.png 

In standard GUI the fields has more size.

**Comment by axd1967** [comment]
> For example you can see the size problems on your screenshots already: https://user-images.githubusercontent.com/3529789/96101611-ee135780-0ed5-11eb-9dd6-68f140e32a62.png
> 
> In standard GUI the fields has more size.

Please highlight where the problem is. I don't see any problem. Please show me YOUR screenshot of this GUI.

**Comment by alex-w** [comment]
> Please highlight where the problem is. I don't see any problem. Please show me YOUR screenshot of this GUI.

You frequently "don't see" real problems and see the imagined problems. I've built your branch, set Chinese language (as you, but you mark it as Japanese) and set size of dialog according to your screenshot. My font size and scale factor for GUI are standard.
stellarium-000

**Comment by axd1967** [comment]
I'm stopping this conversation. Thank you for modifying the GUI as much as possible, the remaining issues will become clearer later.

## Recap of the issues mentioned here:

1. the SSO selection in the Graphs subtab is wrongly placed and as such leads to confusion. it should receive a better place, especially because it is crucial to the functioning of the Graph tool and because that subtab behaves differently from other subtabs
1. the title of the Graph subtab ("Graphs since January...") in its current presentation is expensive in terms of pixel use and can be replaced with a tooltip
1. some subtabs show a title, others don't
1. the widths of some input fields (typically angular limits) are too small, resulting in the user having to fiddle to discover the degree part. The argument that is defended is that low resolution screens cannot provide enough space for the full width. The solution is to give priority to a full width input field and sacrifice the label width by using shortened strings, if necessary acronyms, and tooltips. If there really are not enough pixels, then the better approach is to reduce label contents rather than input field widths, because (1) the labels never change and the user knows about them, and (2) can also receive tooltips to explain their use. To give a few examples, `"Show objects brighter than magnitude:"` can easily be shortened to `"Min. mag:"`; `"Maximum allowed separation"` can easily be reduced to `"Max. sep.:"` and it is unlikely that many users will have a problem (especially when good tooltips are added, that's what they are for).
1. the tab order is to be reviewed

also,
1. I asked for 1024x768 screenshots that demonstrate the need for such constrained fields. I would be surprised if many users still use 1024x768, I wonder whether their volume justifies this kind of discussions, and I suspect this is a moot argument, even though Stellarium officially supports this minimal resolution. _But I might be very well mistaken._
1. overly large input fields are _not_ an issue. there are other places in Stellarium where such fields exist, and nobody complains about these.

**Comment by gzotti** [comment]
Re 1: Simply start to learn to use a tool with its idiosyncrasies, not permanently insist to reforge it. Stellarium also has no file menu in the upper left corner. (Don't even try to suggest that!) 
Re 2: Important strings must be visible, and not depend on whether the user points the mouse over them. Some graphics drivers even appear to suppress tooltips. Talk about UI design...
Re 3: see Re 1.
Re 4. @alex-w rightfully pointed out to you that YOU are using too large GUI font size. We had limited this to meaningful limits before. I cannot find the conversation, but I also think YOUR insistence made us make a possible MISTAKE in b060bd6584e82c3f171c97b79a1b349f0c0c115f to allow larger fontsize AT THE RISK OF THE USER (YOU). Most users will see the font is too big now and reduce size again. You blow up font size beyond what's reasonable and prefer to complain. We should better revert this mistake and limit font size to reasonable values so the GUI does not look bad. You cold maybe apply system screen scaling to get larger labels on your screen. 

also 
Re 1. You would really be surprised if you read more of the support channels, where people are trying to use 600x800 devices, or really have oldish 1024x600 devices as field notebooks.  See various hints in the FAQ. Three operating system families on varying age on computers from about 2003-2020 ranging from 1k to 8k screens are indeed a challenge to support.  _You are totally mistaken._
Re 2. Program GUI improvements may appear here and there at different rates. Cosmetics are not so crucial to the functionality of the program. Most of the GUIs have a long history of happy users. You can suggest improvements, but we are free to accept suggestions, or drop them. Keep the rate low, we have enough to do, much of which is more challenging, and much more rewarding.

**Comment by axd1967** [comment]
look.. we are all just trying to improve things.

> Important strings must be visible

That's precisely the topic of this issue... The title of the graph is NOT important (because it never changes, for one, so this bit of information can be transmitted in other ways to the user); we'll disagree on that.

> but I also think YOUR insistence made us make a possible MISTAKE in b060bd6 to allow larger fontsize AT THE RISK OF THE USER (YOU). Most users will see the font is too big now and reduce size again

First, as far as I can see, b060bd6 is an upper limit to an option; users don't _have_ to change this option, and _if_ they have an issue they _can_ revert it, because they _see_ the result of their action and _understand_ that a too high selection gives _them_ issues, while at the same same time satisfying _other_ users that appreciate the increased range.

About the font size: maybe there is a misconfiguration in my build system that generates larger fonts, I don't know for sure.

I would appreciate if you correct your accusation about b060bd6 , because, as you write, you as maintainer are free to accept or reject suggestions. This also means that you carry the responsability for the result and should not put mistakes on users that ask for changes. We all know that we often have to protect users from their mistakes, be it in their actions (think of #1277 ) or in their change requests. In reality there is a mix of responsibility and trust, but there is no need to accuse (blame...) someone who makes a mistake. The alternative is that no-one makes any suggestion or change request, then there will be no mistakes any more. In other words, that's life. 

We all know that you as maintainers are never obliged to execute suggested changes, but that doesn't mean that you should _reject_ them: maybe someone will one day pop up and say "hey, that's no problem at all, the solution is xxxx...". But if you reject issues, you risk to lose valuable inputs that could be solved by future developers.

I closed this issue out of frustration because of the way this discussion is heading but I will reopen this issue for some future developer to deal with it. The branch is available for anyone interested.

_(And no, I won't ever suggest a File menu. I've been programming in various languages on various platforms since 1980 (and that includes a major 10 million lines of code C++ desktop app in the aerospace domain), I think I have some experience by now, including on UI ergonomy.)_

**Pull request closed without merging**
