### PR TITLE
Satellites: Restore shadow circle at arbitrary altitude

### LINKED ISSUE #3100: sat plugin: umbra at "distance" (should be "altitude") does not correspond to selected sat's umbra
### Actual Behaviour

image
image

### Additionally

- wordings 
- [ ] phrasing: "_show umbra at **distance**_"  should be "_show umbra at **altitude**_" (as noted in https://github.com/Stellarium/stellarium/issues/2510#issue-1298098454)
- [ ] phrasing: "show Earth's umbra" should be "show umbra" or "show umbra for selected sat"  (idem penumbra) because there is only one "Earth umbra", but each sat has its umbra (depending on altitude)
- [ ] what is meant by "C.U."? -> make it "CU" or "Centre of Umbra"

### System
* Stellarium version: 23.0.72-bdee5b6 [master]

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

### PR DESCRIPTION
**Pull request by gzotti**
### Description

The functionality to show a shadow limit for a hypothetical satellite in arbitrary altitude above ground was botched and therefore disabled in 23.1. This now aims to fix that.

- also resets cutoff altitude to 80km
- also no commLink info for nonoperational satellites.

As discussed: We had envisioned shadow enlargement like for Lunar eclipses. However, the original evaluation for visibility conditions does not use shadow enlargement. I have removed the according code.

Fixes #3100 (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] Housekeeping

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win11
* Graphics Card: Geforce 3700Ti

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [x] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
> However, the original evaluation for visibility conditions does not use shadow enlargement. Either remove the code, or add it to the original model?

I think the code for shadow enlargement should be at least disabled or removed. In the future we need improve brightness model for satellites in penumbra and we need a real observations to obtain info for accuracy of our umbra/penumbra for sats.

**Review by alex-w — APPROVED** [review]

**Comment by gzotti** [comment]
I see no crash at exit in about 10 runs. Can you be a bit more specific?

**Comment by alex-w** [comment]
> I see no crash at exit in about 10 runs. Can you be a bit more specific?

Steps to reproduce:
1) Run Stellarium
2) Open Satellites settings and enable the umbra
3) Select ISS
4) Quit from Stellarium

```
Downloaded 0 files (0 kbytes) in a session of 49.06 sec (average of 0 kB/s + 0 files from cache (0 kB)).
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.
StelGLWidget destroyed
[Thread 0x7fffd5476640 (LWP 55222) exited]
[Thread 0x7fffdd1ff640 (LWP 55144) exited]
[Thread 0x7fff5a111640 (LWP 55224) exited]
[Thread 0x7fff59910640 (LWP 55228) exited]
[Thread 0x7fffd4c75640 (LWP 55223) exited]
[Thread 0x7fffdc9fe640 (LWP 55145) exited]
[Thread 0x7fffe59fe640 (LWP 55140) exited]

Thread 1 "stellarium" received signal SIGSEGV, Segmentation fault.
0x0000000000000031 in ?? ()

```

**Comment by gzotti** [comment]
Still cannot reproduce it on W11. Stellarium on my WSL currently would use the Intel GPU but segfaults on startup. Due to other tasks I cannot reboot now. Can you run a Debug build and check where it breaks?

**Comment by alex-w** [comment]
> Still cannot reproduce it on W11. Stellarium on my WSL currently would use the Intel GPU but segfaults on startup. Due to other tasks I cannot reboot now. Can you run a Debug build and check where it breaks?

I've shared log from gdb, so, the main problem - I see the segmentation fault, but I see no source. Something strange happened in new getUmbraData method.

**Comment by alex-w** [comment]
Oops... I've checked the master - same steps and same results - a crash O_O

So, your code is not a bad guy

**Review by alex-w — APPROVED** [review]

**Comment by 10110111** [comment]
> ```
> Thread 1 "stellarium" received signal SIGSEGV, Segmentation fault.
> 0x0000000000000031 in ?? ()
> ```

If it's 100% reproducible, try running under Valgrind. It may be able to tell where the bad jump/call target address came from.

**Comment by alex-w** [comment]
> If it's 100% reproducible, try running under Valgrind. It may be able to tell where the bad jump/call target address came from.

Hmm...

master, debug mode, gdb:
```
Downloaded 0 files (0 kbytes) in a session of 34.195 sec (average of 0 kB/s + 0 files from cache (0 kB)).
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.
StelGLWidget destroyed
[Thread 0x7fffdd413640 (LWP 122542) exited]
[Thread 0x7fffddc14640 (LWP 122541) exited]
[Thread 0x7fffdf298640 (LWP 122539) exited]
[Thread 0x7fffdcc12640 (LWP 122543) exited]
[Thread 0x7fff6f0fc640 (LWP 122566) exited]
[Thread 0x7fff700fe640 (LWP 122564) exited]
[Thread 0x7fff708ff640 (LWP 122563) exited]
[Thread 0x7fffdfba5ec0 (LWP 122534) exited]
[Thread 0x7fff6f8fd640 (LWP 122565) exited]
[New process 122534]
[Inferior 1 (process 122534) exited normally]
```
Am I an idiot?

OK, this branch, debug mode, gdb:
```
Downloaded 0 files (0 kbytes) in a session of 47.111 sec (average of 0 kB/s + 0 files from cache (0 kB)).
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.
malloc(): unsorted double linked list corrupted

Thread 1 "stellarium" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140736946921152) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: Нет такого файла или каталога.

```

Next iteration:
```
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.
StelGLWidget destroyed
[Thread 0x7fffddc14640 (LWP 135903) exited]
[Thread 0x7fffdd413640 (LWP 135904) exited]
[Thread 0x7fffdf298640 (LWP 135901) exited]
[Thread 0x7fffdcc12640 (LWP 135905) exited]
[Thread 0x7fff6f8fd640 (LWP 135931) exited]
[Thread 0x7fff700fe640 (LWP 135930) exited]
[Thread 0x7fff708ff640 (LWP 135929) exited]
[Thread 0x7fffdfba5ec0 (LWP 135897) exited]
[Thread 0x7fff6f0fc640 (LWP 135932) exited]
[New process 135897]
[Inferior 1 (process 135897) exited normally]

```

WTF?!?

**Comment by 10110111** [comment]
> malloc(): unsorted double linked list corrupted

Well, this looks like that same intermittent crash that we've already seen and failed to diagnose.

**Comment by alex-w** [comment]
this branch, debug mode, gdb

1) Run Stellarium
2) Change time to 3 hours early (a daylight on the screen)
3) Open settings Satellites plugin 
4) Umbra and fixed altitude enabled
5) Quit

```
Downloaded 0 files (0 kbytes) in a session of 51.29 sec (average of 0 kB/s + 0 files from cache (0 kB)).
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.

Thread 1 "stellarium" received signal SIGSEGV, Segmentation fault.
0x0000555555e035e3 in std::__atomic_base<int>::operator++ (this=0x6c006c00650074) at /usr/include/c++/11/bits/atomic_base.h:385
385           { return __atomic_add_fetch(&_M_i, 1, int(memory_order_seq_cst)); }

```

**Comment by 10110111** [comment]
What's the stack trace?

**Comment by alex-w** [comment]
Next iteration in same steps:

```
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.
StelGLWidget destroyed
[Thread 0x7fffdf298640 (LWP 138397) exited]

Thread 1 "stellarium" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()

```

**Comment by gzotti** [comment]
Ah, now running debug mode build in debug run. Exited, and was pointed to an issue in a file `atomic`. 
image

```
  _NODISCARD _TVal load(const memory_order _Order) const noexcept { // load with given memory order
        const auto _Mem = _Atomic_address_as<int>(_Storage);
        auto _As_bytes  = __iso_volatile_load32(_Mem);
        _Load_barrier(_Order);
        return reinterpret_cast<_TVal&>(_As_bytes);
    }
```

I admit I have seriously no idea where this comes from. But such error in "atomic" was also the error when I gave up on the latest discussion about TelescopeControl.

Is the call display helpful:
image

**Comment by gzotti** [comment]
Maybe this is #3427 after all?

**Pull request merged**
