### PR TITLE
Observing lists fix

### PR DESCRIPTION
**Pull request by Jocelyn1109**
Pull request only for test (draft).
Not ready to merge.

### CODE REVIEW

**Comment by gzotti** [comment]
Please rebase your work from master for the cleanest solution:

git checkout master
git pull --rebase
git checkout <your-branch>
git rebase master

follow instructions, resolve conflicts. Then 

git push --force

**Comment by Jocelyn1109** [comment]
Very strange I have no conflict on local :(
    Le jeudi 4 août 2022 à 13:13:38 UTC+2, Georg Zotti ***@***.***> a écrit :  
 
 


Please rebase your work from master for the cleanest solution:

git checkout master
git pull --rebase
git checkout 
git rebase master

follow instructions, resolve conflicts. Then

git push --force

**Comment by alex-w** [comment]
Probably your fork has old master

**Comment by Jocelyn1109** [comment]
Ok it is possible.I updated the master and rebase. I will see.
    Le jeudi 4 août 2022 à 13:42:22 UTC+2, Alexander V. Wolf ***@***.***> a écrit :  
 
 


Probably your fork has old master

**Pull request closed without merging**
