### PR TITLE
Do computations in linear color space when rendering planets

### PR DESCRIPTION
**Pull request by 10110111**
Please don't squash if you merge! The commits were carefully separated into logically independent changes!

The main goal of this PR is to make the rocky objects without atmosphere (e.g. the Moon, Mercury, Io etc.) look more correct. In particular, the terminator of the Moon looks much sharper in real life than in Stellarium currently: the brightness comes to zero linearly, while Stellarium renders it superlinearly, which unrealistically smoothens the transition.

Doing this naively reveals a few problems with planets that do have atmospheres: gas giants, Venus etc. These can't be rendered with Oren-Nayar model (much less the special case of it, the Lambert model) due to multiple scattering in the atmosphere that does smoothen the terminator. To work around this I added a hack that emulates the smoothing that used to happen when computations were done in nonlinear sRGB color space. The proper fix would be to find a better BRDF (which may vary between planets).

Also I moved the Lambert model computations from the vertex shader to the fragment shader, because the sharper terminator of the rocky planets reveals the blocky nature of the vertex mesh. 

#### The Moon how it used to look

stellarium-011

#### The Moon how it looks now

stellarium-012

#### A photo of real-life moon, developed from RAW with minimal processing

Screenshot_2023-01-19_01-29-51

#### Saturn + Io how they used to look

stellarium-009

#### Saturn + Io how they look now

stellarium-007

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Ubuntu 20.04
* Graphics Card: Intel UHD Graphics 620

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
Isn't that too sharp/dark now? Exif date is 2008-05-11-22-29-31 CET


2008-05-11-22-29-31_Mond_Russentonne_Test-0002

**Comment by gzotti** [comment]
This was 2005-05-12 around 22:20 CEDT (20:20UT) with Vienna's 68cm refractor. 

Moon-2005-05-12-9933x4120

**Comment by 10110111** [comment]
> Isn't that too sharp/dark now?

Not sure what exactly you mean. The general trend is the same in your photo and in this PR (checked on Mare Serenitatis).

The large contrast in this PR comes (at least partially) from too high-contrast texture. I think the authors of it did more than just applying extra gamma as they say: at least the maria are too dark. This I'm planning to work on later, using the linear LROC data as a source.

**Comment by gzotti** [comment]
I hope I can check your PR on weekend. At first glance the new solution appears to have too large dark craters. But it's a mixed effect with the other change you made recently, where crater shadows are now so strong. These stand out now even stronger.

**Comment by 10110111** [comment]
BTW do your photos represent brightness faithfully, or have they been manipulated with some non-linear tone curve? Would be best if you have linear-color raw images.

**Comment by gzotti** [comment]
Processed some 15 years ago... I can provide the CR2 raw images.

**Comment by 10110111** [comment]
If we replace the texture with a more correct one that I made from LROC data (lacking the poles), only white-balanced to make it look gray, this would look as in the screenshot below. It already looks more consistent with the JPEG you posted regarding the contrast of the maria, but the JPEG seems to be manipulated in the brightly-lit part, so to compare more fairly it's better to have the CR2.

Note that in fact, Oren-Nayar model is not a good model to describe the BRDF of the lunar surface. NASA uses Hapke model for this, and the albedo map was also created from LROC photos using this model. So we shouldn't expect perfect match with Oren-Nayar. Instead, this PR is just one more step to improve, with further ones to be done.

moon-with-better-texture

**Comment by Atque** [comment]
With that new texture, the low resolution of the craters is obvious. Maybe a 4k or even 8k crater texture would be needed. Could such be generated?

**Comment by 10110111** [comment]
> the low resolution of the crater shadows

It's not the low resolution, it's them being aliased. I have a patch locally that enables antialiasing for fragment shader output (basically, supersampling), but this comes at a performance cost. The result looks like this:

stellarium-013

**Comment by gzotti** [comment]
Here are 2 CR2s with different exposure from that 2008-05-11 22:29:31 CET (or CEDT, I cannot rule this out, unfortunately)
[CR2.zip](https://github.com/Stellarium/stellarium/files/10466439/CR2.zip)

**Comment by gzotti** [comment]
Here are CR2s from the big refractor.
[2005_05_12_UniStw.zip](https://github.com/Stellarium/stellarium/files/10467310/2005_05_12_UniStw.zip)

**Comment by 10110111** [comment]
So, using a minimally-processed version of your photo, converted to grayscale, and comparing it with Stellarium at this PR + WIP texture + conversion to grayscale + 1.5px Gaussian blur in the GIMP, I get the results below. Switching between them back and forth, I think the photo and this PR version are similar enough, while the photo and before-this-PR version are not as close. The similarity is not ideal, but it's still quite usable IMO. Of course, this is not the result of purely this PR, because the texture is not yet there, but still, this shows that this PR does make sense.

### Photo

2008-05-11-22-29-31_Mond_Russentonne_Test-0002 gray

#### Stellarium after this PR, + WIP texture

stellarium-015gray-blurred

#### Stellarium before this PR, + WIP texture

stellarium-016gray-blurred

**Comment by 10110111** [comment]
For reproducibility: the above screenshots were taken with the time of the photo taken as UTC+1 timestamp, position on the Earth at 26°54'48"N, 71°26'45"E (this position was set to reproduce the orientation).

The texture used instead of current `moon_4k.jpg` is this one:
c-wb-4096+

**Comment by Atque** [comment]
Indeed the new texture + PR looks more realistic. Does it look better for crescents and gibbouses?

**Comment by gzotti** [comment]
OK, I did not object, just wanted to allow better comparison. Yes, when you can add polar zones to your texture, it should be OK.

**Comment by 10110111** [comment]
> Does it look better for crescents and gibbouses?

It should, but this all is limited by the fact that our model is a sphere, rather than a selenoid, so the shadows in the craters on the limb are visible when they shouldn't be due to being behind the crater walls.

> I did not object, just wanted to allow better comparison

OK, so shall I merge this?

**Comment by gzotti** [comment]
Did you complete your texture?

**Comment by 10110111** [comment]
> Did you complete your texture?

No, and it's not a part of this PR. It'll take quite a bit of effort, because the data for the poles need to go from other sources.

**Comment by gzotti** [comment]
Please check whether you can fix some brightness issues which always appear when trying to improve the Moon.

image

Left is this PR, right is V1.2. Atmosphere off. The highlands around Tycho are burned out worse than 1.2 in this PR.

Will the new texture come within days? (At least by, say, late February?) It will likely require yet another round of adaptation. If the answer is yes, I am happy to wait for the fix after the texture. 

Things to check also include mixing with daylight/twilight.

**Comment by 10110111** [comment]
> Please check whether you can fix some brightness issues which always appear when trying to improve the Moon.

I can't reproduce them. See the screenshot:

stellarium-010

> Will the new texture come within days? (At least by, say, late February?)

Days most likely no. Late February is possible I think (though I can't guarantee it, of course).

**Comment by gzotti** [comment]
Zoom out a bit so that lunar diameter ~1/4...1/3 of vertical fov.

**Comment by 10110111** [comment]
Still doesn't seem to reproduce...

stellarium-010

**Comment by 10110111** [comment]
I mean, it does become blown out when FoV is 4.5°, but at this point it doesn't seem to be important, because the details are quite small anyway.

**Comment by gzotti** [comment]
Ah right, try with Lunar scale-up=4.  There are so many settings...

**Comment by 10110111** [comment]
OK, I see it now. Let's wait until I make the new texture, and then fix this if it still remains. With the current partially-done one I don't get this problem.

**Comment by 10110111** [comment]
Actually, I know what's wrong with the current texture and why it has such a wrong high contrast: I've completely missed this part of the description of the CGI Moon Kit:

> The intensity range (0.16, 0.4) was mapped into the full (0, 255) 8-bit range per channel.

This not only changes maximum brightness, but also shifts the minimum value to 0. After fixing this, the current `master` (without this PR) will look like this:

stellarium-010 1

instead of this:

stellarium-010 2

I'm gonna push this fix, after which I'll update this PR to resolve the conflicts.

**Comment by 10110111** [comment]
And for completeness, after fixing the wrong transformation of texture values and applying this PR, we'll get the following:

stellarium-010

**Comment by 10110111** [comment]
Now, this fixed version does display more of the highlight blowing-out problem. I think this should be fixed only after this PR is merged, since it's a concern of an unrelated part of the code (the strange scaling of color by 1.3–1.6, which is certain to blow up highlights).

**Comment by 10110111** [comment]
OK, I've pushed the fix for blown-out highlights, which appeared to be quite simple. I think nothing should interfere with this PR now.

If you merge it, please _do not_ squash!

**Comment by 10110111** [comment]
The result after all the fixes + this PR:

stellarium-011

**Review by gzotti — APPROVED** [review]
Compared esp. with the photo from the big refractor. WOW!

**Pull request merged**
