### PR TITLE
AngleMeasure ~> Align to selected object

### PR DESCRIPTION
**Pull request by uwes-ufo**
### Description
AngleMeasure ~> Align to selected object
You can pan the screen and left-click to select an object as usual, and a right-click will snap the end of the protractor line (closest to the mouse pointer) to the selected object. Double-click with the right mouse button to pick up the end of the line. Another double click with the right mouse button removes the angle measuring line.

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [?] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 11
* Graphics Card: Intel UHD 620

## Checklist:
- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Why you didn't use config option to toggle onto new behaviour?

**Comment by alex-w** [comment]
I don't like the new behaviour - what was idea (or reasons) to change it?

P.S. As an optional feature it may be acceptable, but definitely not as default behaviour.

**Comment by uwes-ufo** [comment]
> I don't like the new behaviour - what was idea (or reasons) to change it?
> 
> P.S. As an optional feature it may be acceptable, but definitely not as default behaviour.

I usually use the left mouse button to pan and select. Unfortunately, angle measurement blocks these basic functions. So I control the angle measurement exclusively with the right mouse button.

You can drag or right-click to move. Or double-click the right mouse button to capture the end of the line. The old method made it possible to move only one of the two line ends with the right mouse button. The new method allows this with both line ends.

Objects can be selected as usual with the left mouse button. When an object is selected, right-clicking snaps the selected end of the line to the selected object. If no object is selected, the end of the line can be placed anywhere in the scene.

**Comment by uwes-ufo** [comment]
> Why you didn't use config option to toggle onto new behaviour?

good idea!

**Review by alex-w — APPROVED** [review]

**Pull request merged**
