### PR TITLE
Add some nebulae images and update M77 image

### PR DESCRIPTION
**Pull request by sunshuwei**
Add some nebulae images and update M77 image

### CODE REVIEW

**Comment by gzotti** [comment]
Nice images. Are these your own? You know, using "images found somewhere" would not be a good move.

**Comment by sunshuwei** [comment]
barnard_loop-1,barnard_loop-2，barnard_loop-3，barnard_loop-4，m77，sh2-264，sh2-308 is the work of me and my girlfriend(Sun Shuwei and Wang Lingyi), for Stellarium means contributing to the public domain. 

ic10,ic405,ic2177,n3603,n4244,n4565,n6334,n6357, they belong to the public domain. 
Ic417, ic1396, N7000, using the Attribution 2.0 Generic (CC BY 2.0) copyright agreement.

-----
Https://creativecommons.org/licenses/by/2.0/


You are free to:


Share - copy and redistribute the material in any medium or format

Adapt - remix, transform, and build upon the material

For any purpose, even commercially.


This license is acceptable for Free Cultural Works.


The licensor cannot revoke these freedoms as long as you follow the license terms.
Under the following terms:

    Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

    No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

Notices:

    You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.
    No warranties are given. The license may not give you all of the permissions necessary for your intended use. For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.

A new version of this license is available. You should use it for new works, and you may want to relicense existing works under it. No works are automatically put under the new license, however.

-----

**Comment by alex-w** [comment]
CC BY 2.0 is not compatible with GPL v2 - sorry, we cannot accept the ic417, ic1396, n7000 into main package.

**Comment by sunshuwei** [comment]
Deleted ic417,ic1396,n7000.

**Comment by alex-w** [comment]
Please fix typos and remove special chars from ESO/La Silla observatory names. Some images need more accurate calibrations also.

P.S. Please fix the path of textures (no need nebulae/default part)

**Comment by sunshuwei** [comment]
Added n7000, ic1396,sh2-155, coma_cluster, fornax_cluster, n1316.
They belong to the public domain.

**Comment by alex-w** [comment]
Please add author and license info into CREDITS.md files (see section 4)

**Comment by alex-w** [comment]
Please fix file names for M77 and SH2-264

**Comment by alex-w** [comment]
Please fix case for imageCredits keyword too

**Comment by sunshuwei** [comment]
Which one?

**Comment by alex-w** [comment]
imageCredits is case sensitive word

**Pull request merged**
