### PR TITLE
Use IAST names in Vedic Indian skyculture.

### PR DESCRIPTION
**Pull request by vvasuki**
Following up from https://github.com/Stellarium/stellarium/pull/3

### CODE REVIEW

**Comment by gzotti** [comment]
This looks very good, thank you!
However, the TRANSLATORS: ... line should give a direct short hint for the following line, not a general remark. This hint is displayed in Transifex to help translators understand some word. Esp. the lines given for the single stars don't help much, currently. For the constellations, you could give a hint about why entries are in (brackets), [square brackets] or {curlies}. (I see the hint in the file header, this can be kept there, but these notes are not visible inside the Transifex system.)

for example, instead of 
````
# TRANSLATORS: Native name of the body in Indian culture, translated to your language. Example: "Hand (Hastaa)" for the Hastā.
N11	"[Pūrva-Phalguni]"	_("Earlier Phalguni (Purva Phalguni)")
````
the comment line could explain what "Phalguni" means. Is this a god, hero, animal?
````
# TRANSLATORS: Vedic Nakshatra; Phalguni was ...
N11	"[Pūrva-Phalguni]"	_("Earlier Phalguni (Purva Phalguni)")
````

To avoid redundant lines, you can shorten the intro comment to "Adhering to the guidelines in the User Guide 0.16.0".

**Comment by vvasuki** [comment]
Thanks for the tips, @gzotti - please check again . I've improved tips for translators. 

Regarding:
> To avoid redundant lines, you can shorten the intro comment to "Adhering to the guidelines in the User Guide 0.16.0".

I find that comments co-located with the code are a big help - so I retained them..

**Comment by t4saha** [comment]
To separately view rashi & nakshatra......
a) Naksatra can be used as Constellations.
b) Rashi can be Used as Asterism. As names resembles with stick figures, so no image required

**Comment by vvasuki** [comment]
@t4saha - Those are fair proposals (which require more discussion since whatever applies to nakShatra-s applies to rAshi-s as well - the ayanAmsha makes things strange for both) - but we should make that a separate pull request. As it is the repo bosses are acting very slowly in acting on pull requests - let's keep things incremental lest we delay progress further.

**Comment by alex-w** [comment]
I'm confusing now - this PR has difference with PR #61. Which PR is "primary" at the moment?

**Comment by vvasuki** [comment]
I think it's best to consider this primary - https://github.com/Stellarium/stellarium/pull/61 is much broader, and I've separately suggested that @t4saha add his iast changes and additions here (or he could make a separate pull request once this is merged).

**Comment by vvasuki** [comment]
Thanks for pointing it out - removed that option. (It must have been from when I had even the naxatra-boundary-related changes in the same PR.)

**Pull request merged**
