### PR TITLE
Martian Poles

### LINKED ISSUE #2040: Simulation of Martian polar ice caps
There is no polar ice caps displayed on Mars 

The program can calculate direction of the axis relative to the Sun, so it can predict seasonal events and changing polar ice on Mars.
As far as I know, the extent of polar ice caps change according to the season. There must be a way to predict the lowest latitude covered by ice (on both poles).

I'm wondering if we can draw something on Mars surface or changing texture of Mars on the fly to simulate the extent of polar ice caps?

Below is an example of what Stellarium should be able to do (I did it by changing the texture of Mars to a new one with simulated ice on it).

mars-ice-cap

### PR DESCRIPTION
**Pull request by gzotti**
This should bring seasonal Martian poles. The shader-based solution seems to be fastest. 

### Description

Fixes #2040  (issue)

- [x] Define variables
- [x] Implement Martian pole latitude function
- [ ] if possible, let pole cap undulate a bit

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows
* Graphics Card: Geforce 960M

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [x] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
Alright, I have seasonally changing caps. Any dated reference images?
I would like to do something to avoid the razor-sharp edges though. Maybe allow some undulating edge? (Take longitude into account, make some wave...)
The latitude (edge) does not strictly follow the figure in the feature request issue yet, it's a simple sine. In reality, Mars' orbit causes some offset. Not sure how relevant this is.

**Comment by Atque** [comment]
@gzotti I did a quick search and found this image, which has a simulated view beside it. This might help validating your solution.

m2018-06-25_01-04-12_jw_rgb

**Comment by gzotti** [comment]
grafik
Quite close IMHO. I need a good series, though.

**Comment by worachate001** [comment]
Recent images - http://www.alpo-astronomy.org/marsblog/
Interesting simulated Mars with polar caps - https://alpo-j.sakura.ne.jp/MS2003/MSmenu.htm
Simulated Mars for upcoming apparition - http://www.alpo-astronomy.org/jbeish/2022_MARS.htm

**Comment by worachate001** [comment]
Wrong sign? Look at Ls = 300, south  polar cap should be smallest, but it's largest. Same for north pole.

**Comment by gzotti** [comment]
> Wrong sign? Look at Ls = 300, south polar cap should be smallest, but it's largest. Same for north pole.
> 
> After fixing the sign, it looks really close to ALPO simulations.

Ouch, sure. Messed up the labelling in that Fig10. I should sleep more...

**Comment by Atque** [comment]
@gzotti I suppose this very method can be used to create the "blue winters on Saturn" effect?

https://earthsky.org/todays-image/saturn-blue-sky-winter-southern-hemisphere-photo/

**Comment by gzotti** [comment]
OK, I have modelled the snow edge with a simple cosine curve with max. extent as given. The asymmetry of snow edge vs. Ls causes a slight error, but visually the effect is not too far from images. With the MarsObserver you can observe the poles grow in seasonal shadow. I have added a slight undulation to the snow edge, which turns into an almost-star when the polar caps have almost vanished in summer. Good or kitschy?

**Comment by gzotti** [comment]
> @gzotti I suppose this very method can be used to create the "blue winters on Saturn" effect?
> 
> https://earthsky.org/todays-image/saturn-blue-sky-winter-southern-hemisphere-photo/

In principle yes. Now get me a model for Ls and the edge for this effect. Or better, work out a PR! :-) We still have real work ahead...

**Review by alex-w — APPROVED** [review]
Thank you very much!

**Pull request merged**
