### PR TITLE
add DSO-names and some Barnard outlines

### PR DESCRIPTION
**Pull request by ultrapre**
1. dso-names: add, because N6334==Sh2-8, but they are not bound in stellarium.
2. outlines for 3 B-DN because of difficult identification, simulated from _A_Photographic_Atlas_of_Selected_Regions_of_the_Milky_Way_.

### CODE REVIEW

**Comment by ultrapre** [comment]
Data need fixed in catalog

Cr146=Tr 7
Cr230=Tr 14
Cr231=Tr 15
Cr233=Tr 16
Cr234=Tr 16
Cr329=Tr 25
Cr372=Tr 32
Cr387=Tr 34
Lack Cr467!

Lack Mel10! Mel10=NGC659=Cr19
Mel29=NGC 1807=Cr 59
Lack Mel31!

**Comment by alex-w** [comment]
> dso-names: add, because N6334==Sh2-8, but they are not bound in stellarium.

Why you think that NGC 6334 and Sh2-8 are same object?

> Error Report : Melotte 10 is lost in catalog, Mel10=NGC659=Cr19 (1915MmRAS..60..175M).

A typo, OK, but what this is in the pull request?

**Comment by ultrapre** [comment]
> but what this is in the pull request?

Well, I think it is a small fix.

As for Sh2-8, WP shows it, and Sh2 sheet from astronomy-mall also bind them.

**Comment by alex-w** [comment]
> Well, I think it is a small fix.

Where I can see this fix in this pull request?

**Comment by ultrapre** [comment]
Okay, I move catalog report to single issue.

**Comment by alex-w** [comment]
Would you re-check the outlines and coordinates for B 138?

**Review by alex-w — APPROVED** [review]

**Comment by ultrapre** [comment]
image
image
B 138 : 19h10m, 0° （B1900）
Easy to see in Barnard's plate but difficult to align in Sloan plate, so I draw as I can.

**Comment by ultrapre** [comment]
It seems that NGC6334 and Sh2-8 are merged, thus nickname append of this commit is unneed.

**Pull request merged**
