### PR TITLE
Scripting graphics tool

### LINKED ISSUE #459: Scripting Engine Graphics Tools
_Original report by Steve T.:_ https://bugs.launchpad.net/stellarium/+bug/1106739

This feature request from old bug tracker.

The scripting is very nice. I am looking at it to suppliment the astronomy course I teach. I would love to make some scripts where I could draw a trail of the path an object takes, like an analema or a planets retrograde motion. It would probably be a call to draw or plot at the current object's location, but not travel with the object. Another way to state it is to be able to draw/plot at a given RA/Dec.

Thanks, Steve T.

### PR DESCRIPTION
**Pull request by alex-w**
### Description
The new feature is proposed for using in scripts to place markers on the sky. It may be helpful for illustration of celestial events, e.g. drawing analemmas and orbits.

Fixes #459

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?
I've tested behaviour of new scriptable methods in Scripting Console on Windows and on Linux.

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
It works at the moment, but I think I can improve later rendering the markers through introducing support SVG markers.

**Comment by gzotti** [comment]
Good idea. Maybe you can add a simple example script? E.g. Mars opposition 2018 in daily or weekly markers? Or even better: "markers for all planets" to show annual trails, with color-per-planet?

**Comment by alex-w** [comment]
I can add analemma and forward/backward movement for Mars scripts (after merge?)

**Comment by gzotti** [comment]
Should be added pre-merge, then it's just one final commit. ("clean linear history" as Fabien likes.)

**Comment by alex-w** [comment]
Sorry, here is 2h25m (local time) and I cannot quickly write a good script for demo a retrograde movement of Mars (with comments).

**Comment by gzotti** [comment]
No problem in a dev branch... ;-)

**Comment by alex-w** [comment]
OK, I think it ready to merge now

**Comment by gzotti** [comment]
Nice! 
The script should start with the sun visible on screen. I ran a few times before I realized I have to "turn around" to see what would happen. Then we can see it's really a good new feature!

**Pull request merged**
