### PR TITLE
New plugin: online queries

### PR DESCRIPTION
**Pull request by gzotti**
### Description

The plugin works, but the queried websites are under development. 

As result of a virtual developer meeting in early 2020, this is the start for a new plugin to access various sites with HTTP APIs to query for additional data about the currently selected object, e.g. extended star name data, astrophysical data (AAVSO, GCVS), or also Wikipedia and Ancient-Skies. 

The idea is to have access to online resources that provide more information than could fit into the InfoString. The plugin therefore provides a separate dialog with text (HTML) output. 

Every site to be accessed may have to be handled by a separate class, with possible extra settings available in the GUI tabs. Only the output textbox is the same.

We still need a better icon. 

Fixes # 355

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 10
* Graphics Card: irrelevant

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by axd1967** [comment]
Very interesting; it might be interesting to add in the branch a first draft in the User Manual, so that casual testers know how to test it?

**Comment by gzotti** [comment]
No, it is not ready for the public.

**Comment by axd1967** [comment]
I know, @gzotti - it's still on a branch...

**Review by alex-w — CHANGES_REQUESTED** [review]
Please remove debug query info from log

**Comment by gzotti** [comment]
Oops, sure :-)

**Review by alex-w — APPROVED** [review]

**Pull request merged**
