### PR TITLE
Add Revised Julian Calendar

### LINKED ISSUE #2028: Revised Julian calendar
According to WP page [Revised Julian calendar](https://en.wikipedia.org/wiki/Revised_Julian_calendar) (see adoption section also)  adding this calendar into Calendars plugin may be helpful. The algorithm of calendal calculations and accuracy info are exist in WP.

### PR DESCRIPTION
**Pull request by gzotti**
This adds the Revised Julian calendar to the Calendars plugin. 

The algorithm given in https://en.wikipedia.org/wiki/Revised_Julian_calendar is unfortunately buggy. 
I think I have solved this now, and the implementation is ready to merge.

### Description

Fixes #2028  (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win10
* Graphics Card: irrelevant

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [x] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Did you read the original work?

**Comment by gzotti** [comment]
> Did you read the original work?

Just the WP article, and compared to the Gregorian algorithm given in CC (and implemented already). The WP article says CC has ignored the RJC, which I checked in CC.  Do you have more?

**Comment by alex-w** [comment]
See https://articles.adsabs.harvard.edu/pdf/1924PA.....32..407S

**Comment by alex-w** [comment]
Since version 5.14 Qt has QMilankovicCalendar class - I think we may look the code here to verify the algorithm

**Comment by gzotti** [comment]
I think I have fixed it now. But the addition of QCalendar in Qt5.14 should allow adding more tests.

**Pull request merged**
