### PR TITLE
small caps typos

### PR DESCRIPTION
**Pull request by axd1967**
### Description

Fixes # (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
Sorry, but NO. The small letters are a code introduced by the last contributor. It is used for the "unformed stars" which are listed with the respective constellation without being part of the figure. Very much on purpose. I close this.

**Comment by axd1967** [comment]
ah, ok. no problem, I'm so sorry. indeed, I now notice that these pop up at the _end_ of the "normal" constellation blocks.

and it is indeed mentioned here:

https://github.com/Stellarium/stellarium/blob/f26f19e48838024b304e9424c10a440fb450f613/skycultures/almagest/description.en.utf8#L55-L56


it's very likely that this will happen again, as these very much looks like typos and there is no indication that this is intentional. 

for example, if we separated these "special blocks" with some blank lines (maybe the parser needs to skip those lines; or can it accept comments?)? (strictly speaking this is going against DRY...)

this could be a cheap way to attract the attention of whoever would want to do the same mistake.

**Comment by gzotti** [comment]
There is so much to do in Skycultures and so little time ... Currently various authors circumvent missing features with various strategies. The two Keepers of the Project will keep fending off unwanted changes... :-) The Almagest SC has one original author team and one contributor whose work recently caused much discussion. It is likely further changes will be brought in when technical preconditions have been established.

**Comment by axd1967** [comment]
I see. here is where the magic happens: :-)

https://github.com/Stellarium/stellarium/blob/b32e61811cfd8038ad68f773d5491466b31cfb70/skycultures/almagest/make_names.py#L110-L111

the `star_names.fab` file is generated by `make_names.py`, that's where this knowledge is available and can be injected.

YES! fab file parsing supports comments:

https://github.com/Stellarium/stellarium/blob/b32e61811cfd8038ad68f773d5491466b31cfb70/src/core/modules/ConstellationMgr.cpp#L797-L800

See https://github.com/Stellarium/stellarium/pull/1761 for a proposal?

**Pull request closed without merging**
