### PR TITLE
Better Milky Way texture

### LINKED ISSUE #475: Visual artifacts on the sky (new Milky Way texture contains halos for brightest stars)
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1408373

Current trunk (rev. 7276) has visual artifacts for bright objects like Moon or Sirius - a faked light spots below horizon when atmosphere is enabled. Those light spots has structure and position similar Moon and Sirius, but with negative value of the height.

Seems this artifacts related to refraction/extinction effects, but it required more investigation.

### PR DESCRIPTION
**Pull request by Atque**
### Description
The Milky Way texture is ugly, since it still contains some bright stars, such as Sirius, Arcturus and Canopus. This PR brings an edited version, with the stars deleted. Care was taken not to delete DSO's. The editing was done in GIMP.

Fixes #475 

### Screenshots (if appropriate):
Screenshot of Sirius and Orion a -10,000. No more ugly leftover of Sirius!
stellarium-013

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?
Simply by changing the texture milkyway.png in the Stellarium/textures folder.

**Test Configuration**:
* Operating system: Windows 10 (irrelevant)
* Graphics Card: AMD Radeon RX 5700 XT (also irrelevant)

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Thanks!

**Comment by gzotti** [comment]
Looks good, thanks!

**Comment by andromedagirlactual** [comment]
this might be a bit of an old post i am responding to, but the milky way texture IS a rather low resolution image, everything else is very highly detailed [at least on my machine] but the MW is seriously low-rez and it would be lovely if it were jazzed up somewhat...
thought i would respond to this old post rather than double up on a request, anyway... thank you.

**Comment by Atque** [comment]
@andromedagirlactual This PR was about fixing artifacts in the current texture (which is quite low res). If you wish a more detailed Milky Way texture, starting a new request might be the best.

**Comment by gzotti** [comment]
@andromedagirlactual some old systems don't like textures greater than 2048 pixels on a side. You can use HiPS Surveys or the DSS layer to have zoomable high-resolution.

**Pull request merged**
