### PR TITLE
Orbit color and selection improvements

### LINKED ISSUE #3849: Orbit mode "Planets plus selected"
**Is your feature request related to a problem? Please describe.**
I would like to show the orbit of one object in relation to the orbits of the major planets. 

**Describe the solution you'd like**
We need an orbit selection option: Orbits of the major planets (color coded) which is not mutually exclusive to "selected object only". 

**Describe alternatives you've considered**
Currently it seems this is just not possible. Show thousands of orbits, or one and only. 

**Additional context**
Would be helpful to show where that selected object's orbit lies. Maybe add "last N selected objects", so that more than one can be shown at a time. The planet orbits give the relevant context, obviously.

### PR DESCRIPTION
**Pull request by gzotti**
### Description

In light of other upcoming changes and a potentially interesting comet, I see need for two improvements: 

- In the orbit color selection, you can so far draw planet orbits in distinct colors, while all other objects are drawn in a single other color. Alternatively, you can draw orbits in color per planet subtype. This branch adds the option to draw planet orbits in distinct colors _and_ those of the minor bodies per planet subtype.

- Currently you can draw either all orbits, only major planet orbits, or only that of the selected object. This was result of a long development of added flags and settings, and TBH already on the brink of maintainability. Now, it was not possible to show e.g. a view from Solar System Observer where you can see the planet orbits combined with the orbit of a single selected comet.  I have added another checkbox for planet orbits. 

This may again not be the best interface when you can select "Major planets" and "Only major planets". etc., and there is a quirk as the default orbit display without selection is "all orbits". When you now select "Major Planets" but deselect "with moons", moon orbits are still seen.  Maybe the whole selection should be re-done, and e.g. allow Major planets plus 1...n last selected objects (like trails). This way you could enable e.g. 5 interesting comet orbits while having thousands loaded. Hmm, or even allow loading from a list of minor bodies, permanently, in a separate GUI list. 

Fixes #3849  (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update
- [ ] Housekeeping

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win11
* Graphics Card: Geforce 3070Ti (irrelevant)

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Atque** [comment]
> and e.g. allow Major planets plus 1...n last selected objects (like trails). This way you could enable e.g. 5 interesting comet orbits while having thousands loaded.

This would be highly appreciated. Also, I think the orbit of the selected object should be visible even when the object is too faint.

**Comment by gzotti** [comment]
Yes, this is a hot topic. I am in favour of allowing to select dim objects' orbits (just like the icon-like rings in the threaded branch, they can easily reach mag 30 and less), but would rather keep orbits beyond orbit_good off. This would avoid a flood of comet orbits sourced from the 1000 comets file, when they are only relevant for 5 years or so. But there will always be wishes for special cases, like "show orbit of P1/Halley for 1910, 1986 and 2063." Sigh, not now please.

**Comment by gzotti** [comment]
@alex-w, @10110111 I could need some feedback. The current solution is what we had plus a not very elegant planet orbit override.  It should be enough for 24.3 IMHO. 

Of course this could be improved, but only in 24.4 or later. We could have a series of checkboxes: Planets [with moons]/Comets/Asteroids/SDO, Centaurs and KBO or whatever division seems usable. And an option "Selection", where a (permanent) selection of favourite objects (extra GUI dialog with list of minor bodies (no planets, no moons)) could be created.

**Review by alex-w — APPROVED** [review]

**Comment by alex-w** [comment]
It's OK for me at the moment

**Comment by gzotti** [comment]
The idea of permanent favourite object selection for orbit drawing is not forgotten. Hopefully in 24.4.

**Pull request merged**
