### PR TITLE
Add fixed equatorial grid/line

### PR DESCRIPTION
**Pull request by gzotti**
### Description

This will bring a new coordinate grid: hour angle/declination.

Required implementing a full new frametype support.  

Fixes # 2368

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 10
* Graphics Card: Nvidia Geforce 960M

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [x] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
I think we should split Markings tab onto 3 subtabs  - a) Grids, b) Lines, and c) Points and features

@gzotti ?

**Comment by gzotti** [comment]
Please not. The tab is admittedly large, but spreading the gridline features on several tabs won't help. Each grid has its equator and poles, there are a few other specialized lines which are strongly linked to the coordinate systems. These belong together!

**Comment by gzotti** [comment]
I think this is ready. @alex-w if you agree I will do the merge.

**Comment by alex-w** [comment]
Do you want add it into version 0.22.1?

**Review by alex-w — APPROVED** [review]

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest

**Pull request merged**
