### PR TITLE
added recent search

### LINKED ISSUE #1050: Remember last entered objects
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to enter and reenter next night some objects with long names. Ex. NGC 6946, NGC 2685, NGC 2403 - it is easy to make a mistake in the name especially deep at night.

**Describe the solution you'd like**
I want that Stellarium remember last 10-20 entered objects in the search field F3.

### PR DESCRIPTION
**Pull request by chithihuynh**
QUESTIONS:
1) How to execute:  src/gui/SearchDialog.cpp (line: 742) [...if(greekText != trimmedText)...]?
2) How to add/show my test cases for regarding my change?

### Description

Order of search objects (using "F3") are now ordered from relevance recently searched then the rest of relevance searches (compare to just ordered by relevence).Recent searches are italicized so user can tell which one are recent and not.

A new search will be added to the recently searched list after the user clicks enter on an object's name within the search dialog. The list will contain the user's last 10 searches is stored in a JSON file under "/user directory/data/recentObjectSearches.json".

Fixes #1050 

### Screenshots (if appropriate):

> Each screenshot contains the Stellarium search dialog and the corresponding /user directory/data/recentObjectSearches.json file. 

---
Search output (no recent searches saved/how it currently is)
recentSearches01
---
After use clicks "enter" on "1P/Halley", then tries to search for "1P/Halley" again.
recentSearches03
---
User has selected "Alkalbain I" (before clicking "enter")
recentSearches04
---
User is searching for "l" and the following results appears.
recentSearches06

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
> I think that counts as a new feature
- [x] Breaking change (fix or feature that would cause existing functionality to change)
>It might also be this one.
- [x] This change requires a documentation update
>Yes, if this is talking about the documentation for the new functions I put in.

### How Has This Been Tested?

All test cases successfully executed locally. 

I tested the new search function by searching for a few different objects and see if the expected results comes up. The expected results should include:

> greekText != trimmedText (QUESTION 1: Haven't been able to get here so I couldn't test it). 
> greekText == trimmedText:
`-` 13 results total
`-` Most recent search first (switch are italicized) (depending on relevance)
`-` Other relevance searches after (similar order to original but might have fewer outputs, depends on how many recent searches matches)
`-` No duplicate results between the recent and other matches

**Test Configuration**:
* Operating system:  Ubuntu 20.04 LTS
* Graphics Card: Manufacturer: NVidia, Model: GeForce 940MX/PCIe/SSE2, driver version: 440.100

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
>  QUESTION 2: I wanted to add some tests but I don't know how to do so.
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Q1: alpha And = α And
Q2: you cannot add unit tests for Search Tool

**Comment by alex-w** [comment]
Please add depth of history as option in "Options" tab and prepare binary package for windows (just use word [publish] in commit message)

**Comment by chithihuynh** [comment]
I added the option to adjust the size of the list. Since Qt's max default size is 99 for spin boxes, that is where I am capping it right now. That can be changed if needed.

- The recent history will contain up to 99 recent objects but the search result will only show what is specified by the max size variable. This way if the user decided to increase the max size again, the data is still there.

-- Update max size


-- Updated search result


------

- Font will change colors if there is a change in the max size value without confirming or rejecting the change. Helps track where the max size is set to.


----

- Also, I was able to execute the code from my first question earlier. It turned out as expected.. for "alpha" only. Most (if not all others) seems to be sorted backwards.

-- Alpha (good)
alpha01
alpha04

-- Beta (bad) This is happening on the master branch too so I don't think I did anything to effect that.
image

**Comment by chithihuynh** [comment]
Hi @alex-w 

I updated the code to include an option for max history size. But one of the tests failed because of a  "redundant line" so I removed it. Then the updated code failed because of the "Travis CI" build errored out. 

I am not sure what I did wrong or need to fix.

**Comment by alex-w** [comment]
@Astrotourist-info in vacation now, but I had some discussion to him by voice. :) He want to see a dropdown list of previously searched objects before and without new search. @gzotti and @chithihuynh maybe just add a new additional tab with table (with few columns, e.g. name of object, him designation, type...) of previously searched objects?

**Comment by gzotti** [comment]
Sorry, not before next weekend.

**Comment by chithihuynh** [comment]
> He want to see a dropdown list of previously searched objects before and without new search.

Sorry for taking so long. After trying a few different configuration for the drop down search, below is a demo of the drop down search. (It's only searching through a limited database). I have to incorporate the change into the real search dialog.
 - FYI: recent searches are now boded & currently selected objects are highlighted

**1) Opened up demo search dialog (with recent already populated)**
searchDropDownMenu01

**2) Searching for "p"**
searchDropDownMenu02

**3) Scroll down**
searchDropDownMenu03

**4) Backspace until search is empty (recent objects will re-populate)**
searchDropDownMenu04

>  maybe just add a new additional tab with table (with few columns, e.g. name of object, _him designation_, type...) of previously searched objects?

I can work on this after I finish the previous one. 
- @alex-w  What is him designation?

**Comment by chithihuynh** [comment]
Here's the update version: 
searchDropDownMenuA_01
searchDropDownMenuA_02

**Comment by alex-w** [comment]
Please enable opening first tab by default also

**Comment by alex-w** [comment]
Please fix crash when user clicked at item of list after search

**Comment by chithihuynh** [comment]
I just left it as the default color but I think I can change it.

**Comment by chithihuynh** [comment]
No problem. Happy to help.

Also, do you want me to update the user guide with the new search feature when it is all approved?

Hovering is not legible with a black font and the way QListView is currently set up in [normalStyle.css (on line 133)](https://github.com/Stellarium/stellarium/blob/508a59feeb9927f45c332478787e50a79100f146/data/gui/normalStyle.css#L134):

```
QListView::item:hover {
	background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(55, 55, 40), stop: 1 rgb(35, 35, 31));
}
```




- Maybe I can change the hover font color to white?

**Comment by alex-w** [comment]
What about use same style for items:
`
QListView::item:hover, QListView::item:selected {
	background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(177, 130, 43), stop: 1 rgb(210, 207, 133));
}
`

**Comment by alex-w** [comment]
Please fix LGTM alerts

**Comment by alex-w** [comment]
Please back visual style :)

**Comment by alex-w** [comment]
Would you add into the Options tab a button for clear history?

**Comment by gzotti** [comment]
Nice feature!
I tried a few targets. Then I tried "Copernicus". At first, the star with exoplanets came up (rho1 Cnc). Then I switched on Planetary Nomenclature in the view settings/SSO tab. Searching for "Copernicus" again found "Copernicus (crater)" and "Copernicus (Krater)" (I am using German program language). However, both entries point to crater Copernicus on Mars. I then zoomed onto the Moon until I had the Copernicus label visible on screen. Searching for Copernicus still brought me only back to Mars. I don't know exactly how the search for planetary nomenclature can mess this up (does it provide only the first entry, and "Mars" is alphabetized before "Moon"? ) Searching for Hevelius was fine, so I assume my observation has to be solved outside this PR.

**Comment by gzotti** [comment]
@chithihuynh Yes, additions to the User Guide with a detailed description are welcome. Before the merge! Please mark it as \newFeature{v0.20.3}

I have meanwhile found a solution for the problem mentioned above. It is indeed outside this PR, no need to bother.

**Comment by chithihuynh** [comment]
@gzotti I think the issue with "Copernicus" for Mars and the Moon is that they both have the same name, "Copernicus (crater)". Which gets removed when we removed duplicates during the matching process.

I kept the remove duplicates because it was there before, should we not remove duplicates?

**Comment by alex-w** [comment]
The issue is fixed in master already.

**Comment by chithihuynh** [comment]
Oh cool. Thanks

**Comment by alex-w** [comment]
Please add description of new feature to the User Guide as final streak of PR

**Comment by chithihuynh** [comment]
Sorry it took me a while for the user guide but I came across a git issue.

I accidentally commit a practice version then restore the "ch_interface.tex" file. So now, all the 
"git blame" lines for that file points to me on the day I restored it.

Is there a way I can fix it? All my work was done on a new branch which has the old blames but when ever I try to put it on this branch, all the blame goes back to me.

**Comment by gzotti** [comment]
I am not a git expert but I think you can totally remove a commit from your private git so a bad commit really vanishes (?)
So you could delete all traces and add your changes again. Of course, nobody else should have checked out your changes!
Google for detailed instructions.

**Comment by chithihuynh** [comment]
Ok, I believe I fixed the problem regarding the user's guide git issue.

In the user's guide, in addition to adding the recent search information:
- I also added subsections for each tab because I wanted to reference the Options tab a few times.
- Added a new image of the Object tab that shows the recent search results should look like.
- Change typos that I noticed.
- QUESTION: What is the "Extend search" button (mentioned in the Options tab)? I haven't been able to find it in the Search window.

**Comment by alex-w** [comment]
> * QUESTION: What is the "Extend search" button (mentioned in the Options tab)? I haven't been able to find it in the Search window.

Where is you find it?

**Comment by chithihuynh** [comment]
I found it in here

https://github.com/Stellarium/stellarium/blob/4083f7e94d6ae6ec9f7258b377008f4d9c14da66/guide/ch_interface.tex#L911

**Comment by gzotti** [comment]
Oops, seems we have updated the GUI but not the Guide. Please edit in the Guide and replace "Extend Search" by "Use SIMBAD".

**Comment by axd1967** [comment]
@chithihuynh this is a very nice feature, thank you.

do you think following would be possible: to delete an item from the recent searches by hitting the Delete button while an item is selected?

So in this case, I use cursor control to descend to "SOYUZ..." and then hit the Delete button to remove that item from the list.

image

**Comment by chithihuynh** [comment]
@axd1967 
Thank you. Sorry about the late reply. I am currently in school so I didn't see this until now.

I think that would be a great feature to add in. If you put in an issue request, I can get to it this summer (sorry I can't get to it sooner).

**Pull request merged**
