### PR TITLE
Fix timezones mess

### LINKED ISSUE #594: Crash when selecting certain dates in 1 AD
### Expected Behaviour
Shows dates of year 1 as normal.

### Actual Behaviour
Crashes once you select a date between 0001-01-01 and 0001-03-25.

### Steps to reproduce
1. Start Stellarium.
2. Select a date in the given interval.
3. Crash!

### System
Windows 10
GTX GeForce 1070
Latest beta (Although I think this happens in the stable 0.18.3 too)

I tried loading the default solarsys file, but it didn't solve the problem.

### LINKED ISSUE #602: Wrong behaviour of Location Dialog
### Expected Behaviour
When user clicked on the list of locations then Stellarium should change the location and set time zone from location (if time zone is not user defined!) without changes the flag "Use custom time zone".

### Actual Behaviour
When user clicked on the list of locations then Stellarium changes the location and set time zone from location via enforcement setting the time zone as "Use custom time zone" (with resetting all user settings!). 

Last version with correct behaviour is 0.18.0.

Tested on Ubuntu Linux since version 0.17.0 to master.

### Logfile 
Not applicable here.

### PR DESCRIPTION
**Pull request by gzotti**
### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?
Fix #602: Overall more logical behaviour of the Location panel. 
- UT-based timezones can be selected and set.
- custom timezone property is preserved
- custom timezone is preserved (if custom is set!)

Fix #594:  It seems that UT-based custom timezones worked, while some named timezones showed that odd behaviour around year 1, exclusively on Windows. A special case now circumvents the issue.

**Test Configuration**:
* Operating system: Windows 10
* Graphics Card: Geforce 960M (irrelevant)

## Checklist:

- [X] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### Additional checklist (TODO):
- [x] Scripting feature (#497) works (needed slight improvement)
- [x] Cleanup code from intermediate comments
- [x] Make sure Time zones while on non-earth locations work properly.

### CODE REVIEW

**Comment by alex-w** [comment]
This pull request **introduces 4 alerts** when merging e8c092ccf996608dbbe034c1c13988b2fa798475 into 541b1dd958452814e78c28ba7dd4b6b4635247a6 - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-1d01aa250ae78c2d3f1b11bb257df6dd66782e3f)

**new alerts:**

* 4 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alex-w** [comment]
This pull request **introduces 4 alerts** when merging 14ef70e914efd3d697eefa7355a2d074943403bc into 541b1dd958452814e78c28ba7dd4b6b4635247a6 - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-2bd9bd0b4eaa9edaf44d80858c2b46c6d7f0e7c6)

**new alerts:**

* 4 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alex-w** [comment]
This pull request **introduces 5 alerts** when merging 3ac9f525d3f9ccdfe9dcd11d0b22bbe43fac7461 into 1a860d826ab6f0d67888738fa70cc086a301d0f0 - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-1ede730d3c75b7321555c03f6818a5b9dafdfef9)

**new alerts:**

* 5 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alex-w** [comment]
This pull request **introduces 5 alerts** when merging 0527026da46527dfd10aa3027f1b4ad458fe325e into 2b1cc8c34d94cdd190311b92425df90c023bebef - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-785e4e2bc13e0aa3de1772c5f845ac562921ad81)

**new alerts:**

* 5 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alex-w** [comment]
This pull request **introduces 5 alerts** when merging 9b1db68ca5fa0ec503b9658be8f949c494f074c5 into 315451fb9237bec4d17d3c236efffd1f8f911842 - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-5817edaa3c3184988ec39a82bb1585d3c4fd8d85)

**new alerts:**

* 5 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by gzotti** [comment]
Still needs work for non-terrestrial locations!

**Comment by alex-w** [comment]
This pull request **introduces 1 alert** when merging d4973adf37996cfb387698f89c4798046b9da7a5 into 64bb5d9e643055d04d4f53caedd6daf21a041dfa - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-d30f2112a5aae2022d08e3906ef498a390055f0b)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alex-w** [comment]
I think it's ready to merge now

**Comment by alex-w** [comment]
This pull request **introduces 1 alert** when merging b65f49b1d8510cae0e6d3dd8d0c0f1866e0659f4 into 613fa09341d2666fc8c869b0dc7c7110e92b506b - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-b0782aff66ea51cbf2e6595c960900de9f8ed622)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by gzotti** [comment]
I have no time right now: Do custom time zones work on extraterrestrial sites? Standing on the Moon, UT times or even regional time zones might be clever (communication, reverse observation, ...).
I can look into that in about 3-4 hours.

**Comment by alex-w** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 30c15d0f76126953e8473680f06ea6ee7eaa6b64 into 4b3f37373675f48c342fc51511bf7e666c513038 - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-582b5505ea2a51a35b23f2df9ff64a28c9ca0c81)

**new alerts:**

* 1 for FIXME comment

**fixed alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alex-w** [comment]
It should be works, but I'll re-check in today later.

**Comment by alex-w** [comment]
This pull request **fixes 1 alert** when merging 6e3a44e5c4ade96e98336b84ea816fe688db41e0 into 6dac1d1032d7bb3c057fb3e7aeafc1c15009128e - [view on LGTM.com](https://lgtm.com/projects/g/Stellarium/stellarium/rev/pr-0a90905aa9d04440de8b141ca24d967108c17950)

**fixed alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
