### PR TITLE
Rewrite Observability Plugin

### PR DESCRIPTION
**Pull request by Thomas1664**
### Description

As suggested in #948 I am working on a complete rewrite of the `Observability` plugin.

This PR includes:
- [x] Remove unnecessary settings
- [x] Use events for setting change
- [x] re-calculate rise/set/transit
- [ ] Increase accuracy for rise/set/transit
- [ ] Calculate sun opposition
- [ ] Add text to info string
- [ ] Unit testing

Open questions:
- How to include unit tests?

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 10 20H2
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
> Since rise/transit/set are already described in the standard info string, do I still need to include them in the plugin?

RTS time in the core of Stellarium has troubles and it needs to improve

**Comment by Thomas1664** [comment]
@gzotti Adding text to the info string via connecting to the `selectedObjectChanged` signal does not work. What did I wrong?

```c++
StelObjectMgr& objMgr = StelApp::getInstance().getStelObjectMgr();
objMgr.getSelectedObject()[0]->addToExtraInfoString(StelObject::Extra, "Hey there</br>");
```

**Comment by gzotti** [comment]
2 little issues: Make sure there is some selection, and spell `<br/>` This works for me:
```
	StelObjectMgr& objMgr = StelApp::getInstance().getStelObjectMgr();
	if (objMgr.getSelectedObject().length()>0)
		objMgr.getSelectedObject()[0]->addToExtraInfoString(StelObject::Extra, "Hey there<br/>");
```

The text will currently be displayed for the selected object after the parallactic angle and before IAU constellation. The exact placement of the extra strings may change as we see need for it.

**Comment by gzotti** [comment]
Seems it does not always work, have problems elsewhere myself ATM...

**Comment by Thomas1664** [comment]
@alex-w @gzotti I don't know how to calculate rise/set of a star. Everything I've got is the following formula:
```c++
double azimuth = std::acos(std::sin(declination * M_PI_180) / std::cos(latitude * M_PI_180));
```
Can you help me calculate the calculate rise/set of a star/planet?

**Comment by alex-w** [comment]
@Thomas1664 do you have "Astronomical algorithms" by J. Meeus or "Explanatory Supplement to the Astronomical Almanac" by Sean E. Urban and P. Kenneth Seidelmann?

**Comment by Thomas1664** [comment]
@alex-w I found the book "Astronomical algorithms" online. It turned out that there already exists an implementation in c++.
An older version of the implementation is available on [github](https://github.com/rstagers/AA-) and the latest version is available [here](http://www.naughter.com/aa.html). Since you told me to not 're-invent the wheel' we could use this library.

**Comment by alex-w** [comment]
No, this library has non-compatible license, so, we cannot use it

**Comment by Thomas1664** [comment]
In that case I write the calculation by myself.
@alex-w What values - according to "Astronomical algorithms" by J. Meeus - that are needed for the calculations does Stellarium provide and where do I get them from?

**Comment by Thomas1664** [comment]
@alex-w @gzotti 
I need the following information for the calculation:
- apparent sidereal time, converted into degrees
- right ascension and declination of the body
- current position of the observer

How to get this information?

**Comment by gzotti** [comment]
StelCore* core = StelApp::getInstance().getCore();
double sTimeDeg = core->getLocalSiderealTime() * M_180_PI;
double ra, dec;
StelUtils::rectToSphe(&ra, &dec, getEquinoxEquatorialPos(core));
const StelObserver* obs=core->getCurrentObserver();

**Comment by Thomas1664** [comment]
@gzotti @alex-w How to get right ascension and declination for the previous and next day?

**Comment by Thomas1664** [comment]
> @gzotti @alex-w How to get right ascension and declination for the previous and next day?

@gzotti @alex-w I really appreciate your help so far. I really want to continue rewriting the plugin but therefore I need to know where to get right ascension and declination for the previous and next day from.

**Comment by gzotti** [comment]
Sorry, I guess both thought the other would answer...

Simply set the previous/next JD in the StelCore and re-read the object's coordinates.

**Comment by Thomas1664** [comment]
@gzotti Using `core->setJD(defaultJD + 1);` to get right ascension and declination results in values that are almost 1 degree off compared to the values in the paper. What did I do wrong?

**Comment by gzotti** [comment]
If I remember correctly, you compute RA/DEC for 0h UT on today-1, today and today+1, and then do the interpolation steps as described by Meeus. You must take into account observer's location coordinates, timezone shifts etc. 

After the computations, you must reset core to the current JD which you have hopefully retrieved in the beginning: 

```
const double jdStore=core->getJD(); 
double jdTodayMidnight=...
core->setJD(jdTodayMidnight;
... retrieve RA/DecMidnight
core->setJD(jdTodayMidnight-1);
... retrieve RA/DecPreviousMidnight
core->setJD(jdTodayMidnight+1);
... retrieve RA/DecNextMidnight
...compute rise/transit/set ...
core->setJD(jdStore);
```


You can find functions in StelUtils to dissect and convert JD to common dates and back (first find whether it is before or past noon in UT, etc.)

**Comment by alex-w** [comment]
> If I remember correctly, you compute RA/DEC for 0h UT on today-1, today and today+1, and then do the interpolation steps as described by Meeus. You must take into account observer's location coordinates, timezone shifts etc.
> 
> After the computations, you must reset core to the current JD which you have hopefully retrieved in the beginning:
> 
> ```
> const double jdStore=core->getJD(); 
> double jdTodayMidnight=...
> core->setJD(jdTodayMidnight;
> ... retrieve RA/DecMidnight
> core->setJD(jdTodayMidnight-1);
> ... retrieve RA/DecPreviousMidnight
> core->setJD(jdTodayMidnight+1);
> ... retrieve RA/DecNextMidnight
> ...compute rise/transit/set ...
> core->setJD(jdStore);
> ```
> 
> You can find functions in StelUtils to dissect and convert JD to common dates and back (first find whether it is before or past noon in UT, etc.)

Probably to avoid cashing the data you will need also call update() method, e.g.:
```
core->setJD(jdTodayMidnight-1);
core->update(0);
```

**Comment by Thomas1664** [comment]
> If I remember correctly, you compute RA/DEC for 0h UT on today-1, today and today+1, and then do the interpolation steps as described by Meeus. You must take into account observer's location coordinates, timezone shifts etc.
> 
> After the computations, you must reset core to the current JD which you have hopefully retrieved in the beginning:
> 
> ```
> const double jdStore=core->getJD(); 
> double jdTodayMidnight=...
> core->setJD(jdTodayMidnight;
> ... retrieve RA/DecMidnight
> core->setJD(jdTodayMidnight-1);
> ... retrieve RA/DecPreviousMidnight
> core->setJD(jdTodayMidnight+1);
> ... retrieve RA/DecNextMidnight
> ...compute rise/transit/set ...
> core->setJD(jdStore);
> ```

@gzotti I'm not sure if I understand you correctly. For the computations I need RA/DEC for 0h UT. I can get those values by converting JD to `int` which corresponds to 0h UT, right?
Then I add/subtract 1 for the previous/next day. Am I correct?

**Comment by Thomas1664** [comment]
@gzotti  Actually, the paper says that RA/DEC should be computed at 0h Dynamical Time, not Universal Time.
Does that mean I just need to convert JD to `int`?

**Comment by gzotti** [comment]
No, there is no connection to converting anything to an int. There is an offset between UT and DT called DeltaT. If computation has to be done in DT, you have to apply the correction to the result. UT=DT-core.getDeltaT().

**Comment by Thomas1664** [comment]
> No, there is no connection to converting anything to an int. There is an offset between UT and DT called DeltaT. If computation has to be done in DT, you have to apply the correction to the result. UT=DT-core.getDeltaT().

So 0h DT = UT+core.getDeltaT, right?

**Pull request closed without merging**
