### PR TITLE
Ignore .cmake directory in top level of project

### PR DESCRIPTION
**Pull request by rayw000**
### Description

Ignore `.cmake` directory in top level of project

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
How you get .cmake directory?

**Comment by rayw000** [comment]
I cannot reproduce it stably, but it does occur for many times from a clean cloned repo. Seems it appears after a special cmake build action. I'm not at my laptop now. I'd like to give more details later.

**Comment by gzotti** [comment]
You should build the program outside the source directory.

**Comment by rayw000** [comment]
@gzotti @alex-w 
Yes, I built this project under project root.
This morning `.cmake` directory appeared again when I switched from my plugin development branch to master and rebuilt this project. But when I deleted it and tried to reproduce, I lost it again.
I'm not quite familiar with `cmake`. I've read the document of cmake here https://cmake.org/cmake/help/git-stage/manual/cmake-file-api.7.html#cmake-file-api-7 , the directory tree it talks about is exactly what I got, but it doesn't mention how to produce it but only what it is.

**Comment by gzotti** [comment]
You may want to follow build instructions in BUILDING.md

**Comment by rayw000** [comment]
Thank you @gzotti , I'll check it out🙂

**Pull request closed without merging**
