### PR TITLE
fixed bug "Lichpin" to "Linchpin".

### PR DESCRIPTION
**Pull request by sunshuwei**
1Modify Translation Error "Lichpin" to "Linchpin".

2. "Coiled Thong"this is a tool of punishment used to bind and tortured the prisoners.
3 constellations 063, 092, 150, 166, 170, 264，are lost.Now it's not sure which stars they are.
5. The ancient Chinese chariots were all with two wheels. Look at this.
thanks
20070920_f56eb41252db8a303cc2vkee3m8wlyon
20071202_f1049eab5d476ccca2f99bj1qgezzivy
timg
u 4294032407 2232136927 fm 27 gp 0

### CODE REVIEW

**Comment by cardinot** [comment]
Hi @sunshuwei,
many thanks for your contribution.

Could you truncate all those commits, describing the change in the commit message, please?

**Comment by gzotti** [comment]
Excellent, thanks.

**Comment by gzotti** [comment]
@sunshuwei and @cardinot I don't know if this is now already merged or why this is closed? 

I hope my last dubious or unclear entries:
* White Patches Attached and White Patches Nearby. What is that?
* The Opener of Heat: unclear, is this a door for a stove, or a tool to dig in fire? Something else?
* East The Great General --> The Great Eastern General?
* The Great Estern Premier, The Second Estern Premier, The Second Estern General --> "Eastern"

**Comment by cardinot** [comment]
@gzotti The branch was not merged yet. I also don't know why @sunshuwei closed it?

In any case, I reinforce that these commits should be fixed before merging (i.e., truncate all changes in a single commit and rebase it to make the history linear, without all those merge commits)... @sunshuwei please, let me know if you need a hand in this sense ;)

**Comment by sunshuwei** [comment]
This is my operation and understanding error.Is there any way I can reopen this pull requests? Or do you want to start a new one?

White Patches Attached and White Patches Nearby. What is that?

    There is a view that  White Patchesis the LMC and SMC。

    The Opener of Heat: unclear, is this a door for a stove, or a tool to dig in fire? Something else?
Chinese开阳， this is a door for the Human world，阳Yang, from Yin and Yang
https://en.wikipedia.org/wiki/Yin_and_yang
Yang, from Yin and Yang, is a concept in Chinese philosophy. Yang means heat, the  human world, the sun.  The opposite side is Yin, which means cold, the infernal, the moon.
Although I do not think it is appropriate, it is an official translation, which is in fact widely used. 

    East The Great General --> The Great Eastern General?
    The Great Estern Premier, The Second Estern Premier, The Second Estern General --> "Eastern"
Yes ，This is a spelling mistake, and I'll modify it.

**Comment by sunshuwei** [comment]
The Twenty-Eight Mansions(28 Lunar Mansions) is the ancient China divides the ecliptic and the sky area near the equator to divide into 28 regions according to the right ascension.Each region is called a Mansion (Chinese:宿,pinyin:xiù)，the Ancients let the Moon change a Mansion every day to rest.
 Each mansion has a Xingguan of the same name near the ecliptic., which is the main Xingguan.Where the constellation in this area belongs to the Mansion.
The star used to measure the Right ascension standard is called the Determinative Star (Chinese:距星,pinyin:jùxīng) of the Mansions.The difference between the Determinative Star of the Mansion and the Determinative Star of the next Mansion on the Right ascension is the equatorial lodge degrees (Chinese:宿度,pinyin:xiùdù) of the Mansion.The traditional equatorial coordinate system of China divides the equator into 365.25 degrees, and the Sun runs one day for one degree.


On the ancient Chinese star map, a line is drawn from the location of the determinative star. Can I add it with the constellation boundaries?
It is not a real constellation boundary. But as a Chinese star map, there seems to be no better way to express it.
image 2

**Comment by gzotti** [comment]
@sunshuwei Thank you! The explanation about the lunar mansions and the 365.25 degrees, and the images, would be very welcome in the description.en.utf8 file!
I think you can try to write a constellations_boundaries.dat file. See the format in data/constellations_boundaries.dat (this is used if a skyculture has no own file): a boundary consists of 1 or more lines starting with the number of corners, then so many pairs of RA and Declination (J2000), then "2 const1 const2" to name the adjacent constellations. In your case this would be lines with 2 coordinate pairs only, running straight in ecliptic coordinates. You may have to add the Lunar Mansions as 1-star constellations to make it work, though.

**Comment by gzotti** [comment]
@sunshuwei 
* There are stars "Gate of Yang I&II" and "Opener of Heat" (with 2 "Added" stars). With your latest explanations, I assume they should belong together under just one name? I think "Gate of Yang" sounds better.
* "White Patches" or "White Patched"? Or should it be 2x singular forms like "White Patch Attached" and "White Patch Nearby"? I also see there is W.P.Attached and W.P.Nearby, whereas there are stars "White Patched(-s?) Nearby 1&2", and "White Patches Added I&II".  Maybe they should also be revised?

**Comment by sunshuwei** [comment]
1.
No, they're not one name. So they have to be translated differently.
The Chinese character of "Gate of Yang" is "阳门（Yang Men）".
The Chinese character of "Opener of Heat"is"开阳(Kai Yang)".

2.
You're right。
White Patches---White Patches Attached，It's missing a word.
Why one is "White Patches" and the other is "Patched",I also think path is better.

Perhaps we could not consider Wikipedia and the Hong Kong Space Museum?

qq 20171212085544
qq 20171212085639
qq 20171212083923

**Comment by cardinot** [comment]
@sunshuwei Excellent. Huge thanks for that!
Could you run these commands in your master branch, please?
```
git checkout master
git reset --hard 60b49bb10d9f5c37059e2daf92d4463307014ef1
git pull https://github.com/Stellarium/stellarium.git master
git push origin master
```
It should be enough to fix the master branch of your fork now.
For future contributions, please have a look at:
https://github.com/Stellarium/stellarium/wiki/Git-Contributor-Workflow

**Pull request merged**
