### PR TITLE
Refactor: getAngularSize->getAngularRadius

### PR DESCRIPTION
**Pull request by gzotti**
It occurred to me that we need to rename this method to clarify that these values are in fact radii, not sizes
See the documentation in StelObject.h

### Description

Fixes # (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### TODOs
- [x] Rename method
- [x] add default implementation to StelObject base class
- [x] clarify CustomObject's weird size
- [x] clarify Nebula's intermediate result. Better return majorAxisSize/2? Adapt other code accordingly.
- [x] clarify why MeteorShowers, Quasars, Pulsars, Exoplanet systems, Novae, Supernovae have non-zero but some distinct fixed small radii? Proposal: remove method override to inherit StelObject's zero size.
- [x] clarify for the Satellite class what RCS is (document the variables!!!) and how to derive radius, not diameter (as it is maybe now), from that. Adapt other places in the satellites code accordingly!

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win10 (irrelevant)
* Graphics Card: irrelevant

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
@alex-w several classes have small arbitrary but distinctly non-zero sizes. The size for stars is zero. Why not also for these classes? A non-zero value implies we could enlarge it to see more than a dot.
The Nebula and Satellite I think do not follow the specification and return diameters, not radii. This should be fixed finally in this branch.

**Comment by gzotti** [comment]
@alex-w I have added 2 TODO annotations in the StelObject::getInfoMap(): I don't understand the test for negative values. (Just add an assert if in doubt?) And why do we need size in radians?

**Comment by alex-w** [comment]
> @alex-w I have added 2 TODO annotations in the StelObject::getInfoMap(): I don't understand the test for negative values. (Just add an assert if in doubt?) And why do we need size in radians?

I don't remember details, probably this part was added into map to backward compatibility. I think we may delete this data.

**Comment by alex-w** [comment]
> @alex-w several classes have small arbitrary but distinctly non-zero sizes. The size for stars is zero. Why not also for these classes? A non-zero value implies we could enlarge it to see more than a dot.

I've refactor this stuff. The most of these non-zero values was added a long time ago (around series 0.11-0.12) and probably on some step of refactoring we just forgot the fix this points.

**Comment by gzotti** [comment]
I think I caught all cases now.

**Review by alex-w — APPROVED** [review]
Thanks!

**Pull request merged**
