### PR TITLE
Simplify gridline intersect callbacks 

### LINKED ISSUE #3688: Wrongly display of Right Ascension 12h in Equatorial System (RA-dec)
### Expected Behaviour

Display 0h and 12h circle properly

### Actual Behaviour

image
image
image

### Steps to reproduce

Not know exactly how to reproduce that. I just opened it, chose the Moon, press ctrl+M and E.

### System
* Stellarium version: 23.3.0
* Operating system: Windows 10 19045.3930
* Graphics Card: AMD Vega 8 Graphics in Ryzen 5 3500U; Driver version 26.20.11030.22001
* Screen type (if applicable): Resolution 2160*1440, scaling 150%, full screen mode

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/14745720/log.txt)

### PR DESCRIPTION
**Pull request by gzotti**
### Description

Issue #3688 describes a tiny problem in the gridline manager's  labeling of equatorial coordinates.
I tried to fix and saw quite a bit of elaborate code was not even required. Or was it?

During development of this branch I will try to remove that possible bloat code also for the other grids.

Fixes #3688 (issue)

### Screenshots (if appropriate):
see #3688 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] Housekeeping

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win10, Win11
* Graphics Card: Geforce cards (irrelevant)

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 10110111** [comment]
What is `lon` supposed to mean? The longitude of the observer on the planet? Why should it affect the label?

**Comment by gzotti** [comment]
lon/lat (longitude/latitude) seem to be the interface points of screen intersection (?) in general spherical names. I have not gone further today, but at least in the equatorial grid they seem not to be required. Or I am missing something important.

**Comment by alex-w** [comment]
OK, all tests from my side are passed

**Comment by gzotti** [comment]
Brr, and I just discovered errors. Switch to decimal degrees! Not sure what's happening.

**Comment by alex-w** [comment]
> Brr, and I just discovered errors. Switch to decimal degrees! Not sure what's happening.

Oops... hour angle should be always in hours - this bug exists in the current release too

**Comment by gzotti** [comment]
Not necessarily. It's really user's choice. See SHA for navigators.

**Comment by alex-w** [comment]
Coordinates in infobox and in grids should be consistent

**Comment by gzotti** [comment]
please test with all grids and settings (decimal numbers etc.)

**Comment by alex-w** [comment]
Hour angles should be measured in hours by definition, not in degrees

**Review by alex-w — APPROVED** [review]

**Comment by gzotti** [comment]
Do you mean decimal hours? I am not aware of any use for that. Navigators and maybe others (surveyors?) may prefer decimal degrees for hour angles. This branch/fix should however only change the previous behaviour of a spurious 0 for 12h/180°. Given the simplifications, I hope I did not break other grids now. (I guess a lot of bloat was to mitigate the original problem)

**Pull request merged**
