### PR TITLE
remember last script directory - fixes #1500

### LINKED ISSUE #1500: script load button should remember its last folder location.
**Is your feature request related to a problem? Please describe.**
Loading scripts from file button, doesnt recall its last location. 
Every time I want to load a script that I keep in appData/roaming/Stellarium/scripts folder is a pain, because the app doesnt remember its last know folder location and goes back to searching in the programs/stellarium/scripts location 
(this is windoze, 0.2.4 is my current release )

**Describe the solution you'd like**
When I click on the load script button it remembers where (folder/directory) it last loaded a script.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by axd1967**
### Description

Fixes #1500

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system:
* Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-74-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Good solution! Impossible saving files - no problems.

**Comment by axd1967** [comment]
(I'll reviews this based on findings in #1753)

**Comment by axd1967** [comment]
@alex-w could you pls list the steps that lead to your observation?

**Comment by axd1967** [comment]
@alex-w  please explain your issue. I can perfectly save scripts.

**Comment by axd1967** [comment]
this can also work together with the "Load scripts from the User directory by default".

**Pull request closed without merging**
