### PR TITLE
Add new landscape of Mars based on the latest HD panorama taken by Zhurong

### PR DESCRIPTION
**Pull request by rayw000**
China National Space Administration released a high resolution panorama of Utopia Planitia of Mars today. This PR provides a new landscape based on this panorama.

### Description
Add a landscape of Utopia Planitia of Mars based on the latest HD panorama taken by the Mars rover of CNSA.

### Screenshots (if appropriate):
image

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?
1. Update to the latest code
2. Introduce the new files
3. Rebuild the whole project
4. Enable the newly added landscape, and watch the display, the performance and the text
5. Switch to languages which this landscape isn't currently translated into, watch if default English text displays well.

**Test Configuration**:
* Operating system: macOS Big Sur 11.4
* Graphics Card: Intel Iris Plus Graphics with VRAM 1536 MB

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — CHANGES_REQUESTED** [review]
Thanks for new landscape!

Please add the English description of landscape into `description.en.utf8` file and details about license for artwork and landscape.

**Comment by gzotti** [comment]
All new landscapes, if they don't involve/highlight new developments in code, please should go to the downloadable landscape section of stellarium.org. 
Else the new landscape is of course very welcome.

**Comment by rayw000** [comment]
@alex-w Thank you! `description.en.utf8` file added. The license of this panorama is not described clearly on the website of CNSA. I've sent an email to ask if we could use it legally.
@gzotti Thanks for your advice! I've read the section about contributing landscapes to stellarium. I have no server to host a download file, does it mean that I should pack my landscape as a zip file and send it to you via email?

**Comment by gzotti** [comment]
Please see the guidelines in https://stellarium.org/landscapes.html. Indeed, a usage license is crucial!

I think @alex-w would be the designated recipient.

**Comment by rayw000** [comment]
Hi @alex-w 

I've got the permission from CNSA and have forwarded their email to you. Could we continue processing this PR?

**Comment by alex-w** [comment]
@rayw000 I'll prepare downloadable package for this landscape from this PR and put it on the https://stellarium.org/landscapes-interplanetary.html page.

**Review by alex-w — APPROVED** [review]

**Comment by alex-w** [comment]
Done: https://stellarium.org/landscapes-interplanetary.html

**Pull request closed without merging**
