### PR TITLE
Refactoring AstroCalc/Positions tool

### PR DESCRIPTION
**Pull request by alex-w**
### Description
I've added computation the heliocentric ecliptic positions of major planets into AstroCalc/Positions tool as secondary tab. In additional to list was added graphical representation of Solar system view through QCharts. The main purpose to adding new feature is didactic.

### Screenshots (if appropriate):
stellarium-001

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
A fresh look of the tool :)

stellarium-002

**Comment by alex-w** [comment]
OK, I think the tool is ready to merge (by the fact this is a startup point for moving from QCustomPlot to QCharts)

**Comment by gzotti** [comment]
Great to move to QCharts. But halt: If these are ecliptical coordinates, the solar system view is traditionally shown from the North side, where the ecl. longitudes are counted counterclockwise. Then the current view is reversed. 
The other point is the circular scale. Is it possible to use circles with radii in full AU? It may be useful to use a log scale here, so circles with 1, 2, 3, 4, 5, 10, (15?), 20, (25?), 30 AU shown. (Reminds me of Titius-Bode...)

**Comment by alex-w** [comment]
> If these are ecliptical coordinates, the solar system view is traditionally shown from the North side, where the ecl. longitudes are counted counterclockwise. Then the current view is reversed. 

I'll check it

> The other point is the circular scale. Is it possible to use circles with radii in full AU? It may be useful to use a log scale here, so circles with 1, 2, 3, 4, 5, 10, (15?), 20, (25?), 30 AU shown. (Reminds me of Titius-Bode...)

I tried use logarithmic scale, but I don't like how it look in QCharts. Let me check it again tonight...

**Comment by alex-w** [comment]
In polar chart axis cannot be reversed - https://doc.qt.io/qt-5/qabstractaxis.html#reverse-prop

**Comment by alex-w** [comment]
Logarithmic axis is enabled:
stellarium-003

Specifics of view:
- No "Sun" - zero distance is not possible on logarithmic axis (or Mercury will be inside "the Sun" when last is on linear axis)
- Mercury will always have a "wrong position" due scaling effect

**Comment by gzotti** [comment]
> In polar chart axis cannot be reversed - https://doc.qt.io/qt-5/qabstractaxis.html#reverse-prop

Ouch, stupid. https://www.qtcentre.org/threads/70730-Anticlockwise-QPolarChart
Something to ask for future improvements. Currently we have a view from below the ecliptic plane.

**Comment by alex-w** [comment]
I did not committed it yet, but... major + dwarf planets:
stellarium-004

Is it good for here?

**Comment by alex-w** [comment]
I've removed dwarf planets - let me stay the classic view of classic task :) Plus I added note to the graph. @gzotti please review the changes.

**Comment by gzotti** [comment]
I found an interesting improvement for deficiencies in the log axis: In line 1635, use
`seriesPlanets->append(dl, log(distance));
`
and below:
```
	QCategoryAxis *radialAxis = new QCategoryAxis();
	radialAxis->append("0.5", log(.5));  // a few stop marks for AU values
	radialAxis->append("1", log(1));
	radialAxis->append("2", log(2));
	radialAxis->append("5", log(5));
	radialAxis->append("10", log(10));
	radialAxis->append("20", log(20));
	radialAxis->append("30", log(30));
	radialAxis->setLabelsPosition(QCategoryAxis::AxisLabelsPositionCenter);

	radialAxis->setGridLineColor(axisColor);
	radialAxis->setLabelsColor(labelColor);
	radialAxis->setLineVisible(false);
	radialAxis->setRange(-1.5, log(32));
	chart->addAxis(radialAxis, QPolarChart::PolarOrientationRadial);
```

For reasons which I don't understand, the label for 0.5 is above, all other labels are below their respective target, and 1 is missing. Else this is the best version I can get for now.

Another trivial improvement could be:
`angularAxis->setLabelFormat("%d&deg;");`

**Comment by gzotti** [comment]
Wording:
- Heliocentric ecliptic positions of the major planets
- Due to technical limitations the graph shows the Solar system from below the ecliptic plane.


Hey, wait! Maybe by inverting the ecliptical longitudes in the seriesPlanets, and using a CategoryAxis also for the longitudes, we can invert this!

**Comment by alex-w** [comment]
Hmm... please add the patches.

**Comment by gzotti** [comment]
Yes!

	`		seriesPlanets->append(360.-dl, log(distance));`

and

```
	QCategoryAxis *angularAxis = new QCategoryAxis();
	angularAxis->setTickCount(13); // First and last ticks are co-located on 0/360 angle (30 degrees per tick).
	angularAxis->append("330", 30);
	angularAxis->append("300", 60);
	angularAxis->append("270", 90);
	angularAxis->append("240", 120);
	angularAxis->append("210", 150);
	angularAxis->append("180", 180);
	angularAxis->append("150", 210);
	angularAxis->append("120", 240);
	angularAxis->append("90", 270);
	angularAxis->append("60", 300);
	angularAxis->append("30", 330);
	angularAxis->append("0", 360);
	angularAxis->setLabelsPosition(QCategoryAxis::AxisLabelsPositionOnValue);
	angularAxis->setGridLineColor(axisColor);
	angularAxis->setLabelsColor(labelColor);
	angularAxis->setRange(0, 360);
	chart->addAxis(angularAxis, QPolarChart::PolarOrientationAngular);

```

**Comment by gzotti** [comment]
> OK, I'll add your patches and removes the note

DONE!

**Comment by alex-w** [comment]
OK, fixed

**Comment by gzotti** [comment]
Argh, thanks for the fixes, i just saw CI failed because of setting the stylesheet for the delete label.  :-/

**Comment by alex-w** [comment]
@gzotti maybe put the Sun back?

**Comment by alex-w** [comment]
Done!

**Pull request merged**
