### PR TITLE
TUI fixes

### PR DESCRIPTION
**Pull request by gzotti**
### Description

After my surprise about #3481 I decided to push this branch a few days earlier than anticipated.

This is not a complete fix/rethinking of the TUI plugin, just a few updates.
Keyboard action toggles for
- show time
- show object info

Still missing is any type of config GUI, at least with those two flag toggles.

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] Housekeeping

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win11
* Graphics Card: Geforce, but irrelevant 

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
Problem: I need a Windows install package with TUI tomorrow evening. What was the incantation?

**Comment by gzotti** [comment]
Problem 2: The Regular expressions to remove the HTML decoration in StelObject::postProcessInfoString() is still not good, and it shows in the result. What to update, and where else does it appear (will something else break instead?)

**Comment by 10110111** [comment]
> Problem: I need a Windows install package with TUI tomorrow evening. What was the incantation?

`[publish]` in commit message.

**Comment by 10110111** [comment]
> The Regular expressions to remove the HTML decoration in StelObject::postProcessInfoString() is still not good, and it shows in the result.

What shows in the result? What is the input?

**Comment by gzotti** [comment]
If you run this, 
configure hotkey to toggle object info, then  just select e.g. Jupiter and see the green insert. 
Go into planetarium settings (F2/Tools) and activate gravity labels and disc viewport to see what I need to deliver.

A date should be visible to the visitors. That works. But the object info shows HTML extras. (`<table style='...'>`)

Ah -- you also need to activate F2/Extras/Use formatting.

**Comment by 10110111** [comment]
Well, the only tag I see slipping through is `<table style='...'>`, which isn't handled by any of the regexes. The one relevant to tables, `tableRe2`, doesn't match the `style` attribute.

**Comment by 10110111** [comment]
The table with a style can be removed with the following change:
```diff
diff --git a/src/core/StelObject.cpp b/src/core/StelObject.cpp
index a1008d44e8..6fb81e9cc3 100644
--- a/src/core/StelObject.cpp
+++ b/src/core/StelObject.cpp
@@ -961,6 +961,8 @@ void StelObject::postProcessInfoString(QString& str, const InfoStringGroup& flag
     static const QRegularExpression brRe2("<br(\\s*/)?>\\s*");
     static const QRegularExpression tdRe("<td(\\w*)?>");
     static const QRegularExpression tableRe2("<table(\\w*)?>");
+    static const QRegularExpression tableRe3("<table style='[^']*'>");
+    static const QRegularExpression tableRe4("<table style=\"[^\"]*\">");
     str.replace(tableRe, "<table");
     // chomp trailing line breaks
     str.replace(brRe, "");
@@ -977,6 +979,8 @@ void StelObject::postProcessInfoString(QString& str, const InfoStringGroup& flag
         str.replace("<td>", "");
         str.replace("</tr>", "\n");
         str.replace(tableRe2, "");
+        str.replace(tableRe3, "");
+        str.replace(tableRe4, "");
         str.replace("</table>", "");
     }
     else if(!(flags&NoFont))
```

**Comment by gzotti** [comment]
> Well, the only tag I see slipping through is `<table style='...'>`, which isn't handled by any of the regexes. The one relevant to tables, `tableRe2`, doesn't match the `style` attribute.

Yes, same conclusion here.  The "\\w" is "word characters", right? Maybe spaces and quote signs should be added.  I tried `"<table(['\\\"\\w\\s]*)?>"`,  that was not enough.

**Comment by 10110111** [comment]
> I tried "<table(['\\\"\\w\\s]*)?>", that was not enough.

Right, because the style also contains dots, semicolons etc. It's just easier to handle it as "an opening quote, anything that's not a closing quote, a closing quote", for two variants of the quotes. You can put it into a single regex by using alternation.

**Comment by gzotti** [comment]
Yes, that works great! Thanks a lot!

**Comment by gzotti** [comment]
Another one: 
`str.replace("<td>", "");`

 Is this not covered by tdRe? And probably also here any style element like align should be removed.

**Comment by 10110111** [comment]
> Is this not covered by tdRe?

Yes, it is. But again, what valid HTML tag does this regex represent aside from `<td>`?

**Comment by gzotti** [comment]
`<td>` may also include style. See StelObject::getSolarLunarInfoString(). I will check other occurrences and deal with them the same way.

**Comment by gzotti** [comment]
Ah yes, this could also match `<tdfoo>`. Not really good, but in effect it is only used in the HTML we are creating.

**Comment by 10110111** [comment]
> Ah yes, this could also match `<tdfoo>`.

Well, this is the only kind of thing that this regex could match. There's a space missing between the words and the tag name. If you do use explicit style-matching regexes as you do in the new PR, this regex is just useless.

**Comment by gzotti** [comment]
I replaced the indeed useless `\\w` now with `\\s` to catch simple cases of just added space. Currently it looks good.

**Comment by 10110111** [comment]
Now it makes sense. But the `(\s*)?` is redundant and is equivalent (unless you really want to capture) to `\s*`.

**Comment by gzotti** [comment]
Right, it's only one element.

**Pull request merged**
