### PR TITLE
Allow dimming of DSO hints and labels

### PR DESCRIPTION
**Pull request by gzotti**
### Description

When using proportional hints or DSO vector outlines, or also when just using many DSO, they appear too bright on screen.
This branch allows to reduce displayed brightness of hints (icons) and labels using two new spinboxes next to the DSO hint/label sliders. 

 Also, given that I simply want more modern UX where settings can be adjusted individually, 
I allow immediate-storing of more DSO-related fine-tune view settings.
(These are still behind the power user tweak flag, config.ini:gui/immediate_save_details.)

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update
- [ ] Housekeeping

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win10
* Graphics Card: Geforce, but irrelevant. 

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [x] I have updated the respective chapter in the Stellarium User Guide 
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
(Linux) 2K resolution:
stellarium-005
stellarium-006

(Linux) 4K resolution:
stellarium-007
stellarium-008

**Review by alex-w — CHANGES_REQUESTED** [review]
The changes is OK for me, but please check the conversion of variable types (float <-> double) - maybe using type double will be OK for all of them.

**Comment by gzotti** [comment]
Compare globular cluster diameters (infostring) with AngleMeasure result, and switch on DSS. In master the symbol is massively too large. It's less clear with galaxies, and debatable for some diffuse nebulae. These here are with current adjusted scaling on a non-HiDPI screen. 
image

image
image

**Comment by alex-w** [comment]
@gzotti please fix compilation for msvc2017

`C:\stellarium\src\core\modules\Nebula.cpp(1191): error C2679: binary '>>': no operator found which takes a right-hand operand of type 'Nebula::NebulaType' (or there is no acceptable conversion) [c:\stellarium\build-5.12-msvc2017_64\src\stelMain.vcxproj]
`

**Comment by gzotti** [comment]
Ah, this kludge was for MSVC2017, sorry.

**Review by alex-w — APPROVED** [review]

**Pull request merged**
