### PR TITLE
Display hourly proper motion of solar system objects

### LINKED ISSUE #949: Comet display of RA and DEC rates
**Is your feature request related to a problem? Please describe.**
Request for additional information to be displayed for object on main screen when selected; comets (and asteroids).

**Describe the solution you'd like**
When imaging a comet, PHD2 guiding uses a dRA and dDEC rates (arcsec/hour).  It would be very helpful for Stellarium to display these values on the main window when a comet is selected. 

**Describe alternatives you've considered**
Cartes du Ciel and Sky Safari 6 Pro provide this information.  However, I prefer Stellarium as I use it extensively for imaging session planning.

**Additional context**

### PR DESCRIPTION
**Pull request by gzotti**
### Description

This adds hourly proper motion display to planets, minor planets and comets. We give the difference from one hour ago to the current position. 
Both versions, length and position angle, and the d&alpha;/d&delta; components are provided.
Computation requires two full position updates of the Solar System.

For this, I have defined a new InfoString type flag. AFAIK only stars and (now) SSO can display proper motion. 

Fixes #949

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 10
* Graphics Card: Geforce 960M (irrelevant)

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (SUG: note TBD!)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Please use `qc_("towards", "into the direction of")` for solar system bodies too.

**Comment by gzotti** [comment]
Ah, sure, there it was!

**Comment by nandikshorbagul** [comment]
hello the stellarium team

**Comment by nandikshorbagul** [comment]
i can say to @xalioth

**Comment by nandikshorbagul** [comment]
the landscape of stellarium web is old i want a new with clouds

**Comment by nandikshorbagul** [comment]
@stellarium new landscape

**Pull request merged**
