### PR TITLE
Icons redraw/redesign

### LINKED ISSUE #752: Change buttons to make UI more intuitive
When someone has time to do UI work (if you agree it could be improved), in the script edit window the 'Clear' button, the 'File Open' button, the SSC button, and even the stop script button all look like they are disabled. The File Save button looks enabled, and useful, but it is a little hard to tell what the others are because of the greyness used in the colors. If they used the same blues as the File Save button, the problem would be eliminated.

This may apply to other windows as well, but I haven't played with them as much.

### LINKED ISSUE #793: Toolbar icons consistency
Problem
----------

Hi, a minor thing that bothers me is that some icons are not consistent in style with the others. I really like the icons and I think that the shapes are consistent, but there are some buttons with subtle differences on color and shadow

icons

In the image you can see that the AstroCalc icon when disabled is slightly brighter that the others, also when selected it does not have a glow. Icons on the oculars bar are not bright enough when selected, specially the sensor one (the rectangle). Finally on the bottom bar some icons do not glow when selected.

Questions
-----------

I wanted to fix it myself. I was going to adjust the brightness and add blut to some icons manually using GIMP, but I wanted to ask first if there is some vector graphics or high resolution available. Do you think it would be OK to redraw the icons on Inkscape and then generate the PNGs?

### PR DESCRIPTION
**Pull request by martinber**
# Description

Here I'm redrawing every icon because some of them are not consistent with the others as mentioned on #793

I'm redrawing the icons on Inkscape to export them as PNG later, useful if you plan on doing HiDPI versions later.

Also I fixed that the close icon on the AstroCalc window needs a margin.

Fixes #793, can help solving #763

### Notes:

- I'm not going to redraw unused icons
- I'm using less glow than the previous icons because otherwise sometimes the glow extends past the limits of the icon
- Added a `icons.svg` file on `Stellarium/data/gui` with vector versions off every icon
- Added a `icons.svg` file on each plugin folder
- Changed considerably the design of some icons:
  - AstroCalc sidebar icon
  - btDssoff and btDSSon, the camera icon now is a Hubble-like image
  - btToastSurvey-off/on now says DSS and has a shape of a TOAST projection tesselation
  - btSurveys-off/on now says HiPS and has a shape of a HEALPix projection tesselation
  - Equation of time plugin icon now is an analemma instead of a equation of time plot
  - Exoplanets plugin icon now is an exoplanet transiting a star instead of some random circles
  - Redesigned all icons from Oculars plugin
  - Pulsar and Quasars icons had just the text "PSR" and "QSR". I tried to draw a pulsar and a quasar, please check them because I'm not sure if I got right the concepts of them
  - Satellite plugin icon is a little different
  - Observability plugin icon now shows the path of a star on the sky
  - PointerCoordinates plugin icon
  - CompassMarks plugin icon
  - Scenery3d icons
  - ArchaeoLines icons
  - Help and info window tab icons
  - Surveys window tab icon
  - The Eclipses tab icon for the AstroCalc window (currently unused)
- Created some icons
  - Created an icon for the "Sky" tab on the view configuration window, previously this tab used the same icon as the "SSO" tab
  - Binoculars icon for the Oculars plugin (currently unused)
  - Transit tab icon for the AstroCalc window

### TODO:

- [X] Create `/stellarium/data/gui/icons.svg`
  - [X] Document inside the `.svg` how to modify and export the icons to PNG
- [X] Redraw left sidebar icons
- [x] Redraw bottom bar icons
- [x] Redraw icons for tabs on windows
- [X] Redraw plugin icons
- [ ] Squash commits when I finish working

### Left for another PR:

- Remove unused icons
- Rename icon filenames to match better their purpose
- Redraw misc icons to fix #752
- Change selection color of window tab icons, right now they look light blue
- Make the oculars plugin bar smaller
- Change backgrounds to make unselected icons more visible during the day
- Fix some margins on the GUI

### Screenshots:

Sidebar comparison:
Toolbar comparison

Old icons on top and new ones below
Resolution comparison

Bottom bar. I'm not showing some icons that were mostly unchanged:
Bottom bar icons

Oculars:
Oculars comparison

Window tab icons:
Window tab icons

Mockup of how currently unused "Transit" and "Eclipses" icons would look on the AstroCalc window
Mockup of AstroCalc

This PR also fixes that the close icon on the AstroCalc window needs a margin
AstroCalc close icon bug

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?
I just run the program with the new icons, doing screenshots to see diferences between old and new icons. I also check the contrast of the icons on daylight and nighttime if appropiate.

**Test Configuration**:
* Operating system: Debian GNU/Linux
* Graphics Card: AMD Radeon R7 360. Driver: radeon

## Checklist:
- [X] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
Vector versions are a very good idea. A "bit" more glow may look nicer, though. Is that just some global setting in the Inkscape files? (Did not look into these files yet.)

**Comment by martinber** [comment]
There I added more glow. I'm creating the glow using the "Drop Shadow" tool on Inkscape which has some adjustable parameters. I want to find easily reproducible steps so new icons have consistent glows.

For now I'm documenting the steps inside the .svg as text, I'm going to paste it here so you get the idea:

> Glow:
> - Group all elements of the icon and copy to "glows" layer
> - Filters -> Shadows and Glows -> Drop shadow
>   - Glow radius: 0.5px
>   - Offset: 0
>   - Shadow type: Shadow only
>   - Color: #C3C3C3
> - Select each blur individually
> - Check if bounding box looks big enough to hold the blur without cutting
> - Check if bounding box is small enough to fit on the boundaries of the icon
> - To adjust the bounding box: Filters -> Filter Editor
>   - Filter General Settings (on bottom)
>   - Adjust coordinates and dimensions manually for each icon
> - Now you have one "glow" object, we are using three of these superposed
> to get a stronger effect, so we need two more
>   - Select the object and press Ctrl-D two times to create two additional copies

I don't want more glow because it doesn't fit on large icons (check the top of the "on-sky" icon on the close-up screenshot above). To fix that I should make the icons smaller or find a way to create more glow on the center and less glow on the edges.

**Comment by martinber** [comment]
Hello, sorry for the delay. I've finished almost every icon from the bottom bar and icons for most plugins. Take a look of them on the main post above. The icons left to do are the ones located on the windows tabs.

In the meantime I wanted to ask some questions:
- Right now, there are three icons/functions that are confusing. Do you have any recommendations about how to redesign these icons?
  - Deep sky objects background images (toggles images for most important nebulas/galaxies)
  - Digitized Sky Survey (TOAST) (shows some sky survey)
  - Toggle Hierarchical Progressive Survays (HiPS) (you can choose between surveys)
- I represented the "Pulsar" icon as a star with beams on his poles. And the "Quasar" one as a small galaxy with two beams too. Is this astronomically correct?

**Comment by gzotti** [comment]
The deep sky object backgrounds looks like a camera with flash which is admittedly confusing. But how would you symbolize "astrophoto"? Any "telescope with camera" icon likely looks just like a telescope, and a typical CCD camera looks like a box with fan, not very interesting. Maybe a "foggy patch with stars inside" (or "cluster associated with nebulosity" in NGC terms) would be better? It could look somewhat like a mid-19th century DSO drawing (Lord Rosse etc.?)

DSS is probably hard to describe other than "DSS". I am not aware of a symbol that represents this better. Given that we have no other TOAST-encoded survey, we should probably use DSS to describe it, and mention TOAST in the technical description only. Or there should be easy to follow guidelines how to create another TOAST...

The HiPS globe symbolizes both the total sky coverage and the hierarchical sectioning into smaller parts. Not bad IMHO.

**Comment by gzotti** [comment]
For the Scenery3D, I can provide a higher-res raster image (if nor even an EPS?) from my archives. Likewise, the ArchaeoLines was a quick 5minute job. It should symbolize a Stonehenge trilithon with the sun inside. Not sure how to beautify this?

**Comment by martinber** [comment]
I didn't know that the Scenery3D icons were made by you, thank you but I don't think I need the higher res icons as I'm copying the wrench and the eye from previous designs.

I'm not sure what the circles represent, so I tried to represent [3D gizmos](http://docs.pixologic.com/wp-content/uploads/2017/06/4R8_39.jpg) or something like that. Also I've added a pedestrian to the enable icon:

Screenshot at 2019-12-25 18-23-29

Regarding the stonehenge icon I will try to make a [curved design](https://www.google.com/search?tbm=isch&q=stonehenge icon) later.

I don't know what you think, I'm changing the design of some icons without asking for permission first. You can see the list of which icons changed considerably on the first comment of this PR, also I regularly change the images there so you can see them. So if you prefer some of the older icons I have no problem making the new ones more similar.

**Comment by gzotti** [comment]
3D gizmo: quite radical change, I must sleep over that. The plugin is the final result of a research project (https://astrosim.univie.ac.at/) which introduced this generally accessible tool for Virtual Archaeoastronomy, from which the "Kreisgrabenanlage" icon was taken. 
ArchaeoLines: The new trilithon is not bad, although I would prefer a star (or even round "sun") to be symmetrical to (in line with) the gap. Maybe enlarge that gap and place the sun back inside the upper part?  Else, a totally different thing could be taken, e.g. the Giza Pyramids, or (ruins of) a Greek temple? It is funny that you changed the "Observability" plugin icon to look almost like the ArchaeoLines content (diurnal arcs). Maybe "Observability" should be changed again (something with calendars/clocks?), and ArchaeoLines should get these arcs over a temple?

**Comment by martinber** [comment]
Thank you for your insights, that research project looks impressive, I can see that a lot of work went into that. So I tried changing the design of the icons you mentioned.

- Scenery3d: Replaced the 3D gizmo with the neolithic circular enclosures. Left the pedestrian to symbolize that you can walk around
- Archaeolines: I want to keep Stonehenge as it is the first thing I imagine when talking about astronomically oriented monuments. I did put negative sun rays coming from the trilithon. I think that with more work I can make it a little better.
- Regarding Obervability you are right, so now it has some kind of sun/star rising above the horizon. Otherwise maybe I should just return to the telescope and the OK symbol

I wanted to ask about the window tab icons. Do you want me to do "disabled" and "active" versions? Right now we are using one icon for both (e.g. "tabicon-landscape.png") that changes color when enabled. The astrocalc window also has "active" icon variations but they are unused (e.g. "tabicon-AstroCalc-Graphs-enabled.png"

**Comment by gzotti** [comment]
Scenery3D: Thanks, that's better. The pedestrian is indeed a good idea!
ArchaeoLines: Not sure if everybody can see that. What about a slightly wider gap where on the top (just under the lintel) a tiny star shines through? (like the original version, just a bit prettier)
Observability: I think it's OK. 

"Active" tab icons: I see the active tab icon is colored light blue. @alex-w, @xalioth  was that the originally intended design, and should we change that?

**Comment by xalioth** [comment]
Hi,

Congrats for the icons refresh, it looks really nice!!

I can't remember the original reason behind the light blue color, but @martinber seems to be a very talented graphist (unlike me), so I can only approve everything he decides :)

**Comment by martinber** [comment]
Thank you very much!

- I've been looking around and I see that Johan Meuris is who actually knows about icon design as [he made the previous icons](https://johanmeuris.eu/en/portfolio_page/stellarium-interface-icons/). So I think we should at least ping him before merging this PR?

- I finished redrawing the window tab icons, I only made a "disabled" version. I've been looking at the code and I understand that right now selected tab icons are getting a light blue tint because of Qt's default behavior ([[1]](https://stackoverflow.com/questions/5044449/how-to-change-qt-qlistview-icon-selection-highlight) [[2]](https://forum.qt.io/topic/96989/how-to-remove-decoration-tinting-of-selected-items-in-item-views/7) [[3]](https://forum.qt.io/topic/96235/how-to-preserve-qtreeview-item-s-icon-color/5)). I would change that later on another PR

- I think I've finished everything I wanted to do originally, check on top the window tab icons and how I changed the ArchaeoLines icons again too.

If you agree, I will rebase master and squash everything into 3-5 commits with more descriptive names

**Comment by ericschdt** [comment]
Thank you very much for new the icons, I like them a lot!

However, the left ("old") one of the land scape looks more like a tree with hills to me, while the ("new") one on the right reminds me more of lamps. There are no purely circular trees, unless you cut them as such. :) 
old_new

**Comment by gzotti** [comment]
Yes, ArchaeoLines is now fine!

Contacting Johan is a good idea. @xalioth or @alex-w do you have contact?

**Comment by alex-w** [comment]
Icon for eclipse and icon for transits for AstroCalc tool are needed, but at the moment new version for both icons are not exists.

**Comment by alex-w** [comment]
In addition: I guess in near future we will need one new icon for Oculars plugin for finderscopes/binoculars.

**Comment by martinber** [comment]
Hello again,

The landscape icon now is similar to the previous one, see on the top post image.

I've been also working on missing tab icons, here you can see them (ignore the icon labels, I pasted the icons here so you can see them on a window):

Untitled3

- Regarding the "Eclipse icon", I would prefer the one above the "Markings" text, instead of the old version shown above the "Starlore" text

- Regarding the "Transit icon", I think that it is going to be confusing. [Is the difference between an eclipse and a transit relevant](https://www.reddit.com/r/space/comments/2v0hwv/the_difference_between_a_transit_eclipse_and/)? Anyways, I made an icon of a transit, see it above the "Landscape" label

- Right now, the "Sky" and "SSO" tabs have the same icon. I tried to make a new "Sky" icon, but I'm not really happy with it. What do you think?

Finally, I made an icon for binoculars/finderscopes. So now these are the icons on the oculars plugin:

Screenshot at 2020-01-05 16-22-48

**Comment by gzotti** [comment]
Re eclipse vs. transit: I do think it is relevant. Eclipses are "big" events, while transits are rather for advanced users. The icon above "Markings" is better, I agree.

**Comment by alex-w** [comment]
Regarding to “Transits icon” - the transit term are using in 2 meanings: for “small eclipses” and for culminations. Transits tab in AstroCalc tool cirrently had table with time of the high culmunations for selected object in some time range and we use icon with galaxy over trees for it at the moment.

**Comment by gzotti** [comment]
Oh, I thought it was for a future application of finding Mercury/Venus transits. Indeed, for "transit through the meridian" I propose a central vertical line with a star crossing.

**Comment by martinber** [comment]
I modified the GUI files to use the new "Sky" window tab icon. See here how it looks now:
Window tab icons

I updated the "Transit" icon to represent the culmination of a star over the meridian. This "Transit" icon and the "Eclipse" were unused. I pasted them over a screenshot so you can see how they will roughly look:
AstroCalc mockup

Later, after rebasing on top of master I realized that you added the "Transits" tab so I updated the icon on the GUI files too, but I don't have images.

**Comment by alex-w** [comment]
I see we have now same icon for Date and Time dialog and for tab for configure of the date and time. It may introducing some misunderstandings.

**Comment by alex-w** [comment]
Maybe some standard icons like “save file” or “open file” should be created too?

**Comment by martinber** [comment]
> I see we have now same icon for Date and Time dialog and for tab for configure of the date and time. It may introducing some misunderstandings.

Sorry, I thought that there was no problem as they were on different places. There I updated the image on top

> Maybe some standard icons like “save file” or “open file” should be created too?

I was thinking to leave those for another PR. I think that we need to reconsider the colors on the GUI first. Here you can see every icon I could find inside of GUI buttons:
 
GUI buttons with icons

Right now:

- Enabled buttons have a light background with dark text/icons
- Disabled buttons have the same background but with white text/icons
- Clicked buttons have a darker background

I would change the background of disabled buttons to make them darker, and I don't know what to do with their text/icons. Also I think that buttons and checkboxes could have less gradient, or that we can make minor changes to make some things look more modern?

Next week I'm going to be busy, but if you prefer I will continue to add GUI work to this PR. I listed some things I wanted to do on the "Left for another PR" title on the top post

**Comment by alex-w** [comment]
Left the standard GUI elements to another PR is OK for me.

**Comment by martinber** [comment]
There I fixed the Logs tabicon and squashed the commits a bit, just in case you want to merge it

**Comment by gzotti** [comment]
Looks fine. However, I admit I don't understand the consequences of the changes in viewDialog.ui. @alex-w ?

**Pull request merged**
