### PR TITLE
Build with MinGW and Clang

### PR DESCRIPTION
**Pull request by hmartinez82**
### Description
Fixes building with MinGW-gcc and Clang

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] Housekeeping

### How Has This Been Tested?
Stellarium is running and loading the built plugins

**Test Configuration**:
* Operating system: Windows 11 10.0.22621.2361

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by alex-w** [comment]
Please add new item for AppVeyor for testing building via MinGW

**Comment by hmartinez82** [comment]
The only unit tests not passing is testCalendars. I did read the comment there, it's failing in those two tests meant to test "Link Time Code Generation", but I'm not using LTO with GCC nor Clang and still, the unit test fails with both compilers. Any thoughts?

**Comment by alex-w** [comment]
The unit testing is an important one of course, but I meant automatic building the source code - like the current MSVC items

**Comment by hmartinez82** [comment]
I'll work on that. I have to learn AppVeyor from scratch :). I've only used Jenkins and Github Actions in the past :)

**Pull request closed without merging**
