### PR TITLE
New planet magnitudes

### LINKED ISSUE #574: New planet magnitude calculation has appeared
There has appeared a new way of calculating planetary magnitudes. Mercury and Venus seem to be the ones most affected by this new formula.

The paper:
https://www.sciencedirect.com/science/article/pii/S221313371830009X?via%3Dihub

Stellarium could have this as an additional option for the 5 ways of displaying mangitudes given at the moment.

### PR DESCRIPTION
**Pull request by gzotti**
### Description

This branch should add a few planet magnitude improvements:
- A new paper from Mallama&Hilton (2018). 
- A proper magnitude evaluation for the Moon.
- Umbra and penumbra circles.
- Eclipse magnitude in Infostring now in percent
- Earth shadow enlargement using either traditional (2%) or Danjon method.

Fixes #574, #1350, #430.

It does not solve #1115. There is an unknown positional mismatch between numerical and graphical operations, which is a separate problem.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 10 20H2
* Graphics Card: irrelevant

We can 
- observe new planet magnitudes. Esp. Mars showing albedo-dependent magnitude changes
- note the first implementation of a more realistic Lunar magnitude
- see Lunar eclipse details: a small increase of the umbra edge seems to give a better match.
- The umbra circle sizes have been derived as geometrical circle drawn at Lunar distance and using the Besselian size formulations from the Explanatory supplement. There is currently a slight visual difference between the numerical InfoString, shadow visualisation (undocumented) and my geometrical circles results which is hard to trace. Maybe we need to solve aberration and possibly other light time effects before this mismatch can be closed.

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
@alex-w I think you made the shadowFactor in Planet.cpp lines ~2084: Can you please maybe also work out a factor for penumbra for a Lunar eclipse? Currently the opposition surge adds more light than penumbra takes away, which seems odd.

**Comment by Atque** [comment]
@gzotti I know this is draft and WIP an all, but I just wanted to report a bug:
I get some REALLY weird magnitudes for Jovian moons when viewed from Jupiter. They reach magnitude -70 (!).

**Comment by gzotti** [comment]
OK, thanks. Yes, I dared to apply the Mallama algorithm for observers not on earth, but the Jovian satellites were taken from some other source, and this may have to be adapted. Thanks for mentioning, this needs to be fixed of course.
 
Do you agree with the Lunar behaviour now?

**Comment by Atque** [comment]
@gzotti Yes, the lunar formula seems to agree very well with other sources now (even better, actually, since CdC and other planetaria don't take the distance factor into account). The opposition surge makes the sky incredibly bright, which agrees with my own impression of a full moon vs 90%-ish moon.

**Comment by Atque** [comment]
@gzotti You are probably aware of this, but the new magnitude algorithm doesn't take eclipses into account (Jovian, Saturnian and Martian moons seen from respective parent body).

**Comment by gzotti** [comment]
Indeed there was a case still open for non-terrestrial locations that did not care for shadows. TNX.

**Comment by alex-w** [comment]
@gzotti sorry for late answer. Yes, I've added the code for compute the shadow factor, but this code was ported from old version of Stellarium (0.12). Probably it was added by @xalioth or @guillaumechereau

**Comment by Atque** [comment]
@gzotti I get some weird readings for Jupiter when viewed from Saturn. A 0.2% illuminated Jupiter shines at magnitude -3.7, which is clearly incorrect. Is there some kind of phase factor not taken into account?

**Comment by gzotti** [comment]
> @gzotti sorry for late answer. Yes, I've added the code for compute the shadow factor, but this code was ported from old version of Stellarium (0.12). Probably it was added by @xalioth or @guillaumechereau

No problem, I made my own now with pencil&paper and some geometry.

**Comment by gzotti** [comment]
> 
> 
> @gzotti I get some weird readings for Jupiter when viewed from Saturn. A 0.2% illuminated Jupiter shines at magnitude -3.7, which is clearly incorrect. Is there some kind of phase factor not taken into account?

The paper by Mallama&Hilton provide phase functions which end near 150°. Given its principally higher accuracy and phase functions extending widely beyond what's visible from earth, I allow its use also from other planets. The only alternative I see for now is going back not applying this magnitude model for any location but earth/moon, and revert, for all places beyond earth/moon, to the albedo/diameter/phaseangle model the origin of which I don't know. It is OK to be picky, but please consider this as "science currently has no answer for such case". 

You may also again find a few seconds of mismatch between lunar eclipse factor and the visual contact with the shadow indicator circles. The latter use a slightly different way to work out the shadow geometry. On third reading I can try to apply the usual way to derive shadow diameters in arcseconds and convert back to kilometers for drawing. 

I am a bit unsure about the magnitude curve during Lunar eclipses. May deserve another look, but I must really do other things this week.

**Comment by Atque** [comment]
> The paper by Mallama&Hilton provide phase functions which end near 150°. Given its principally higher accuracy and phase functions extending widely beyond what's visible from earth, I allow its use also from other planets. The only alternative I see for now is going back not applying this magnitude model for any location but earth/moon, and revert, for all places beyond earth/moon, to the albedo/diameter/phaseangle model the origin of which I don't know. It is OK to be picky, but please consider this as "science currently has no answer for such case".

I thought it might be a limitation. This algorithm is much better overall.

> You may also again find a few seconds of mismatch between lunar eclipse factor and the visual contact with the shadow indicator circles. The latter use a slightly different way to work out the shadow geometry. On third reading I can try to apply the usual way to derive shadow diameters in arcseconds and convert back to kilometers for drawing.

Isn't this simply an issue caused by the absence of aberration computation?

**Comment by gzotti** [comment]
>Isn't this simply an issue caused by the absence of aberration computation?

I am not 100% clear about the reason for the apparent asymmetry. What really surprised me is that the numerical computation (which uses apparent positions) and the shadow simulation (which should use the same numbers) appear to disagree by a few seconds. Also the circle should match in a very symmetric way, but does not, by some arcseconds. But indeed, we should implement all things around aberration, and then reconsider these deviations. I think at least for illustrative purposes the current set of improvements is quite good.

**Review by alex-w — APPROVED** [review]
Thank you very much for the code!

**Pull request merged**
