### PR TITLE
Updated Bengali Descriptions

### PR DESCRIPTION
**Pull request by t4saha**
### Description

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — APPROVED** [review]
Thank you very much for translations, but I fear those maybe lost, because we exported all texts onto Transifex and we are updating all *.utf8 files from transifex translations per language. I hope the putting copy of those translations onto Transifex is not big problem.

P.S. Of course I can add note to the script to exclude bn language for updater.

**Comment by t4saha** [comment]
Ok then I will update the translations in the transifex portal. 

One question : does the .isl file and the translated description file for scenary 3D plugin aslo generated from the transifex portal ?

**Comment by alex-w** [comment]
.isl - no, description - yes

**Comment by alex-w** [comment]
wait! scenery description - no

**Pull request merged**
