### PR TITLE
AstroCalc/Almanac

### PR DESCRIPTION
**Pull request by alex-w**
### Description
This pull request contains a new module for AstroCalc tool - Almanac. The new module have a few specific submodules.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
I convert it to draft due Almanac subtool is not complete yet.

**Comment by gzotti** [comment]
After the 23.3 feature freeze, I would like to at least get #3207 done.

**Comment by alex-w** [comment]
> After the 23.3 feature freeze, I would like to at least get #3207 done.

This feature for v23.4 or v24.x

**Comment by gzotti** [comment]
Yes, so we should concentrate on getting 23.3 issues off the table.

**Comment by gzotti** [comment]
What happened?

**Comment by alex-w** [comment]
> What happened?

I'll rewrite the module

**Pull request closed without merging**
