### PR TITLE
"spiky stars" is not very accurate (also in translations)

### PR DESCRIPTION
**Pull request by axd1967**
### Description
a better term exists in astrophotography: **diffraction spikes**. or the "**starburst effect**".
this should make translations easier (the Dutch translation "_stekelige sterren_" is poor and can be replaced with "_diffractielijnen_").

Fixes # (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by axd1967** [comment]
- to me this is an attempt to simulate diffraction.

image



- and if Stellarium is claiming to be realistic, then "decorative stars" have no place...

**Comment by gzotti** [comment]
I know the texture. I painted it. 

Spiky stars have also been used in printed atlases in the 17th-20th centuries. Some users asked for them.

If we give in to rename it, you will come with the next "suggestion for somebody to implement, but I will not do it" to adapt the figure to the currently used telescope or model the star figures in myopic/astigmatic eyes. These are decorative symmetrical stars, but may look to some users like diffraction patterns of some telescopes. This is called "interpretation".

**Comment by axd1967** [comment]
Sounds reasonable. In such case, I'd rather be tempted to draw nice abstract lines (like one of '🟄 ✶ ✷ ✹ 🟎' or even ' 𐫰 ' ), rather than something that _definitely_ looks like diffraction spikes (and triggers this kind of issues)? 

I'm curious as to the arguments of those users that asked for such graphics in Stellarium.

I tried to find some references on the web (by lack of an issue!) to get a better idea. 

https://www.atlasobscura.com/articles/the-exquisite-drawings-from-the-first-map-of-the-entire-sky

a few crops for the interested:

image
image


Ah: a good question, but the answers are lacking: https://hsm.stackexchange.com/questions/6532/when-and-why-did-the-spiky-star-appear-as-an-image-in-art-and-science

Further...
https://webspace.science.uu.nl/~gent0113/celestia/celestia.htm

_(But for the n'th time, can we keep the personal attacks out? We are all just doing our best to push Stellarium further.)_

**Comment by alex-w** [comment]
> I'm curious as to the arguments of those users that asked for such graphics in Stellarium.

Demonstrations in planetarium as artificial representation of stars for constellations war one of request and reason to including this feature.

**Comment by alex-w** [comment]
Probably this PR should be rejected or, at least, we can create a new one texture for decorative star (maybe take it from old atlas) to avoid a "diffraction spikes" look.

@gzotti ?

**Comment by gzotti** [comment]
My oh my. Why not add a pixel editor into the configuration dialog to edit your favourite star shape? Draw a different 16x16 texture that looks like a decorative star but has no spikes, and add a config option to config.ini? Or add 5 more textures, give them appropriate names, and let the user choose? This comes from adding too many options. There are really more urgent things to improve.

I see this PR not useful. "Spiky stars" is a common English term. Hint: How this appears in other languages is up to the translators.

**Comment by axd1967** [comment]
_abuse

**Pull request closed without merging**
