### PR TITLE
Hires screenshot

### PR DESCRIPTION
**Pull request by gzotti**
To continue #102: This is not finished yet, but I am a bit stuck, maybe @guillaumechereau or @xalioth can share some insight. 

I want to make high-resolution screenshots. The various parts of the scene, gui, projection, etc. have to be resized, and certainly I have overlooked something again. I cannot make the button bars appear in the low edge of the screen. Also I don't like the hackish projection parameter patching, is there a more elegant solution?

These hi-res screenshots would be nice to have. I think it is acceptable to have small dialog windows and small text, usually these big images are intended for text/guiless poster prints. Panoramas 16384 pixels wide? No problem on better machines.  Or at least FullHD screenshots on netbooks. Maybe text should be resized? I have not played with the effect of pixelRatio, maybe this helps here?

### CODE REVIEW

**Comment by guillaumechereau** [comment]
As far as I know it's hard to make large size screenshots, and in the current state of the code will involve a few hacks.  I am not sure how to handle the UI rendering properly since this is done by Qt on top of the OpenGL rendering and the code here is already quite complex.

**Comment by guillaumechereau** [comment]
Just tested the branch, I confirm the problem with the bottom bar (on linux).  There is also a small bug in the config dialog: the screenshot size cannot be typed properly, I have to move the cursor after each stroke.  Not sure why.

**Comment by gzotti** [comment]
Config bug: Indeed, I only ever changed the thousands... I have an input mask attached which allows only digits. Probably this is connected. Else, we could make a Spinwheel instead of textboxes, but it's a long spin up to 16000... (Maybe steps of 100 pixels? But what if you want 2048 px for a reason?)
Ah, it works with a QIntValidator instead, will fix that.

Still, the missing bottom toolbar is a mystery to me. The StelGui->forceRefreshGui() should do just that. Or is that a signal to redraw on next render pass, and the screenshot making is just one pass, so it never redraws? I call setGeometry() to avoid the bars drawn inside the image. But it seems forceRefresh() does nothing now.

**Comment by alex-w** [comment]
This feature may cause OpenGL error "Request for more GPU memory than is available" (http://nvidia.custhelp.com/app/answers/detail/a_id/3553), so, maybe we should check number of GPU memory to set the maximum size of screenshot and reduce wanted size to possible values?

**Comment by gzotti** [comment]
Actually I test max framebuffer size, so I thought that's enough. Yes, other tests should be added and image size limited as required.

**Comment by alex-w** [comment]
After some playing with this new feature I found source the "invisibility" of the bottom bar. The main problem is changing geometry of SkyGui without changing geometry of  their parent - StelGui - so in this case all objects outside parent rectangle are cropped.

**Comment by gzotti** [comment]
Good idea, but I see no geometry in StelGui. If I tweak StelGui's parent, StelMainView, I think this is limited by the OS to your screen's resolution (?). Or were you successful and like to show your code?

**Comment by gzotti** [comment]
Yes, this is the problem. I have a clipped button bar with a screenshot of 1220 height (1920x1200 monitor) But is there a solution?

**Comment by gzotti** [comment]
Alright. it's the StelRootItem configured to clip its children... We are getting further!

**Comment by gzotti** [comment]
Yes, that was it! 8192^2 screen shot looks terrific. 16384^2 should work, but only has Milky Way...

**Comment by gzotti** [comment]
I saw that the StarMgr defines star sizes in pixels. Had to add a scale value, but not sure whether this should be applied like now or better applied somewhere else. Result of a large star map looks really nice. It could be used to increase font or button bar size if we want that, or meteor shower radiant symbols, or tweak the distance of the gridlines. It's a matter of taste to change those. The application of the huge images is likely on posters, so adjusting GUI size is not an issue.

@alex-w can you please tell me under which circumstances you have that memory issue?

**Comment by gzotti** [comment]
I see Travis build fails with an unknown GL constant. Actually I don't really do anything else than log the retrieved result, and I don't fully understand the figures, I cannot reproduce problems mentioned by @alex-w . Either disable this test when compiling with clang, or completely?

**Comment by alex-w** [comment]
@gzotti compilation of this branch is broken on OS X

**Comment by gzotti** [comment]
I know, see my previous comment. The break concerns a value request about free GL memory, which apparently does not exist on Macs. The whole test block could be removed or just commented away on OSX. 

Please define "oversized". I had no problems with maximal sizes 16k^2 on a card that qualified itself as capable to do that, and even MESA made 8192^2.  I also had no problems making 8k^2 on my old Ubuntu notebook (Geforce 9800), although it reported no values on the AMD test.

**Comment by alex-w** [comment]
I think it's ready to merge after exclude or resolve problematic code for OSX. I'll try to get memory error again, but I may test in at work only.

**Pull request merged**
