### PR TITLE
Ensure Unicode strings are converted when compiling  with Unicode enabled

### LINKED ISSUE #2934: Telescop control : cannot open serial device
### Expected Behaviour:
I have a NexStar compatible telescop controler which can conect at Stelarium throught Bluetooth on my celularphone an works prety well. I  expect to do the same on Stelarium 1.1 or 1.2  on Windows 10  ( the controler was working ok with somme old version of stelarium on a Lenovo YOGA Laptop Windows 10)

### Actual Behaviour
I get in the log file: "ERROR creating TelescopeClientDirectNexStar: cannot open serial device "COM5"
TelescopeClient::create(): Unable to create a telescope client." 

I can tell you that if I connect on COM 5 with Putty and send some comands to the controler i receive good answers ( so the BT connection via COM 5 is working).

### System
* Stellarium version: <stellarium-1.2-qt6-win64?>
* Operating system: <Windows 10 Version 22H2>
*Laptop ASUS ExpertBook 

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/10300576/log.txt)

### PR DESCRIPTION
**Pull request by A-j-K**
### Description

Qt6 appears to have introduced Unicode compilations. Type casting is insufficient and a full byte conversion is required.

Fixes #2934 

### Screenshots (if appropriate):

N/A

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

This was tested using my SkyWatcher SynScan Handcontroller AZ-GTiX Mount.

Note, this fix was at the serial port level and therefore I believe will address any mount that uses a serial port and not just my own SkyWatcher mount.

**Test Configuration**:
* Operating system: Windows 11 Qt6 6.3.4

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation (header file)
- [ n/a] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ n/a] I have added tests that prove my fix is effective or that my feature works
- [ n/a] New and existing unit tests pass locally with my changes
- [ n/a] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 10110111** [comment]
Wouldn't it be better to always use Unicode-enabled `CreateFileW`, regardless of Qt version and `UNICODE` macro, instead of all this useless conditional compilation?

**Comment by 10110111** [comment]
Also, `QString::fromUtf8("...").constData()` already provides a sequence of UTF-16 code units, so no need to create an `std::string` and convert via codecvt.

**Comment by 10110111** [comment]
> I currently don't have a system that can build a Qt5 version

You can use the AppVeyor build that's configured in `.appveyor.yml` in the source tree root. Prepending `[publish]` in commit messages produces binary artifacts. You should choose the "patch" one (which only installs `stellarium.exe`), otherwise if you download the full installer several times, you'll run over download limit.

> Quite happy to rework it that way

Yes, please do. I really dislike how complicated the code is becoming. Even before this change the code looked needlessly complicated. So please make it simple, there's not a single reason to use 8-bit legacy code pages with Qt where `QString` already stores data in UTF-16.

**Comment by gzotti** [comment]
You can use the Qt MaintenanceTool in your Qt directory to add Qt5.15.2 (make sure to add QtScript and the other required additional libraries). Then in QtCreator, select the Kit for Qt5.15.2 and in the  cmake configuration, make sure to set ENABLE_QT6 to false/0. You may need to set Qt5 libs instead of Qt6 into PATH as well. 

+1 for simpler code. Note that most of the telescope plugin code roots in Qt4 times.  I did the Qt6 ifdefs and was happy I could compile it, but had no hardware to test. If there are functions that work on both, Qt5 and Qt6, it's preferrable. Methods introduced after Qt5.12 would still be problematic, though, as the Qt5 releases are AFAIK still made with 5.12. 

@alex-w is Qt5.9 still used somewhere, or could we raise at least to 5.12?

**Comment by alex-w** [comment]
> Qt5.9 still used somewhere, or could we raise at least to 5.12?

No, we can update requirements up to Qt 5.12

**Comment by alex-w** [comment]
Probably this PR fixed #3006 already

**Review by alex-w — APPROVED** [review]
Can't test on hardware, but looks ok

**Review by gzotti — APPROVED** [review]
If it did not work before, and works with this on actual hardware, sure it's OK for me!

**Comment by gzotti** [comment]
It is possible that this fix has already solved a handful of them. OPs would need to test their gear now with a new build. It's a pity 23.2 just came out, so this will likely take months...

**Comment by gzotti** [comment]
I also have just fixed another error around a message connection that was renamed in Qt5.15 and would never have worked on Qt6. Whatever reported issue this probably fixes I cannot say as we rarely receive useful logfiles (where this issue would have been visible). This is one of the big problems with the TC plugin: we would need ~30 devices to test on 3 OS and 2 CPU families, and 30 user-developers to debug and keep the program working with their own gear, not withdrawing to obsolete versions on the slightest hint of problem. So, any help is welcome, and esp. working fixes after deep reverse-engineering insights!

**Comment by gzotti** [comment]
Qt5 builds are required on older systems:
- 32bit versions. This also includes users of older instrumentation with 32bit-only ASCOM drivers. 
- Windows 7 systems
- Windows systems with weak graphic subsystems, e.g. Intel Core-i of 1st/2nd generation are blacklisted by Qt and need to run ANGLE mode, which is no longer available with Qt6. And there are even weaker systems (Pentium6, Celeron, Atom, ...), things that users with higher demands may just mask out when shopping for new systems. 
 
It seems many observers use such oldish, otherwise obsolete systems to drive their telescopes, or they are in regions of this planet where PCs don't rain from the sky, and even old, used PCs are a major investment. A 2008 PC with Win10 (works in most cases!) and ANGLE is still better than no PC. Qt5 based releases for Windows should IMHO be provided as long as Win10 is widely used (i.e., at least V25.4), and as long as the code differences are miniscule. On Linux, some LTS distros may still have no Qt6. And who knows what will happen when probably hundreds of millions systems will (at least officially) have to move from Win10 to Linux in late 2025?

After release of 1.0 reports about issues with the TC plugin came in. About every report that included version number indicated Qt6, which is why we recommend using Qt5-based builds (but not obsolete 0.21 builds!). This most likely indicates I messed up something while porting to Qt6, but was not able to identify what. People complained in some astro forums instead of reporting with us, and often declared to have reverted to older versions.

**Comment by 10110111** [comment]
> Pentium6

What is this? Do you mean Pentium Pro, with the P6 microarchitecture? This won't even run Windows 7. Pentium 4? This one is usable with a discrete GPU.

> On Linux, some LTS distros may still have no Qt6

They are irrelevant, their official Stellarium packages won't be upgraded anyway until OS release upgrade.

> have to move from Win10 to Linux

No one will have, just as many haven't moved from Windows 7 to anything, because at least this may bring problems with driver support.

**Comment by gzotti** [comment]
> > Pentium6
> 
> What is this? Do you mean Pentium Pro, with the P6 microarchitecture? This won't even run Windows 7. Pentium 4? This one is usable with a discrete GPU.

Whatever, maybe my memory fails with all these CPU names. A year ago I was asked for help with an older sub-Core-i laptop. I installed Win10, and Stellarium 0.22.1 worked in ANGLE mode. The thing serves the daily needs of an older gentleman.  Then maybe it was Pentium-IV. Already then I associated "Pentium" with the 1990s. Now they seem to also call Atoms "Pentium". And I admit, I will never learn their "Lakes".

Now, fit a discrete GPU into such an old laptop!

> > On Linux, some LTS distros may still have no Qt6
> 
> They are irrelevant, their official Stellarium packages won't be upgraded anyway until OS release upgrade.

We provide Ubuntu packages for 18.04LTS. Does it have Qt6? 

> > have to move from Win10 to Linux
> 
> No one will have, just as many haven't moved from Windows 7 to anything, because at least this may bring problems with driver support.

Requote: **"(at least officially)"**

**Comment by alex-w** [comment]
> We provide Ubuntu packages for 18.04LTS. Does it have Qt6?

Sorry, but no, we do not provide packages for Ubuntu 18.04 LTS

**Comment by gzotti** [comment]
I was referring to https://launchpad.net/~stellarium/+archive/ubuntu/stellarium-releases
image
OK, maybe 23.1 was the last then? 

I have two Odroid SBCs which are stuck with 18.04LTS. On these I like to have the latest features available, but can only build with Qt5. I hope I could still point out: being able to build with Qt5 will be needed for a few more years.

**Pull request merged**
