### PR TITLE
Vectors

### PR DESCRIPTION
**Pull request by wlaun**
### Description

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by wlaun** [comment]
Tests still not compiled.

**Comment by wlaun** [comment]
On Fri, 17 Apr 2020 at 19:02, Alexander Wolf <notifications@github.com>
wrote:

> *@alex-w* requested changes on this pull request.
>
> Well, the unit tests are failed - please check the code.
>
> See: https://travis-ci.org/github/Stellarium/stellarium/builds/676296445
> and https://ci.appveyor.com/project/alex-w/stellarium/builds/32256612
> ------------------------------
>
> In src/tests/testConversions.cpp
> <https://github.com/Stellarium/stellarium/pull/1051#discussion_r410352066>
> :
>
> > +	data << "+45d0m0s"	    << M_PI/4. << "legacy";
>
> +	data << "+90d0m0s"	    << M_PI/2. << "legacy";
>
> +	data << "+80d25m10s"	<< a(80,25,10) << "legacy";
>
> +	data << "+400d0m5s"	    << a(400,0,5) << "legacy";
>
> +	data << "-30d0m50s"	    << a(-30,0,50) << "legacy";
>
> +	data << "123.567 N"	    << a(123.567,0,0) << "legacy";
>
> +	data << "123.567 S"	    << a(-123.567,0,0) << "legacy";
>
> +	data << "123.567 W"	    << a(-123.567,0,0) << "legacy";
>
> +	data << "+46d6'31\""	<< a(46,6,31) << "legacy";
>
> +	data << "12h0m0s"	    << M_PI << "legacy";
>
> +	data << "6h0m0s"	    << M_PI/2. << "legacy";
>
> +	data << "10h30m0s"	    << h(10,30,0) << "legacy";
>
> +	data << "+80°25'10\""	<< a(80,25,10) << "legacy";
>
> +	data << "-45d0m0s"	    << -M_PI/4. << "legacy";
>
> +	data << "-80°25'10\""	<< a(-80,25,10) << "legacy";
>
> +	data << "-80r25m10s"	<< -0.0 << "legacy";
>
>
> A typo?
>
Where?
-W

**Comment by alex-w** [comment]
See “-80r25m10s” - why “r” here?

**Comment by wlaun** [comment]
It was written by the person who developed the original test. You'll have
to ask him why he used "r". I merely copied all the original ("legacy")
test cases. Note that the expected result is -0, so it was never meant to
return -80.4...°.
-W

**Comment by alex-w** [comment]
Parser not work properly on Windows: https://ci.appveyor.com/project/alex-w/stellarium/builds/32258956

**Comment by wlaun** [comment]
Legacy code, e.g., Stellarium-0.19.1.17106-x86_64.AppImage is broken, at
least on my Linux box with
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
...

I could fix it by using the literals '°' and 'º' in the regular expression,
and all the tests will pass. But this doesn't mean that a binary compiled
on one some developer machine will work on some Linux or Windows machine
running this or that locale.

I'll have to look into this. I'll also have to check whether there's any
other use of characters beyond u+007F in the Stellarium code.

I suppose you don't want to drop support for degree signs or characters
beyond U+007F entirely?

Wolfgang

**Pull request merged**
