### PR TITLE
Avoid screen blanking on Intel UHD (#2166 #2472 #2484)

### LINKED ISSUE #2166: Display goes blank frequently in v0.21.3
My display keeps going blank in v0.21.3.  Although the has been a known issue for several previous versions I have been using ANGLE mode to launch Stellarium with no problems.
Now, in this latest version, the screen blanking has returned even in ANGLE mode.  Same thing for MESA mode.  It does not happen when I mouse around on the regular star screen or move the sky view around.  It does seem to occur once I click on any of the options buttons on the left side of the window.  Trying to do some things in the windows that open seems to induce the blanking.

Running Windows 11 on an HP laptop with:
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 8 Gb RAM, Graphics: Intel(r) UHD Graphics 620, driver v27.20.100.8935
Log file is attached
[log.txt](https://github.com/Stellarium/stellarium/files/7856982/log.txt)
.

### LINKED ISSUE #2472: Borderless fullscreen windowed mode
**Is your feature request related to a problem? Please describe.**
It's not really addressing any specific problem, I would categorize this instead as a matter of ease of use, especially when switching between Stellarium and other windows on the system.

**Describe the solution you'd like**
I would like to be able to run Stellarium in a borderless fullscreen windowed mode, which visually would be presented as is the default fullscreen mode, covering the task bar, etc., but allowing to seamlessly ALT+TAB between windows without entering and exiting the exclusive fullscreen mode, as is the case with the latter. This would resemble the behavior that happens when using ANGLE, but in this case it would not require ANGLE for that purpose.

**Describe alternatives you've considered**
None, beside using the software in ANGLE mode, or in standard window mode with the downside that it has the title bar and doesn't cover the whole screen resolution (ie: taskbar). You can manipulate the windows with tools such as *Borderless Window Utility*, to force the window to become borderless, but it still will not be able to cover the taskbar. Regardless, it would be great if it could be done natively

**Example of the current window maximized**
stellarium_kd7obQVjv2

**Forced borderless window (still cannot cover taskbar)**
stellarium_L2R8s8x65J

### LINKED ISSUE #2484: Screen goes black for a brief moment then image reappears, flickering
### Steps to reproduce

Start any Stellarium executable, click on any object, scrollin in a bit and screen flickers after that.

### System
* Stellarium version: 0.22.1
* Operating system: Win 10 Pro, 21H2, build 19044.1706
* Graphics Card: Nvidia gtx 1080ti, driver 512.15, no overclocking.
* Screen type (if applicable): LG C9 TV, resolution 1920:1080, HDMI, 120Hz, 12 bpc, RGB signal, no HDR,  scaling 150% (changed scaling - no effect)

### Logfile 
File attached
[log.txt](https://github.com/Stellarium/stellarium/files/8853144/log.txt)

### PR DESCRIPTION
**Pull request by uwes-ufo**
### Description
Avoid screen blanking on Intel UHD (#2166 #2472 #2484)
Screen flickering on Intel UHD Graphics is a long-known issue. The backlight turns off and on multiple times! The current workaround is to switch to Angle mode. But in Qt6 there is no more angle mode...
Perhaps the user should make their choice based on a configuration setting value like:
... if (confSettings->value("video/SwapBehaviorSingleBuffer", false).toBool()) ...

Fixes #2166
Fixes #2472
Fixes #2484

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 11
* Graphics Card: Intel UHD 620

## Checklist:
- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
I don't have a hardware to test it. @gzotti can you help here?

**Comment by gzotti** [comment]
I never experienced screen blanking, I only have a few IntelHD/HD2000/530 systems. If this switch solves the issue and causes no other, yes, we can take it, but with documentation, e.g. about important startup troubleshooting options. (SUG section 2.5?)

**Comment by alex-w** [comment]
> I never experienced screen blanking, I only have a few IntelHD/HD2000/530 systems. If this switch solves the issue and causes no other, yes, we can take it, but with documentation, e.g. about important startup troubleshooting options. (SUG section 2.5?)

Good idea!

@uwes-ufo could you record the video from patches and unpatches Stellarium?

**Comment by uwes-ufo** [comment]
> @uwes-ufo could you record the video from patched and unpatched Stellarium?

Sorry but I don't have a camera - just the built in laptop webcam. I've tried using a mirror, but believe me or not, the screen flicker effect even prevents the camera from working. Like a master reset on the entire graphics system.

**Comment by gzotti** [comment]
No smartphone or even pre-Android phone with camera? Quality need not be great.

**Comment by uwes-ufo** [comment]
> No smartphone or even pre-Android phone with camera? Quality need not be great.

Sorry no smartphone - I gave it to my daughter...

**Review by alex-w — APPROVED** [review]

**Comment by 10110111** [comment]
Single buffering sounds like a very suspicious solution. What does it actually mean in Qt5/6? Does the rendering happen directly to the screen, so that on very slow systems we would see each frame accumulate objects instead of showing the complete frame instantly? Or does the buffering happen before blitting of the intermediary FBO to screen?

**Comment by gzotti** [comment]
Yes, I expect to read these considerations and descriptions in the User Guide. Still don't know why some Intel-only systems reportedly show this behaviour.

**Comment by 10110111** [comment]
But there's nothing to describe in the UG: this PR makes single buffering unconditional.

**Comment by gzotti** [comment]
Ouch, indeed! It had that config variable when I first saw it. @alex-w please consider activating this. I must quit for the day.

**Comment by uwes-ufo** [comment]
I would like to download stellarium-1.22.2-0511533-win64.exe based on Qt 6.3.1 - where to find it?

**Comment by alex-w** [comment]
I fear it will be publish tomorrow, due AppVeyor traffic limitations

**Comment by 10110111** [comment]
Not sure if it's the issue that was supposed to be fixed by this PR, but I tried running current weekly build with `--single-buffer` option passed, and appearance of tooltips (e.g. over light pollution slider) or dialog boxes (e.g. new atmosphere model) results in flicker on Intel UHD Graphics 520 on Windows 11.

**Comment by uwes-ufo** [comment]
Unfortunately, the "--single-buffer" switch has no effect on the Qt5 build. Hopefully stellarium-1.22.2-0511533-win64.exe based on Qt 6.3.1 will be available for download soon...

**Comment by uwes-ufo** [comment]
please try stellarium-1.22.2-38a869f-win64.exe with --single-buffer

**Comment by 10110111** [comment]
Just checked, it works fine indeed. I wonder why though. Maybe the issue is worth reporting to Intel instead of working around it. It's always better to have good drivers instead of good kludges.

**Pull request merged**
