### PR TITLE
Convert Spherical and Fisheye landscapes to pure fragment-shader rendering

### PR DESCRIPTION
**Pull request by 10110111**
### Description

These two commits convert spherical and fisheye landscapes to pure fragment-shader rendering. This makes them look nice at large field of view, including the new equirectangular projection. 

The old style landscape (one of which is the default one) needs much more work to implement, so it's not done yet.

The spherical landscape has a quirk: in GLES2 or GL<3.3 it gets a seam at the point where the texture wraps in longitude. In principle, this could be fixed for 3.0≤GL≤3.2, but this would require insertion of `#version` directive that's different from current "`3.3` or empty". Whether this should be done is to be discussed.

#### Old "Moon" landscape (type: spherical)

stellarium-009

#### New "Moon" landscape

stellarium-010

#### New "Moon" landscape with a seam

stellarium-011

#### Old "Trees" landscape (type: fisheye)

stellarium-001

#### New "Trees" landscape

stellarium-002

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Ubuntu 20.04
* Graphics Card: Intel UHD Graphics 620

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — APPROVED** [review]
Great!

**Comment by gzotti** [comment]
Looks great :-)
I cannot see the seam. Where to configure this? 
Or better, do you know/suspect any systems where this would not work? E.g. Mesa 11 (OpenGL 3.0) as delivered with Qt6.4? Or RasPi4 (Mesa22/OpenGL 2.1)?

**Comment by 10110111** [comment]
> Or better, do you know/suspect any systems where this would not work? E.g. Mesa 11 (OpenGL 3.0) as delivered with Qt6.4? Or RasPi4 (Mesa22/OpenGL 2.1)?

Both. Basically, anything that's not capable of desktop OpenGL 3.3 will display this seam in the current state of this code.

**Comment by gzotti** [comment]
Hmm... while I like the new view in capable systems, we should not leave the minor end broken with that ugly seam. Any ideas what to do? E.g., how much effort (also concerning code readability/maintenance) would be a complete switch old/new behaviour?

**Comment by 10110111** [comment]
@gzotti I've pushed a fix, please see if it's good enough.

**Comment by gzotti** [comment]
`+` no seam
`-` edge is not covered
Screenshot from Windows/Qt6.4.0/Mesa.

stellarium-066

But this appears probably like before.  It seems on the RPi4 this still works nicely with closed seam. So yes, we can accept this for now!

**Comment by 10110111** [comment]
> edge is not covered

What does azimuthal grid say? The landscapes don't extend beyond the core domain of the projection. We can easily change this, but it needs a decision whether we want it.

**Comment by 10110111** [comment]
> If you mean, we could extend and repeat landscape in a regular cylindrical layout beyond the core area, this would also be great!

This would be exactly as it's always been for atmosphere. Just an analytical (or sometimes custom) continuation that the projectors already have.

> But this would require both landscape and all sky features!

This is much harder, since most of other features are rendered from model space to screen space, which uses only one branch of the inversion of the screen-to-modelspace mapping.

> [screenshot]

The screenshot shows something strange though. Could you show numeric labels to make sure I understand it correctly?

**Comment by 10110111** [comment]
Here's what I get with the equirectangular projection. Yours is strangely incomplete. Could you post the log?

stellarium-001

**Comment by gzotti** [comment]
This is what I meant with "looks like before", i.e. there is the gap. 
stellarium-068
 Log with Win10/Mesa11: [log.txt](https://github.com/Stellarium/stellarium/files/10202723/log.txt)

**Comment by gzotti** [comment]
Ah, stupid error! I was already back at master. Forget my last entries!

**Comment by gzotti** [comment]
> > But this would require both landscape and all sky features!
> 
> This is much harder, since most of other features are rendered from model space to screen space, which uses only one branch of the inversion of the screen-to-modelspace mapping.

Sure. I was surprised you seemed to suggest it.

**Comment by 10110111** [comment]
> I was surprised you seemed to suggest it.

No, I just suggested this:

stellarium-003

stellarium-004

**Pull request merged**
