### PR TITLE
Fixed Milky Way texture

### PR DESCRIPTION
**Pull request by sunshuwei**
Better orientation of the 47 Tucanae in the milkyway.png.

微信图片_20241203163715

### Description

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] Housekeeping

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 10110111** [comment]
This looks suspicious. Does anyone know how this spot was added to the texture? Was it present there from the beginning, or did someone add it by hand? If it was there from the beginning, then this change is quite dubious.

**Comment by sunshuwei** [comment]
> This looks suspicious. Does anyone know how this spot was added to the texture? Was it present there from the beginning, or did someone add it by hand? If it was there from the beginning, then this change is quite dubious.

As far as I know, it was in another incorrect position 10 years ago.
@Atque fixed it with #2421. But for some reason, it is still in the incorrect position.
https://github.com/Stellarium/stellarium/pull/2421

**Comment by Atque** [comment]
The texture comes from Axel Mellinger's panorama (can be found as an HiPS layer), and some stars were uglily visible until I removed them in 2020. I left the DSO's untouched to make them appear fuzzier in wide angles of view, but 47 Tuc was too off, so I tried fixing it in a separate PR. Clearly I did not do it well enough.

**Review by 10110111 — APPROVED** [review]
OK, so reverting to the texture before #2421 by
```
git checkout f8ea563652eb6a7fc02c8372922c28a3a46a6757^ -- textures/milkyway.png
```
yields a very good placement of the spot in the render. I suppose it's because the Milky Way was rendered using an imprecisely texture-mapped grid instead of the current exact computation of the texture coordinates (implemented in 0464f529759fd08b1d7e5984e43809ce5e095af0).

The new texture in this PR places the spot back, so now it LGTM.

**Review by alex-w — APPROVED** [review]
Thanks!

**Comment by sunshuwei** [comment]
In this case, the 2021 Milky Way texture seems to be a better choice.
It will avoid possible errors caused by manual modification.

**Comment by sunshuwei** [comment]
It looks perfect.
64987f4d-5f30-4292-a3c7-96b336fb1f50

**Pull request merged**
