### PR TITLE
Make QXlsx use the correct Qt

### PR DESCRIPTION
**Pull request by DarthGandalf**
### Description

Fixes issue reported in #2838

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by DarthGandalf** [comment]
@10110111 is this fixes your build, I'll send the patch to QXlsx upstream, and fix the URL here

**Comment by 10110111** [comment]
Yes, this fixes the errors.

**Comment by DarthGandalf** [comment]
@10110111 he suggested a different solution at https://github.com/QtExcel/QXlsx/pull/258
Does the updated PR work for you?

**Comment by 10110111** [comment]
If you mean `CMAKE_PREFIX_PATH`, then how is that supposed to work if both Qt versions are installed in `/usr`?

**Comment by 10110111** [comment]
Still sounds like a kludge. Why have both `-DENABLE_QT6` and `-DCMAKE_PREFIX_PATH`? Maybe one should be dropped then, if the other works universally?

**Comment by 10110111** [comment]
So, is your idea to replace `CMAKE_PREFIX_PATH` from inside `CMakeLists.txt`? This sounds hacky.

**Comment by DarthGandalf** [comment]
> So, is your idea to replace CMAKE_PREFIX_PATH from inside CMakeLists.txt? This sounds hacky.

It's already in this PR :) and it's not replace, but change. It's possible user provided their CMAKE_PREFIX_PATH already, we shouldn't break that use case.

**Comment by DarthGandalf** [comment]
@10110111 https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html says that this variable is supposed to be set by the project, which I read as set by CMakeLists.txt

@alex-w of course! that's exactly what I'm trying to do here, which broke in #2838

**Comment by 10110111** [comment]
> It's already in this PR :)

Oh, didn't notice you changed it. OK, this works now. I think there should be a comment explaining this hack.

**Comment by DarthGandalf** [comment]
> I think there should be a comment explaining this hack.

Done.

**Review by 10110111 — APPROVED** [review]

**Review by alex-w — APPROVED** [review]

**Pull request merged**
