### PR TITLE
Astrocalc: findRightAscension replacement

### LINKED ISSUE #1901: It would pay off to implement those directly using Planet::getHeliocentricEclipt...
https://github.com/Stellarium/stellarium/blob/c3bf117b051b0010547787ac5e9ffb56f37546af/src/gui/AstroCalcDialog.cpp#L4816-L4819

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in c3bf117b051b0010547787ac5e9ffb56f37546af when #1852 was merged. cc @Stellarium.

### PR DESCRIPTION
**Pull request by gzotti**
### Description

Not really a bug fix but this may improve efficiency: A replacement of a function that avoids computing everything

Fixes #1901 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Just run it. The problem is that I don't know exactly what to search for. 
The original function computed equatorial J2000 positions. Meanwhile this includes aberration, while the replacement function provided here does not (yet) include that. 

If the sole purpose of this function is finding <em>times</em> for standstills etc, we don't need aberration. If the numbers are important, I will continue to work on this and provide a solution including aberration. 

**Test Configuration**:
* Operating system: Win10 (irrelevant)
* Graphics Card: irrelevant

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
In one hand a new solution is more accurate, in other hand it slowly rather previous version. I need to recheck rules of exclusion of computations (I've compared 0.21.1 and this branch).

**Comment by gzotti** [comment]
I am surprised that this should be slower? This new solution only computes two planets, not the whole SolarSystem. 
This needs 
* execution timing comparison of master vs. this branch
* an answer about what exactly this function is used for. J2000 coordinates, sure, but with or without aberration? Are the actual numbers important, or is this just used for finding things like greatest elongation?

**Comment by alex-w** [comment]
I think this PR should be rebased and rechecked after merge PR #1880

**Comment by alex-w** [comment]
@gzotti how you tested this solution and what is your results?

**Review by alex-w — APPROVED** [review]
I think we can merge it

**Comment by alex-w** [comment]
Please check the latest stable version of Stellarium:
https://github.com/Stellarium/stellarium/releases/latest

**Pull request merged**
