### PR TITLE
[TCP] manual commands for NSEW

### PR DESCRIPTION
**Pull request by asiniscalchi**
New buttons for the INDI telescope to move it manually by pressing them.
One new slide to set the speed (4 speed)
Some refactoring in the code to make it cleaner.
image

### CODE REVIEW

**Comment by gzotti** [comment]
Very nice! We had a request for "D-Pad usage" for quite a while now. (https://bugs.launchpad.net/stellarium/+bug/1609234)

Maybe the move controls can be made an "optional part of the Stellarium protocols"? Both LX200 and the NexStar protocols allow moves with varying speeds. Possibly the slider needs different max values?

**Comment by asiniscalchi** [comment]
@gzotti 
- what do you mean with "optionl part of the Stellarium protocols" ?
- I only coded the 4 standard velocity of INDI protocol.
- what about remove the slider and manual move only at the slowest one ?

**Comment by gzotti** [comment]
@asiniscalchi 
* Sorry, "protocol" was ambiguous, (1) coming from ObjectiveC terminology. Maybe "virtual base class" in C++. I mean, virtual methods should go already into class TelescopeClient, with some implementation that does nothing (maybe qDebug()<< "MOVE: not implemented"). Both TelescopeClientLX200 and TelescopeClientNexStar could implement it from the available (LX200|NexStar) protocol documentation. The TelescopeClientTCP (this may be factored out into new files?) implements Stellarium's (2) "Stellarium telescope control protocol", talking to the old TelescopeServer programs (found in the old wiki! http://stellarium.sourceforge.net/wiki/index.php/Telescope_Control or http://stellarium.sourceforge.net/wiki/index.php/Telescope_Control_(client-server) ) or StellariumScope. I am not really involved with the TelescopePlugin development, so I don't know whether those old programs still are officially supported or maintained (@alex-w @xalioth are they?), or could be extended to deal with new commands in the "Stellarium telescope control protocol".  Or somebody might even re-implement such servers in Python, Ruby or other languages, tutorial-style. I don't know about RTS2 in detail, but this would (for now) work with the virtual methods of the base class. 
* OK, that means INDI has 4 speeds. NexStar I think has 9 preset speeds (or even allows free programmability), not sure about LX200. Some generic methods setSpeed(int), int maxSpeed() etc. could deal with such device-dependent differences. 
* Not so good I think. E.g. the slowest speed in NexStar is reeeally slow. Maybe replace the buttons by 4 sliders like an analog joystick? Or grab the touch pad and allow variant speeds? But no, this makes things needlessly more complicated. The slider could become a numerical spinbox, but this is a matter of taste. It may be useful to define hotkeys (e.g. Alt-W/A/S/D on gaming keyboards?) instead of mouse clicking.

**Comment by asiniscalchi** [comment]
(1) I already extended TelescopeClient with the virtual methods for manual moving. I will add the logs for null implementation.
(2) actually the API I introduced has the following signature:
  - virtual void TelescopeClient::moveNorth(int speed);
it's more flexible than the a general setSpeed methods: If I want to move NE I code:
 - moveNorth(1);
 - moveEast(1);
This way you can move in every direction.
A more general implementation could be:
 - virtual void TelescopeClient::move(double angle, double speed);
I will think about it ... I have the feeling it's the optimal solution.
(3) let's forget the point

**Comment by gzotti** [comment]
setting a motion angle sounds interesting, but please be aware of the actual possibilities of the mounts and the basic communication protocols for NexStar and LX200, You will have to decompose possibly into 4 commands like "setSpeed(7), RA+, setSpeed(3), Dec-" with speed factors depending on angle. (I have seen at least NexStar protocol allows free speed selection, so this may be very fine grained.) If that works, great! But I am not sure if the second speed command would affect the RA move while it is already moving. 
With a freely selectable angle, of course some different GUI may be needed, maybe a "virtual joystick" in the center of the 4 buttons (these should remain to allow pure RA or DEC movement).

**Comment by asiniscalchi** [comment]
Mmm...I just the commit is to remove the libnova dependency.
The viceversa.

**Comment by asiniscalchi** [comment]
For the size of libindi:

➜  external git:(dev_telescopeControl) ✗ du -h ./libindi 
92K	./libindi/libs/indibase/connectionplugins
20K	./libindi/libs/indibase/alignment/CMakeModules
1,5M	./libindi/libs/indibase/alignment
3,0M	./libindi/libs/indibase
92K	./libindi/libs/webcam/v4l2_decode
376K	./libindi/libs/webcam
48K	./libindi/libs/lx
124K	./libindi/libs/stream/recorder
104K	./libindi/libs/stream/encoder
360K	./libindi/libs/stream
3,9M	./libindi/libs
448K	./libindi/obsolete
188K	./libindi/drivers/filter_wheel
1,6M	./libindi/drivers/telescope
936K	./libindi/drivers/focuser
292K	./libindi/drivers/rotator
192K	./libindi/drivers/weather
160K	./libindi/drivers/dome
68K	./libindi/drivers/agent
116K	./libindi/drivers/video
592K	./libindi/drivers/auxiliary
68K	./libindi/drivers/ccd
4,2M	./libindi/drivers
120K	./libindi/tools
44K	./libindi/examples/tutorial_six
68K	./libindi/examples/tutorial_seven
40K	./libindi/examples/tutorial_one
76K	./libindi/examples/tutorial_five
48K	./libindi/examples/tutorial_eight
44K	./libindi/examples/tutorial_two
60K	./libindi/examples/tutorial_four
48K	./libindi/examples/tutorial_three
444K	./libindi/examples
48K	./libindi/test/core
64K	./libindi/test
11M	./libindi

~ 11 Mb that can be lower if examples and drivers are removed.

**Comment by xalioth** [comment]
Well i don't mean only libindi, but the whole INDI stuff in our git:

fabien@fabXPS15:~/projects/stellarium/src/external/indi$ du -h --max-depth=2
16K	./tools
88K	./libindi/tools
2.7M	./libindi/libs
2.7M	./libindi/drivers
32K	./libindi/test
336K	./libindi/obsolete
220K	./libindi/examples
7.1M	./libindi
8.0K	./.circleci/ubuntu_bionic
8.0K	./.circleci/ubuntu_artful
8.0K	./.circleci/debian_stretch
8.0K	./.circleci/debian_buster
60K	./.circleci
36K	./travis-ci
208K	./cmake_modules
52K	./debian/libqhy
36K	./debian/indi-sx
40K	./debian/indi-eqmod
32K	./debian/indi-gpsnmea
68K	./debian/libindi
36K	./debian/indi-maxdomeii
44K	./debian/libinovasdk
36K	./debian/indi-nexdome
44K	./debian/fliusb
44K	./debian/libfishcamp
32K	./debian/libindi-all
40K	./debian/gsc
36K	./debian/indi-qhy
36K	./debian/indi-apogee
40K	./debian/indi-qsi
68K	./debian/kstars
36K	./debian/indi-aagcloudwatcher
316K	./debian/libgphoto2
40K	./debian/indi-inovaplx
36K	./debian/indi-duino
64K	./debian/fxload-libusb
40K	./debian/libfli
32K	./debian/indi-gpsd
36K	./debian/indi-fli
36K	./debian/indi-armadillo-platypus
40K	./debian/libapogee
96K	./debian/astrometry-data
52K	./debian/libsbig
36K	./debian/indi-sbig
36K	./debian/indi-ffmv
40K	./debian/indi-fishcamp
40K	./debian/asi-common
40K	./debian/indi-gphoto
44K	./debian/indi-mi
36K	./debian/indi-dsi
36K	./debian/indi-asi
32K	./debian/indi-nexstarevo
44K	./debian/libqsi
1.9M	./debian
3.3M	./macosx/INDI Server
3.3M	./macosx
25M	./3rdparty/libqhy
180K	./3rdparty/indi-sx
532K	./3rdparty/indi-eqmod
64K	./3rdparty/indi-gpsnmea
120K	./3rdparty/indi-mgen
76K	./3rdparty/indi-maxdomeii
28K	./3rdparty/libinovasdk
52K	./3rdparty/indi-nexdome
56K	./3rdparty/fliusb
296K	./3rdparty/libfishcamp
104K	./3rdparty/indi-qhy
148K	./3rdparty/indi-apogee
108K	./3rdparty/indi-spectracyber
76K	./3rdparty/indi-qsi
15M	./3rdparty/indi-radiosim
416K	./3rdparty/indi-aagcloudwatcher
108K	./3rdparty/indi-ssag
312K	./3rdparty/indi-tess
76K	./3rdparty/indi-inovaplx
1.3M	./3rdparty/indi-duino
60K	./3rdparty/fxload-libusb
392K	./3rdparty/libfli
32K	./3rdparty/indi-gpsd
100K	./3rdparty/indi-fli
64K	./3rdparty/indi-armadillo-platypus
8.8M	./3rdparty/libapogee
100K	./3rdparty/libdspau
2.6M	./3rdparty/libsbig
196K	./3rdparty/indi-sbig
56K	./3rdparty/indi-ffmv
68K	./3rdparty/indi-fishcamp
16K	./3rdparty/asi-common
228K	./3rdparty/indi-gphoto
660K	./3rdparty/indi-mi
232K	./3rdparty/indi-dsi
92K	./3rdparty/indi-gige
52K	./3rdparty/generic-ccd
17M	./3rdparty/indi-asi
36K	./3rdparty/indi-shelyak
76K	./3rdparty/indi-rtlsdr
124K	./3rdparty/indi-nexstarevo
1.9M	./3rdparty/libqsi
75M	./3rdparty
88M	.

**Comment by asiniscalchi** [comment]
Tomorrow you will count ~3 MB

**Comment by alex-w** [comment]
Oops... On Windows: c:\stellarium\src\external\libindi\libs\indibase\indilogger.h(31): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory 

This is should be fixed of course.

**Comment by gzotti** [comment]
I am just within another branch and cannot test it today with Indi in any case. I think the idea with the 4 buttons and speed control is good, it had been requested already long ago, see above. 

Erm... how do I pull this branch to my computer now? (Still beginner in git!)

Hopefully tomorrow/Sunday I can check if Dummy telescope could be made to work. 

On the future of the plugin: As expressed a week ago (above), I think

* the directly connected devices should remain included for simplicity in handling, and the Stellarium Telescope Protocol should be extended (or has been already) to include these move commands. It shall be allowed that a device ignores the move commands (with a debug message). Better yet, the Dialog can disable the move buttons if a device has no valid implementation for "MOVE".
* What is the future of the 10 year old TelescopeServers (available on SF)? Are *these* supported still? I have found them only by chance, and never used them! If yes, they should be moved here (in a separate repo). 
* I would also like to see somebody create a "pushto" mount tinkering tutorial for 3D-printed gears and simple decoders, running in Python, on a Raspberry Pi Zero W (wireless!).  Open that as "challenge" for somebody?

**Comment by axd1967** [comment]
> As a more general comment, I think it was a mistake to add all the dependencies for this plugin inside the git. That's more than 80 Mb of mostly binary stuff, and is way too large to put in a git. Imagine at the next update we will add again 80Mb in the git.. That's not sustainable.

Totally agree. We should not put binary stuff in Git. 
Note that there would exist extensions that allow to manage such big binary objects, but the question should then rather become: can we split off such external stuff? See also the discussion in #1295 .

> 
> Instead, the build system should just ensure that the dependency is present on the developer's setup, like usual dependencies.

Agree.

Also, one should question whether the average user needs all that ; this is exactly why a TRUE plugin should be offered for users that need the INDI stuff. At the same time, the repo would remain light and compilation would be faster.

(and a TRUE plugin, not a plugin that users cannot remove... because that is no longer a plugin!)

**Pull request merged**
