### PR TITLE
Improve OpenGL text drawing performance.

### PR DESCRIPTION
**Pull request by unpacklo**
### Description
Improve text drawing performance with OpenGL by using a static instance of `QOpenGLPaintDevice`. I still haven't narrowed down exactly what is causing the performance problem but I can see creating a new `QOpenGLPaintDevice` causes every `drawText()` call to create and destroy GL buffer objects.

Yields about a 2x speedup for my typical setup which draws lots of lines for the celestial sphere.

Fixes # (issue)

### Screenshots (if appropriate):
Before, 10 FPS:
image

After, 20 FPS:
image

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Manually ran the change with a locally built stellarium and profiled with Instruments.

**Test Configuration**:
* Operating system: macOS 13.1
* Graphics Card: Radeon Pro 560X 4 GB
Intel UHD Graphics 630 1536 MB

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — APPROVED** [review]
Thanks!

**Comment by 10110111** [comment]
Even though this improves performance, this is still a hack, so it deserves a comment explaining why this object is static and what OS environment needs this.

**Comment by gzotti** [comment]
I tend to agree with @10110111 on this. The Qt docs of this class warns to be careful when interacting with the GL state. Can we guarantee that nothing can break when we leave a static object for re-use? (Or is it better to use an instance member variable in StelPainter and take care of this?)

**Comment by 10110111** [comment]
Instance member will be worse because it will partially restore the performance dip, since StelPainter is created and destroyed multiple times per frame.

**Comment by gzotti** [comment]
Maybe then the StelPainter should be kept alive and handed around for a longer time?

**Comment by gzotti** [comment]
Yes, I know. But if creation&destruction, i.e., state switching&restoring, happen so often, of course this is a plausible cause of slowdown. If we can hand around a StelPainter for a longer time, it should save a lot of overhead.

**Comment by alex-w** [comment]
I got report about performance regression in Windows also :(

**Comment by 10110111** [comment]
> I got report about performance regression in Windows also

Does this PR improve the situation?

**Comment by alex-w** [comment]
> Does this PR improve the situation?

- 1.2 release with equatorial grid - 17-35 fps
- the current branch with equatorial grid - 17-40 fps

macOS 13.2.1, MBP, M1

**Comment by 10110111** [comment]
The code that this PR changed has now been removed, hopefully the performance will be acceptable now. The PR itself is therefore obsolete.

**Comment by gzotti** [comment]
We can close this, thanks to all participants!

**Pull request closed without merging**
