### PR TITLE
Python clean ups

### PR DESCRIPTION
**Pull request by IceflowRE**
@deix <m.powalko@gmail.com>
- Use "List Comprehensions"
- Use the "with" keyword when dealing with file objects
- Use the "with" keyword when dealing with file objects
- Fixed: indentation issues, trailing white spaces, missing white spaces around operator

Iceflower
- Fix code indentation

See #5 

---
I didnt do tests after this "rebase".

### CODE REVIEW

**Comment by xalioth** [comment]
could you please split commits related to indentation, and the ones with real code changes? It's hard to review otherwise.

**Comment by IceflowRE** [comment]
Done.

**Comment by IceflowRE** [comment]
@alex-w Can we merge this?

**Comment by xalioth** [comment]
Thanks

**Pull request merged**
