### PR TITLE
dots are for dialog openers, not for action buttons

### LINKED ISSUE #916: bookmarks: remove triple dot in "Go to..." button
Convention is to open a dialog box when clicking a button that contains dots: the dots signal that more is to come before something will happen.

In the case of Bookmarks, the button does not open a dialog box, but triggers an immediate action.

### PR DESCRIPTION
**Pull request by axd1967**
fixes #916

### Description

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
If you edit several files with the same "mission" (dots for openers...), you can just add to the same PR.

**Comment by alex-w** [comment]
I hope this tool will be removed before release 0.20.0

**Comment by gzotti** [comment]
Which? The whole Bookmarks thingy? Or do you want to redesign it? I admit I rarely use it, but it seems it has its friends.

**Comment by alex-w** [comment]
Currently one french guy in process of deep refactoring and redesigning this tool (Bookmarks) into tool for manage observing lists. Previously he added patch for support many bookmark lists for the tool but in the private discussion I proposed rewrite the tool to enhance it.

**Comment by axd1967** [comment]
* i can add the dots to those buttons too, even if it is to be removed.
* in the case of the refactoring, #882 and #917 will be solved too :-) 
* please tell "the french guy" to avoid .ini files and use something like YAML ... those ini files are horrible to version control, manage and share with other users.

**Comment by alex-w** [comment]
> * i can add the dots to those buttons too, even if it is to be removed.
> * in the case of the refactoring, #882 and #917 will be solved too :-)

Sorry, Alex, but sometimes I do not understand you, because it looks like you critique tools who never use. You are removed 3rd line about ini and ugly YAML - sorry, but Bookmarks never used YAML not INI. Why you asked about technology or data format for tool, who never used touched the technology or format from the question? About behaviour in your report #917 - how we can resolve unreproducible issue? For your report #882 - the current behaviour of Bookmarks are implemented as was required by users. I really don't understand why we should make this tool very difficulty for understanding by users and include many inner meanings for clearly checkboxes, who you will never use? No, new tool will be not support setting time and location for bookmarks.

**Comment by axd1967** [comment]
hello @alex-w ... we obviously have language issues. never mind, we will get there.

about #882 - just let it simmer. someone will pick up the issue and/or propose a solution, don't worry (but if the whole bookmark feature gets replced, the entire discussion will become moot).

**Comment by alex-w** [comment]
Superseded by master

**Comment by axd1967** [comment]
ok!

**Pull request closed without merging**
