### PR TITLE
Smooth orbit lines (esp. for comets)

### PR DESCRIPTION
**Pull request by gzotti**
### Description

Drawing orbit lines from 360 time steps along the orbit works well for ellipses with low eccentricity only. 
For highly elongated comet orbits, the perihel area is covered only with a few vertices, which causes a polygonal, usually vastly undersampled appearance. With the time step approach, the situation was remedied a bit by not plotting the entire orbit, but only the part which is signified by the orbit_good value in ssystem_minor.ini. 

This PR provides a solution that constructs the entire orbit for ellipses with eccentricities e<0.999, by stepping over the eccentric anomaly. This looks generally much better and allows the estimation where in the outer solar system the object has its aphel. There still remain a few "polygon orbits" when they appear close to the observer. 

Fixes # (issue)

### Screenshots (if appropriate):

stellarium-094

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 11
* Graphics Card: Geforce (irrelevant)

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 10110111** [comment]
Is the screenshot the state before this PR or after?

**Comment by gzotti** [comment]
It's the new state. Previously, only the orbit_good days were shown for the orbits, although most can now be shown entirely. Yes, there are still a few edges visible, those are close to the observer. We can increase to 720 or 1440 steps per orbit to remedy that somewhat (at probably high CPU cost), but an n-gon always has vertices...

**Comment by 10110111** [comment]
How is the second commit related to this PR?

**Comment by 10110111** [comment]
> We can increase to 720 or 1440 steps per orbit to remedy that somewhat (at probably high CPU cost), but an n-gon always has vertices

This way would indeed require too many vertices, the closer the curve and the wider the FoV, the more vertices we'd need. But we need them only in one section, not for the whole orbit. So I think a better approach would be to generate the orbit already in the screen coordinates (which we do need to obtain anyway in `drawOrbit()`), and sample it smartly, something like this:

1. Generate a few points, say, 10.
2. For each pair of points measure angle and distance between them **on screen**.
3. If some quality function of angle and distance is too low, add a point with eccentric anomaly taken as average between the two.
4. Stop when all lines have sufficient quality.

**Comment by gzotti** [comment]
I did not intend to fix #1650. This here provides a significant improvement, though.

**Review by alex-w — APPROVED** [review]
Well, good improvement

**Review by 10110111 — APPROVED** [review]

**Pull request merged**
