### PR TITLE
Always use texture-based text rendering in StelPainter

### PR DESCRIPTION
**Pull request by 10110111**
This will let us control gamma correction by simply changing texture format when we convert our rendering pipeline to linear colors. We can't do this when using QOpenGLPaintDevice.

Text rendering quality doesn't change. From my observations via apitrace, QOpenGLPaintDevice does basically the same, even for rotated text: just renders textured quads with the texture containing text.

A side effect is a small performance improvement when the scene has a lot of text.

The `-t` mode now only disables antialiasing in `StelPainter::drawText`, and also does something for the GUI, which I didn't change.

Also, this PR will make #3003 obsolete and, possibly, fix the cause of it.

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Ubuntu 20.04
* Graphics Card: Intel UHD Graphics 620

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
The `-t` mode enable very strange look for text in bottom bar

**Comment by 10110111** [comment]
> The `-t` mode enable very strange look for text in bottom bar

Not my fault, it's similarly ugly in `master`.

**Comment by alex-w** [comment]
As far as I remember `-t` mode was added for low-cost devices such RPi or ANGLE-“powered” (low-graphics?) systems. Bad news, that I can’t saw when we broke GUI in `-t` mode.

**Comment by 10110111** [comment]
It was for RPi, and the aliasing was intended. As for the wrong placement of the panel (not sure if you see it too), I suspect it might have been broken by #3125.

**Review by alex-w — APPROVED** [review]

**Comment by alex-w** [comment]
But in this case we can remove support -t mode

**Comment by 10110111** [comment]
So, should we do it now?

**Comment by alex-w** [comment]
I think yes. @gzotti?

**Comment by gzotti** [comment]
I hope I can test with RPi3&4 later tonight.

**Comment by gzotti** [comment]
What is ugly or broken with -t in master?

**Comment by gzotti** [comment]
Ok, looks like the older composition/layout of that status line. It still works, but just looks less perfect than the reworked solution. I may have not cared, given the lack of actual necessity of the -t option.

**Comment by gzotti** [comment]
Please compare: right: 23.2. left: this branch, regular mode. At least on Windows, there is a significant loss of quality. 
Screenshot (82)

**Comment by gzotti** [comment]
RPi3, this PR
stellarium-rp3_pr3343
RPi3, master
stellarium-rp3_master

**Comment by gzotti** [comment]
RP4, master
stellarium-rp4_master

RP4, master with -t
stellarium-rp4_master-t

RP4, this PR
stellarium-rp4_pr3343

RP4, this PR with -t
stellarium-rp4_pr3343-t

This really gives a nice speed gain!

**Comment by 10110111** [comment]
> At least on Windows, there is a significant loss of quality.

What if you run with `-platform windows:fontengine=freetype` command line option?

**Comment by 10110111** [comment]
So, except for Windows, everything looks OK, right?

**Comment by gzotti** [comment]
> > At least on Windows, there is a significant loss of quality.
> 
> What if you run with `-platform windows:fontengine=freetype` command line option?

Yes, that works. Fonts are a bit narrower now. Right: 23.2, left: this PR
Screenshot (83)

OK, to accept this, the platform option must go into all startup links, like `-platform windows:altgr,fontengine=freetype`, into the cmake/*.iss.* files.

I can also confirm a great speed improvement here (~40->65 fps!). 

WAIT: I did a few more runs, and suddenly freetype seems not to become active. It looks thin and bad again. No log entries that could help.

**Comment by 10110111** [comment]
> I did a few more runs, and suddenly freetype seems not to become active. It looks thin and bad again. No log entries that could help.

Try following [this post](https://stackoverflow.com/a/36204635/673852) and getting rid of the command line addition.

**Comment by gzotti** [comment]
Ah, thanks. It seems that the command line parsing of a coma-separated list of options `-platform windows:altgr,fontengine=freetype` does not work. Also giving separated `-platform  windows:...` options fails. The `altgr` option is essential on many international keyboards, though. 

So, what works is a file qt.conf right next to the .exe which contains:
```
[Platforms]
WindowsArguments = fontengine=freetype,altgr

```

This means: 

- On Windows builds, this files has to be created/provided (cmake?)
- It must be deployed in installs (cmake/inno?)
- The `data/*.iss.*` files must be freed from `-platform windows:...` options

**Comment by 10110111** [comment]
> Yes, that works. Fonts are a bit narrower now. Right: 23.2, left: this PR

The +SEP and +SCP items look different in your two windows. Is there a good explanation, or is it a bug in this PR?

**Comment by gzotti** [comment]
Uh, yes. Apps are RemoteSync'ed. No explanation, looks like a bug.

**Comment by alex-w** [comment]
Please check https://github.com/Stellarium/stellarium/commit/186febd4d67b53946ce200bb4e69a0a0450b7086

**Comment by 10110111** [comment]
What do these +SEP and +SCP represent? How do I enable them?

**Comment by alex-w** [comment]
> What do these +SEP and +SCP represent? How do I enable them?

SCP = South Celestial Pole; SEP = South Ecliptic Pole

Please check poles in Markings tab

**Comment by 10110111** [comment]
I have them, and from the code I see that the cross is rendered as a sprite, so this shouldn't be related to this PR.

@gzotti Do you reproduce this lack of the crosses in `master`?

**Comment by gzotti** [comment]
Crosses are fine in master. But I still have the flood of 

`D:\StelDev\GIT\stellarium\src\core\StelApp.cpp:910: OpenGL error: 1281 (GL_INVALID_VALUE)
`

**Comment by gzotti** [comment]
For what it's worth, crosses now also show in this PR.

**Comment by 10110111** [comment]
> But I still have the flood of

Would be useful if you could find the point where this error occurs (e.g. via apitrace).

> crosses now also show in this PR

OK, is it OK to merge then? @alex-w has pushed the changes to `qt.conf`, so it should work now.

**Comment by alex-w** [comment]
Error 1281 should not be happening after rebasing

**Comment by gzotti** [comment]
Can qt.conf also be created in the temporary build directory? I usually run a test build from there, without installation. Currently I need to create this manually.

**Comment by 10110111** [comment]
> Error 1281 should not be happening after rebasing

Where do you see this error?

**Comment by gzotti** [comment]
The 1281 is in master, not in this PR. This seems OK to merge. We could however really remove the -t option (including SUG deletions).

**Comment by 10110111** [comment]
> We could however really remove the -t option

OK, will do it separately.

**Comment by alex-w** [comment]
> Can qt.conf also be created in the temporary build directory? I usually run a test build from there, without installation. Currently I need to create this manually.

It's possible, but I can't do the solution right now - after 2 weeks only. Please fill separate report for this issue for memory.

**Pull request merged**
