### PR TITLE
Add contact times of global solar eclipse in AstroCal

### PR DESCRIPTION
**Pull request by worachate001**
### Description
The main contact times, including latitude/longitude of each contact point.

Note: Minor fix in lunar eclipse - description of 'position angle' in contact table is incorrect for some circumstances. The new one should be better.

### Screenshots (if appropriate):
solareclipse-circumstances

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Manjaro 22.0.0
* Graphics Card: -

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — APPROVED** [review]
Thank you very much!

**Comment by worachate001** [comment]
By the way, as we can calculate location of the Moon's shadow, I'm developing capability to export KML file to open with GoogleEarth/Marble. I hope to add it as well but a bug has been discovered and still under investigation. It might be not ready before Stellarium 1.0, so I think I should add contact times first. This is what we can expected in the next stage.

solareclipse-map

stellariumeclipsemap-marble

**Comment by alex-w** [comment]
@worachate001 maybe removing latitude and longitude columns from upper table now?

**Comment by gzotti** [comment]
The path width is its maximum? Path width are variable as the shadow runs over earth's surface. See its notable variation in case of annular-total (a.k.a. hybrid) eclipses.

**Comment by gzotti** [comment]
For layout reasons, maybe add a rubber buffer to the right of the lower table? The width of the rightmost column looks ugly. Else this addition is great!

**Comment by worachate001** [comment]
> The path width is its maximum? Path width are variable as the shadow runs over earth's surface. See its notable variation in case of annular-total (a.k.a. hybrid) eclipses.

Path width is at the time of greatest eclipse (least distance between shadow axis and Earth's center). So it's not maximum value.

I'm trying to add the path width and duration in the lower table, it should look better and more useful. We will have more information about duration of eclipse at greatest eclipse and at both ends of the center line.

While doing this I think I may found the cause of bug that I'm looking for. Making this PR draft for now, I need more time to investigate.

**Comment by worachate001** [comment]
Path width, duration, and type of eclipse are added to the contact table. Type is useful in case of hybrid eclipse. Most hybrids start and end with annular but not always.

solareclipse-circumstances-update

**Review by alex-w — APPROVED** [review]
Thanks for perfect improvement!

**Review by gzotti — APPROVED** [review]
You rock! Awesome :-)

**Pull request merged**
