### PR TITLE
Improve quality of rings rendering

### PR DESCRIPTION
**Pull request by 10110111**
### Description
Current code that renders planetary rings has some issues:

* ~Outermost layer has a gap, as noted in #2775, and it becomes obvious even on Saturn if we reduce number of "stacks" in the call to `sRing()` to 3 or 2;~
* Rings of Saturn are obviously polygonal when zoomed in to screen size (see left and right sides of the screenshot below);
* ~Additionally, ring shadow is not quite smooth: sort of aliased.~

This PR redoes the rings in the following way:

* ~Instead of making a polygonal model of the rings, the whole model becomes just a quad, and~ texture coordinates are computed in the fragment shader to yield an annulus ~instead of the square~.
* ~Mip mapping is enabled for ring texture.~
* ~Shadow is made behave correctly with mip mapping, finally becoming smooth.~

#### Old Saturn (viewed from Jupiter):

stellarium-003

#### New Saturn (viewed from Jupiter)

stellarium-004

#### Old Uranus

stellarium-001

#### New Uranus

stellarium-002

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Ubuntu 20.04
* Graphics Card: Intel UHD Graphics 620

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — APPROVED** [review]

**Comment by 10110111** [comment]
But this is already much better than what we have in current `master`:

#### This PR:

stellarium-007

#### Master:

stellarium-008

**Comment by gzotti** [comment]
Yes, the problem around #435 is that Pan is inside the rings, so the tessellation in all but Perspective projection makes an ugly mess. Perspective is somewhat bearable. It seems that in your solution the observer is now not surrounded by rings. 
And look into the strange break in the rings also when observed from Saturn's surface. This works well in master.

**Comment by gzotti** [comment]
@10110111 , do you have a working solution at least for this view from Saturn? Else we should push it to 23.1 to not block 1.2.

**Comment by 10110111** [comment]
No, let this go to a next release.

**Comment by 10110111** [comment]
So, I have undone the simplification of the ring mesh to a square, and fixed #2775. Only roundedness of the rings (as seen from faraway observers) remains to be the topic of this PR, which shouldn't break the look from inside the rings more than it already is.

**Comment by alex-w** [comment]
> So, I have undone the simplification of the ring mesh to a square, and fixed #2775. Only roundedness of the rings (as seen from faraway observers) remains to be the topic of this PR, which shouldn't break the look from inside the rings more than it already is.

I accept it and approve the PR

**Review by gzotti — APPROVED** [review]
Very good now, thank you! 
I also consider #435 solved by this solving of the indexing. The ring is  a bit coarse, but no mess.

**Pull request merged**
