### PR TITLE
Indicate max exposure time for moving objects

### LINKED ISSUE #2752: Oculars: Indicate max exposure time for moving objects to avoid trailing
**Is your feature request related to a problem? Please describe.**

Suggested via PM by Andrea Mattei:

> When I select an asteroid, I can see some values in the info, including the proper motion expressed in seconds of arc.
> So, if I have set my scale for my CCD, might it be useful to read the exposure time to use to prevent the asteroid from being moved?
> 
> 
> For example, I have selected Asteroid (1420) Radcliffe. I can read 15" /hour how Proper Motion. My CCD scale is 1.1105"/px
> So, my calc is: 
> 1.1105 / (15/3600) = 266 sec (max time of exposure)
> 
> 
> Selecting (65803) Didymos:
> Proper Motion is: 5' 14" = 314 arc second for hour (at 15 october 2022)
> then: (1.1105 / (314/3600)) = 12.7 sec (max time of exposure)
> 

**Describe the solution you'd like**

If a solar system object is tracked in sensor view, add information of maximum exposure time to avoid a movement of more than 1 pixel width. The info can go as ExtraInfoString or as add-on to the sensor frame. 

**Describe alternatives you've considered**
Currently it needs some brain to estimate this time.

**Additional context**
It can be assumed the telescope is tracking at sidereal rate.

### PR DESCRIPTION
**Pull request by alex-w**
### Description
This pull request contain the implementation (optional feature) of indicate the max exposure time for the moving objects within Oculars plugin

Fixes #2752

### Screenshots (if appropriate):
stellarium-001

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 10110111** [comment]
Does this feature assume that the telescope is installed on a tracking equatorial mount? This should be mentioned somewhere in the docs. Also, if this assumption is true, then the text should only appear for equatorial mount when the selected object is being tracked, or the computation of max exposure time should include the diurnal motion.

**Comment by gzotti** [comment]
Yes, tracked mount that has been well aligned against axes, is well guided, and is in an altitude range to not suffer from differential refraction, sure.  It estimates duration of motion on the sphere against the stars to not exceed 1 pixel (IIRC). 15 years ago nobody would have assumed otherwise. But you can also have motorized tracking on an alt-az mount when you also counterrotate the frame, so "equatorial" is not the criterium.  
Max. exposure for the sky just depends on focal length and declination. Not sure if we really must work out how long user can expose a static camera with 10mm lens when aimed at &delta;=60°.

**Comment by 10110111** [comment]
> But you can also have motorized tracking on an alt-az mount when you also counterrotate the frame, so "equatorial" is not the criterium.

Our "Equatorial mount" checkbox controls whether the frame rotates automatically around its optical axis. Regardless of the mount axes, if the frame remains upright, as is currently rendered in stellarium with "Equatorial mount" unchecked, it can't have the same max exposure time as with equatorial mount, even when tracking an object.

But still, the whole this feature is absolutely undocumented AFAICT, so I couldn't even learn about any assumptions that this rather ambiguous label implies.

**Comment by gzotti** [comment]
It appears that all frame labels are not documented. My hope with in-master guide sources was that features are documented by the respective developers as they are added. :-/

**Comment by gzotti** [comment]
Mentioned in https://github.com/Stellarium/stellarium/commit/666f775c66eaf2cb936f664f7f02261a9b8f7b3a

**Pull request merged**
