### PR TITLE
Observing lists

### PR DESCRIPTION
**Pull request by Jocelyn1109**
### Description
new version of bookmarks: ObservingList

### Type of change
See specifications here: https://github.com/Stellarium/stellarium/issues/976

### How Has This Been Tested?
Manual unit test

**Test Configuration**:
* Operating system: Linux Ubuntu 20.04.2 LTS
* Graphics Card: GeForce RTX2060 6Go

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — CHANGES_REQUESTED** [review]
Please fix codefactor's whitespace/blank_line issues and please add `.kdev4` into `.gitignore` file

**Comment by Jocelyn1109** [comment]
I will correct all problems :)

**Comment by Jocelyn1109** [comment]
Hello @alex-w  there are some problems with the check. I did some corrections and the code is commited but it seems the check not take into account modification. For example this method was modified (https://github.com/Stellarium/stellarium/blob/5ecde6b427f1ae7ce19dd200ba4b5f2da23549b1/src/gui/ObsListCreateEditDialog.cpp#L576-L722) and the code is on my forked repo, but the check is done on the old code. Same problem here with the white space: https://github.com/Stellarium/stellarium/blob/5ecde6b427f1ae7ce19dd200ba4b5f2da23549b1/src/gui/ObsListCreateEditDialog.cpp#L220.

Moreover there are problems with code that not on my side.

Jocelyn

**Review by alex-w — APPROVED** [review]
I think this tool is ready to merge and replace the Bookmarks. Of course it can be improve later.

@gzotti ?

**Comment by gzotti** [comment]
I cannot formally review it this week, sorry. I have said what I think is important functionality. If it is not here yet, I hope for a fix soon.

**Comment by gzotti** [comment]
@alex-w please proceed if you feel comfortable, I may not have time for anything for the next 1-2 weeks. The discussion and my concerns/application scenarios are in #976. If they are not solved by this solution, this may be added in the next months. Time will tell if the feature is useful in this format, but probably you will get some similar remarks in October (when the new release is out - almost nobody is commenting on betas :-(.

**Comment by axd1967** [comment]
I'm afraid this is maybe a tad too soon to merge to master, but indeed it is always painful to discover that beta testing is almost inexistent...

here are my observations

- [ ] bug: import is not working. do this: delete `observingList.json` - start - create list - export - import -> core dump. in fact, I was not able to import a list
- [ ] I assume that lists from other users can be imported too? and they are _added_ to the set of lists?
- [ ] consider adding a confirmation dialog to the Exit button once a list has been created in the main window (new list -> do something -> from that point onwards, the user must be guarded against an accidental exit; do not forget to also guard for closing the dialog via top-right close button)
- [ ] same for "delete list"
- [ ] list names should be unique, just to protect the user from probable upcoming confusion?
it is likely that importing lists can cause duplicate list names, so an import should add some extra information (maybe the file name? date/time of import?)
image
- [ ] what is the intention of the first (empty) line in the screenshot above?
- [ ] list name should not be empty (the save/close should be disabled)
- [ ] be aware of #1811  
- [ ] check a stray character:
image
- [ ] the feature seems to store the location implicitly? (field `location`) what happens if the location is wrong/unknown? 
- [ ] bug: user is sent to "null island"!
image

- [ ] what is the function of the creation time?
image
- [ ] consider assigning read-only fields a different style (eg greyed out)
- [ ] here is an important use case: after selecting an object (planet, star, DSO,...), do not remove the focus from that object when opening the dialogs. this allows to pre-select an object and easily add it to a list
- [ ] I suspect that there is a small issue: the creation date is the master date for the list; someone who wants to create a series of observations during the night must create several lists (eg every minute!). 
- [ ] there is something strange happening with time: create a list item, change time, double-click item => time somehow jumps; is this intentional?
- [ ] "Vesta" is stored as a planet
- [ ] the "description" line could as well be made writeable
image
- [ ] the editor window position is not remembered
image
- [ ] objects should be selectable (double-click) from the editor too: that way, I can easily delete and re-add an object
- [ ] importing/exporting lists should remember the last selected directory (at least during the ongoing session)
- [ ] it seems to be possible to edit a list, keep the editor window open,  and then delete that list from the main dialog. this might lead to bugs, I'm not sure. for example, create two lists, edit one (keep the editor open), in the main dialog delete that very list and then edit the second list; observe that the editor is still busy with the (now deleted) list


## Important
- [ ] this will hide the user's bookmarks, and that might hurt. Especially because the same keyboard shortcut has been used, this **will** give problems to unsuspecting users. it would have been better to create this feature NEXT / in parallel to bookmarks and optionally remove the bookmarks feature in a later release. **so a  a migration routine should be provided that automatically imports the existing bookmark list (eg when `observingList.json` is missing) and transforms it into a default/first observing list. (again, the alternative is to NOT touch the bookmark feature). 

this is a great feature, so please take the following paragraph as positive feedback. 

I believe that the development branch of a new feature should also include the changes in the User Manual, as this achieves two purposes:

1. the developer is the best positioned user to write the first cut of the changes to the User Manual, even if in a rough version. It is likely that those changes will need to be reviewed, another reason to do this in the **feature branch** and not once merged to master, as it could lead to early detection of bugs, misunderstandings etc
2. this helps in reviewing/testing the feature, because now all a tester can use is a UI; what if the UI is not easily understood.

but again, thanks for the new feature!

@Jocelyn1109

**Comment by Jocelyn1109** [comment]
I Will Fix all those problems 

Envoyé depuis Yahoo Mail pour Android 
 
  Le sam., juil. 31, 2021 à 19:52, ***@***.***> a écrit:   


I'm afraid this is maybe a tad too soon to merge to master, but indeed it is always painful to discover that beta testing is almost inexistent...

here are my observations
   
   -    
 bug: import is not working. do this: delete observingList.json - start - create list - export - import -> core dump. in fact, I was not able to import a list

   -    
 I assume that lists from other users can be imported too? and they are added to the set of lists?

   -    
 consider adding a confirmation dialog to the Exit button once a list has been created in the main window (new list -> do something -> from that point onwards, the user must be guarded against an accidental exit; do not forget to also guard for closing the dialog via top-right close button)

   -    
 same for "delete list"

   -    
 list names should be unique, just to protect the user from probable upcoming confusion?   
it is likely that importing lists can cause duplicate list names, so an import should add some extra information (maybe the file name? date/time of import?)   


   -    
 what is the intention of the first (empty) line in the screenshot above?

   -    
 list name should not be empty (the save/close should be disabled)

   -    
 be aware of #1811

   -    
 check a stray character:   


   -    
 the feature seems to store the location implicitly? (field location) what happens if the location is wrong/unknown?

   -    
 bug: user is sent to "null island"!   


   -    
 what is the function of the creation time?   


   -    
 consider assigning read-only fields a different style (eg greyed out)

   -    
 here is an important use case: after selecting an object (planet, star, DSO,...), do not remove the focus from that object when opening the dialogs. this allows to pre-select an object and easily add it to a list

   -    
 I suspect that there is a small issue: the creation date is the master date for the list; someone who wants to create a series of observations during the night must create several lists (eg every minute!).

   -    
 there is something strange happening with time: create a list item, change time, double-click item => time somehow jumps; is this intentional?

   -    
 "Vesta" is stored as a planet

   -    
 the "description" line could as well be made writeable   


   -    
 the editor window position is not remembered   


   -    
 objects should be selectable (double-click) from the editor too: that way, I can easily delete and re-add an object

   -    
 importing/exporting lists should remember the last selected directory (at least during the ongoing session)

   -    
 it seems to be possible to edit a list, keep the editor window open, and then delete that list from the main dialog. this might lead to bugs, I'm not sure. for example, create two lists, edit one (keep the editor open), in the main dialog delete that very list and then edit the second list; observe that the editor is still busy with the (now deleted) list


Important
   
   -  this will hide the user's bookmarks, and that might hurt. Especially because the same keyboard shortcut has been used, this will give problems to unsuspecting users. it would have been better to create this feature NEXT / in parallel to bookmarks and optionally remove the bookmarks feature in a later release. **so a a migration routine should be provided that automatically imports the existing bookmark list (eg when observingList.json is missing) and transforms it into a default/first observing list. (again, the alternative is to NOT touch the bookmark feature).

this is a great feature, so please take the following paragraph as positive feedback.

I believe that the development branch of a new feature should also include the changes in the User Manual, as this achieves two purposes:
   
   - the developer is the best positioned user to write the first cut of the changes to the User Manual, even if in a rough version. It is likely that those changes will need to be reviewed, another reason to do this in the feature branch and not once merged to master, as it could lead to early detection of bugs, misunderstandings etc
   - this helps in reviewing/testing the feature, because now all a tester can use is a UI; what if the UI is not easily understood.

but again, thanks for the new feature!

@Jocelyn1109

**Comment by axd1967** [comment]
See also PR https://github.com/Stellarium/stellarium/pull/1826

**Comment by Jocelyn1109** [comment]
Hello @alex-w, I did some tests but maybe not enough.
I don't have the problem on my side with the List(s) label, even if I change the size of the window.
What is your configuration and your resolution ?

obsList-json-default-text

Jocelyn

**Comment by alex-w** [comment]
> Hello @alex-w, I did some tests but maybe not enough.
> I don't have the problem on my side with the List(s) label, even if I change the size of the window.
> What is your configuration and your resolution ?

I don’t see problems on all my devices with different resolutions. I fear you may reproduce it with specific combination of DPI and font size.

**Comment by Jocelyn1109** [comment]
@alex-w  Sorry the message was to @axd1967 :)

**Comment by Jocelyn1109** [comment]
@alex-w :

"his will hide the user's bookmarks, and that might hurt. Especially because the same keyboard shortcut has been used, this will give problems to unsuspecting users. it would have been better to create this feature NEXT / in parallel to bookmarks and optionally remove the bookmarks feature in a later release. **so a a migration routine should be provided that automatically imports the existing bookmark list (eg when observingList.json is missing) and transforms it into a default/first observing list. (again, the alternative is to NOT touch the bookmark feature)."

Should I keep the old bookmark too with Observing List ?
Are you agree with that ?

Jocelyn

**Comment by alex-w** [comment]
No, please see my email

**Comment by axd1967** [comment]
> Hello @axd1967 @alex-w, I did some tests but maybe not enough.
> I don't have the problem on my side with the List(s) label, even if I change the size of the window.
> What is your configuration and your resolution ?

It could be an issue on my side, but it's not critical.

> 

> 
> "consider adding a confirmation dialog to the Exit button once a list has been created in the main window (new list -> do something -> from that point onwards, the user must be guarded against an accidental exit; do not forget to also guard for closing the dialog via top-right close button)"
> 
> Should I add a popup to confirm to confirm the deletion of a list and when I leave Observing Lists dialog and Observing List edit/modify dialog ?

Yes, definitely. You must prevent the user losing valuable information by mistake, so delete actions should always be guarded.


> 
> Jocelyn

**Comment by axd1967** [comment]
> @alex-w :
> 
> "his will hide the user's bookmarks, and that might hurt. Especially because the same keyboard shortcut has been used, this will give problems to unsuspecting users. it would have been better to create this feature NEXT / in parallel to bookmarks and optionally remove the bookmarks feature in a later release. **so a a migration routine should be provided that automatically imports the existing bookmark list (eg when observingList.json is missing) and transforms it into a default/first observing list. (again, the alternative is to NOT touch the bookmark feature)."
> 
> Should I keep the old bookmark too with Observing List ?

Unfortunately, it's a bit too late. Best is to follow the site maintainer's advice here.

But IMHO efforts should be made to either automatically import the current `bookmark.json` file (if the `observinglist.json` file is missing, which is an indication that the user has not yet been faced with the new feature). Otherwise many users will complain or at least be very surprised (which is called a "breaking change").

> Are you agree with that ?
> 
> Jocelyn

**Comment by axd1967** [comment]
> No, please see my email

Avoid private conversations; there is no need to keep some people in the dark - this is contrary to open source development.

**Comment by Jocelyn1109** [comment]
> I'm afraid this is maybe a tad too soon to merge to master, but indeed it is always painful to discover that beta testing is almost inexistent...
> 
> here are my observations
> 
> * [ ]  bug: import is not working. do this: delete `observingList.json` - start - create list - export - import -> core dump. in fact, I was not able to import a list
> * [ ]  I assume that lists from other users can be imported too? and they are _added_ to the set of lists?
> * [ ]  consider adding a confirmation dialog to the Exit button once a list has been created in the main window (new list -> do something -> from that point onwards, the user must be guarded against an accidental exit; do not forget to also guard for closing the dialog via top-right close button)
> * [ ]  same for "delete list"
> * [ ]  list names should be unique, just to protect the user from probable upcoming confusion?
>   it is likely that importing lists can cause duplicate list names, so an import should add some extra information (maybe the file name? date/time of import?)
>   image
> * [ ]  what is the intention of the first (empty) line in the screenshot above?
> * [ ]  list name should not be empty (the save/close should be disabled)
> * [x]  be aware of [remove i18n field from bookmark file #1811](https://github.com/Stellarium/stellarium/issues/1811)  (OK -> see [Bookmarks becomes Observing List #976 (comment)](https://github.com/Stellarium/stellarium/issues/976#issue-566236071))
> * [ ]  check a stray character:
>   image
> * [ ]  the feature seems to store the location implicitly? (field `location`) what happens if the location is wrong/unknown?
> * [ ]  bug: user is sent to "null island"!
>   image
> * [x]  what is the function of the creation time? ( OK -> see [Bookmarks becomes Observing List #976 (comment)](https://github.com/Stellarium/stellarium/issues/976#issue-566236071))
>   image
> * [ ]  consider assigning read-only fields a different style (eg greyed out)
> * [ ]  here is an important use case: after selecting an object (planet, star, DSO,...), do not remove the focus from that object when opening the dialogs. this allows to pre-select an object and easily add it to a list
> * [ ]  I suspect that there is a small issue: the creation date is the master date for the list; someone who wants to create a series of observations during the night must create several lists (eg every minute!). I think this is the same as [Bookmarks becomes Observing List #976 (comment)](https://github.com/Stellarium/stellarium/issues/976#issuecomment-823197733)
> * [ ]  there is something strange happening with time: create a list item, change time, double-click item => time somehow jumps; is this intentional? -> update: this seems to not always happen, when switching between lists
> * [ ]  "Vesta" is stored as a planet
> * [ ]  the "description" line could as well be made writeable
>   image
> * [ ]  the editor window position is not remembered
>   image
> * [ ]  objects should be selectable (double-click) from the editor too: that way, I can easily delete and re-add an object
> * [ ]  importing/exporting lists should remember the last selected directory (at least during the ongoing session)
> * [ ]  it seems to be possible to edit a list, keep the editor window open,  and then delete that list from the main dialog. this might lead to bugs, I'm not sure. for example, create two lists, edit one (keep the editor open), in the main dialog delete that very list and then edit the second list; observe that the editor is still busy with the (now deleted) list
> 
> ## Important
> * [ ]  this will hide the user's bookmarks, and that might hurt. Especially because the same keyboard shortcut has been used, this **will** give problems to unsuspecting users. it would have been better to create this feature NEXT / in parallel to bookmarks and optionally remove the bookmarks feature in a later release. **so a  a migration routine should be provided that automatically imports the existing bookmark list (eg when `observingList.json` is missing) and transforms it into a default/first observing list. (again, the alternative is to NOT touch the bookmark feature).
> 
> this is a great feature, so please take the following paragraph as positive feedback.
> 
> I believe - this is a personal opinion, not necessarily shared by the other developers - that the development branch of a new feature should also include the changes in the User Manual, as this achieves two purposes:
> 
> 1. the developer is the best positioned user to write the first cut of the changes to the User Manual, even if in a rough version. It is likely that those changes will need to be reviewed, another reason to do this in the **feature branch** and not once merged to master, as it could lead to early detection of bugs, misunderstandings etc
> 2. this helps in reviewing/testing the feature, because now all a tester can use is a UI; what if the UI is not easily understood.
> 
> but again, thanks for the new feature!
> 
> @Jocelyn1109

@axd1967  I think you should validate all your remarks with the team because a lot are not in the specification.
I will correct the bug but I am waiting for the feedback of the team.

Thanks

Jocelyn

**Comment by Jocelyn1109** [comment]
@alex-w  @gzotti  @axd1967 

"consider adding a confirmation dialog to the Exit button once a list has been created in the main window (new list -> do something -> from that point onwards, the user must be guarded against an accidental exit; do not forget to also guard for closing the dialog via top-right close button)"

Do i need to add popups for those cases ? 
- a popup like that "Do you want to quit without saving ? Yes/No
- and another: "Do you want to delete the list ? Yes/No

I didn't see any popup in Stellarium.

Jocelyn

**Comment by axd1967** [comment]
> "it is always painful to discover that beta testing is almost inexistent..."
> You can't say that. You should understand that I do my possible an I work on Stellarium when I have the time.
> 
> Jocelyn

Don't worry, you did your best; this is not directed to you. The problem seems to be that too few developers do a timely review (I'm no exception... I only tested this AFTER it had been merged to master).

**Comment by axd1967** [comment]
> @alex-w @gzotti @axd1967
> 
> "consider adding a confirmation dialog to the Exit button once a list has been created in the main window (new list -> do something -> from that point onwards, the user must be guarded against an accidental exit; do not forget to also guard for closing the dialog via top-right close button)"
> 
> Do i need to add popups for those cases ?

Yes.

> 
>     * a popup like that "Do you want to quit without saving ? Yes/No
> 
>     * and another: "Do you want to delete the list ? Yes/No

Just use the default :

https://github.com/Stellarium/stellarium/blob/d5d8d667a1893d08e8abee9aea6b8bc7f34ac105/src/gui/StelDialog.cpp#L322-L325

(ideally, there should be a string argument that refines the question, but that is not critical for the moment.)
> 
> 
> I didn't see any popup in Stellarium.
> 
> Jocelyn

**Pull request merged**
