### PR TITLE
Calendars plugin: New Hindu and Hindu Astronomical calendars

### PR DESCRIPTION
**Pull request by gzotti**
### Description

This will introduce the New Hindu and Hindu Astronomical calendars to the calendars plugin. 
The test cases for the calendars are OK, and I added also more test on the script for the astro... functions.

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Win10, Qt5.15.2
* Graphics Card: irrelevant

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [x] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
The calendars are done, I think, but not yet the text/data addenda.

**Review by alex-w — APPROVED** [review]
Thanks!

Would you add an option to define custom color of text on the sky for calendars?

**Comment by alex-w** [comment]
> > Would you add an option to define custom color of text on the sky for calendars?
> 
> Currently I use the InfoString color (with black/white switch). Do you mean one color for all, or per-calendar? Should these switch in day/night conditions?

When flag enabled plugin should use custom color for all calendars and ignore day/night conditions, otherwise it should works as is.

**Comment by gzotti** [comment]
I think now it's OK. More to come only later this year... @alex-w I am waiting for the test runs, if you agree I will do the merge.

**Comment by alex-w** [comment]
OK

**Pull request merged**
