### PR TITLE
Bundled QtCompress

### PR DESCRIPTION
**Pull request by alex-w**
### Description
Restore support the building Stellarium with bundled `qtcompress` library in additional to Qt-provided library for manage ZIP archives. Using bundled `qtcompress` library provide binary packages of Stellarium without `qt6-base-abi` dependency in our PPA.

Fixes #3793 (discussion)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [x] Housekeeping

### CODE REVIEW

**Comment by 10110111** [comment]
What are the cases when one would want to use the Qt-provided version? Are the maintainers of, say, Linux distributions supposed to always use the Qt-provided version?

**Comment by alex-w** [comment]
> What are the cases when one would want to use the Qt-provided version? Are the maintainers of, say, Linux distributions supposed to always use the Qt-provided version?

I think for source-based Linux distros, Qt-provided version will be better solution, but maintainers should have known best way for their distros.

**Comment by alex-w** [comment]
Any news for review?

**Comment by 10110111** [comment]
I'm not completely convinced that we want to use the Qt-provided code in this case, since it's simply unclean to rely on implementation details. OTOH, this flag is already an improvement, since we can now disable this reliance.

If all the issues with mixing different licenses are clear (which I'm not competent enough to check), I don't have any additional objections.

**Comment by 10110111** [comment]
I wouldn't bet on it. The request was added 15 years ago at the times of Qt 4.5, and nothing changed since.

**Pull request merged**
