### PR TITLE
Fix: unambiguous comet names

### LINKED ISSUE #3349: Cannot find 1P/Halley in historical apparitions
After the big renaming effort, the F3 search panel no longer can clearly indentify a comet in several apparitions. 

### Expected Behaviour

F3 search: "Halley" should list all known apparitions

### Actual Behaviour

I can only find one entry for 1P/Halley which resolves to 989 N1, and another for P/Halley (1222) which does not load. 

### Steps to reproduce
Load ssystem_1000comets.ini, then search for Halley.

### System
* Stellarium version: 23.2
* Operating system: Win11 (hopefully irrelevant)
* Graphics Card: Geforce (irrelevant)

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
The logfile indicates some message around a "stupid general group" which IMHO should not exist and indicates a bug. 
Logfile of a previous run showed problems around a regular expression ('HALLEY(1456)'), but I cannot reproduce that now. I searched for "Halley", "Halley(1456)" and "Halley (1456)". 

[log.txt](https://github.com/Stellarium/stellarium/files/12251715/log.txt)

### PR DESCRIPTION
**Pull request by gzotti**
### Description

Some recent changes have broken the solar system loading a bit, in that the object name is too short, and data for recurring comets like Halley are overwritten. 

Branch fix/3349 provides a different solution which adds another instance variable to the Comet class. I don't think it's required.

This alternative PR continues re-writing the data files on the one hand, and intends to create unambiguous names on loading.
Another test during load should ensure that data are not overwritten.

To complete that work:
- [x] Adapt SSE plugin accordingly.
- [x] Re-format 1000_comets.ini.

Fixes #3349 (issue)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

Usually, for testing changes: 
- remove current ssysstem_minor.ini from user data dir
- launch program
- import 1000_comets.ini
- Search for Halley and see all entries listed.

**Test Configuration**:
* Operating system: Windows 11
* Graphics Card: irrelevant

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
Please give me a few days before further committing to this draft. I am trying to understand your undocumented changes in the SSE plugin.

**Comment by gzotti** [comment]
The MPC data files are really problematic for periodic comets. They don't come with data codes (e.g. P/2023 T3) but just as nnP/name. 

My original aim here was to dissect all names into the following entries in ssystem_minor.ini:

- name e.g. Halley, NEAT, ... without and additions, orbit codes, brackets, ...
- comet_number (optional). Could be made negative for Defunct (D) comets, or we display P code as long as it was observable. 
- iau_designation I thought this was always like "[PDCA]{-fragment}/YYYY W1". However, it seems officially they would use "nnP/name" in case of periodic comets, without specifying the apparition, and withou putting the name in brackets. (Or maybe the older object designation (from a previous passage) will be kept when there is no "new discovery" but object is practically followed through aphelion?
- perihelion_code old-fashioned like "1986 III" or just "1456" if there was no other in that year.
- discovery_code either old-fashioned like "1982i" or new style like "C/2023 E3". In the latter case the iau_designation may be an updated version after reclassification ("A/2023 E3" if object turned out to be rather an asteroid, or "I/2023 E3" if extrasolar).


from which the name and any combination of labels could be assembled on the fly. However this may still be complicated and may require code duplications at various places. 

There was a list of Halley designations in the newer IAU discovery scheme from which I proposed using things like "1P/1982 U1 (Halley)", but seeing this practice and given that such lists for other comets like Encke may not be available, it may be preferable to simply mark numbered periodic comets with perihelion code or even, to be fully consistent everywhere and not use old labels even where available, only with year of perihelion (which is available in the MPC file).

The _name_ which would be used in ssystem_minor.ini and can then be displayed (screen label) would be (examples)

- 33P/Daniel (1909 IV) or 33P/Daniel (1909)???
- 332P-C/Ikeya-Murakami (2021)
- 1P/Halley (1910)
- 1P/Halley (1986) or 1P/Halley (1986 III)???
- P/2020 V4 (Rankin)

while the Infostring should still show all other codes. This name can be used as name entry in the ini file and (mangled through SolarSystemEditor.convertToGroupName()) group ID. The loader must make sure the group names are unique and give a warning if there is a duplicate. This would also mean that I do not separate the comet number into a separate comet_number entry. If needed, it can simply be extracted from the name. 

@alex-w your comments please?

It may also be easier if I convert my old comet file (the source of 1000comets.ini) into MPC format to just load that without going through ini format first. Converting the ini list is a nightmare... It would finally also allow selecting entries!
@alex-w Did you add data to the 1000comets.ini file? 

(All object designations here are mentioned as examples and some need not exist in reality.)

**Comment by gzotti** [comment]
Probably in a similar way, minor planets should always be formatted like "(1) Ceres" (e.g. in location lists, search lists, ...).

**Comment by gzotti** [comment]
The check for comet data (crossref) may have to be still added to the loading of other .ini files as well. For now I assume the .ini file is finalized.

**Comment by alex-w** [comment]
I think 1P/Halley (1986) and P/2020 V4 (Rankin) looks good for screen labels

**Comment by alex-w** [comment]
> Did you add data to the 1000comets.ini file?

No, I didn't touches the 1000comets file

**Review by alex-w — CHANGES_REQUESTED** [review]
Please check comets A/2022 B3 and A/2023 H4 - the name is empty

**Comment by alex-w** [comment]
Adding comets via SSE plugin are broken now :(

**Comment by gzotti** [comment]
> Please check comets A/2022 B3 and A/2023 H4 - the name is empty

Yes, they have no names! Their data are from MPC. AS I have understood, A/ objects were reclassified as Asteroids, which then have no "right" to bear proper names before they are numbered. I tried to also retype them as asteroids for us in the importer, but some of them have open "orbits" (e>=1), which then causes other problems. (All our minor planets are expected to have elliptical orbits.)

**Comment by alex-w** [comment]
> > Please check comets A/2022 B3 and A/2023 H4 - the name is empty
> 
> Yes, they have no names! Their data are from MPC. AS I have understood, A/ objects were reclassified as Asteroids, which then have no "right" to bear proper names before they are numbered. I tried to also retype them as asteroids for us in the importer, but some of them have open "orbits" (e>=1), which then causes other problems. (All our minor planets are expected to have elliptical orbits.)

I understand it, but now A/2022 B3 exist as A/2022 B3 () also, and the second designation is wrong. So, wrapper for similar objects is needed.

**Comment by alex-w** [comment]
> Adding comets via SSE plugin are broken now :(

At first look, this is a 2 separate issues - converting name into section and formatting the data within inin file

**Comment by gzotti** [comment]
> > > Please check comets A/2022 B3 and A/2023 H4 - the name is empty
> > 
> > 
> > Yes, they have no names! Their data are from MPC. AS I have understood, A/ objects were reclassified as Asteroids, which then have no "right" to bear proper names before they are numbered. I tried to also retype them as asteroids for us in the importer, but some of them have open "orbits" (e>=1), which then causes other problems. (All our minor planets are expected to have elliptical orbits.)
> 
> I understand it, but now A/2022 B3 exist as A/2022 B3 () also, and the second designation is wrong. So, wrapper for similar objects is needed.

Ah, yes, OK. Probably it's enough to test the name for "^A/" to avoid adding (empty) name in brackets.

**Comment by alex-w** [comment]
I tried removing "A/2022 B3 ()" from the list of MSSO via SSE - the item removed from the list, but not from the file.

I tried loading comets from "MCORBS: all comets..." list and I got the crash after troubles with parsing:
```
Done reading comet orbital elements. Recognized 996 candidate objects out of 1001 lines.
No match for "    C.53P010  **** 06 28       0.43      1.00      261       330        71                  9.0  4.0  C/-146 P1                                                 31,  257"
No match for "    C/56K010  **** 05 24       0.22      1.00       17       170       110                  9.0  4.0  C/- 43 K1"
No match for "    C240V010  0240 11 10       0.37      1.00       82       214        44                  9.0  4.0  C/ 240 V1                                                 10,  167"
No match for "    C390Q010  0390 09  4       0.92      1.00       23       356        36                  9.0  4.0  C/ 390 Q1                                                 31,  257"
No match for "    C400F010  0400 02 24       0.21      1.00       47        38        32                  9.0  4.0  C/ 400 F1                                                 31,  257"
No match for "    C418M010  0418 10  4       0.35      1.00      240       310       110                  9.0  4.0  C/ 418 M1                                                CCO    12"
No match for "    C442V010  0442 12 14       1.53      1.00      178       271       106                  9.0  4.0  C/ 442 V1                                                 31,  257"
No match for "    C539W010  0539 11  6       0.16      1.00      246        33        19                  9.0  4.0  C/ 539 W1                                                 31,  257"
No match for "    C565O010  0565 07 14       0.83      1.00       79       180       121                  9.0  4.0  C/ 565 O1                                                 10,  163"
No match for "    C568O010  0568 08 27.6     0.870     1.000      34.9     301.8       4.0                9.0  4.0  C/ 568 O1                                                 31,  257"
No match for "    C574G010  0574 03 24       0.73      1.00      342       155        54                  9.0  4.0  C/ 574 G1                                                 31,  257"
No match for "    C770K010  0770 06  5.8     0.580     1.000      88.0     110.7     117.0                9.0  4.0  C/ 770 K1                                                 31,  257"
No match for "    C817C010  0817 03  2       1.10      1.00      202       315       120                  9.0  4.0  C/ 817 C1                                                CCO    12"
No match for "    C868B010  0868 03  4       0.42      1.00      277       321        65                  9.0  4.0  C/ 868 B1                                                 25,  187"
No match for "    C905K010  0905 04 26       0.20      1.00       50        70       140                  9.0  4.0  C/ 905 K1                                                 31,  257"
No match for "    C962B010  0961 12 28       0.63      1.00       85         2       119                  9.0  4.0  C/ 962 B1                                                 31,  257"
No match for "    CA14C010  1014 04  6       0.56      1.00       84       174       117                  9.0  4.0  C/1014 C1                                                 31,  257"
No match for "    CA18P010  1018 08 26       0.62      1.00      197       185        35                  9.0  4.0  C/1018 P1                                                 31,  257"
No match for "    CA80P010  1080 09 10.9     0.681     1.000      73.6     322.9       6.9                9.0  4.0  C/1080 P1                                                 17,   67"
No match for "    CA92A010  1092 02 22       0.77      1.00       62       114       124                  9.0  4.0  C/1092 A1                                                 31,  257"
No match for "    CA97T010  1097 09 22       0.30      1.00      298       352        41                  9.0  4.0  C/1097 T1                                                 31,  257"
No match for "    CB10K010  1110 05 18       0.83      1.00      358       321       137                  9.0  4.0  C/1110 K1                                                 31,  257"
No match for "    CB32T010  1132 08 30.7     0.736     1.000     114.2     213.2     106.3                9.0  4.0  C/1132 T1                                                5 (3)  17"
No match for "    CB47A010  1147 01 28       0.12      1.00      300       282       110                  9.0  4.0  C/1147 A1                                                 31,  257"
No match for "    CC30X010  1230 12 28.7     0.860     1.000     181.0     303.7      16.0                9.0  4.0  C/1230 X1                                                 31,  257"
No match for "    CC40B010  1240 01 21.5     0.668     1.000     331.4     135.1      75.3                9.0  4.0  C/1240 B1                                                5 (3)  20"
No match for "    CC45D010  1245 04  0       0.50      1.00       87       180        20                  9.0  4.0  C/1245 D1                                                 31,  257"
No match for "    CC64N010  1264 07 20.29    0.8249    1.0000    159.71    151.04     16.40               9.0  4.0  C/1264 N1                                                Leiden"
No match for "    CC93V010  1293 10 28       0.78      1.00      313        89        30                  9.0  4.0  C/1293 V1                                                 31,  257"
No match for "    CC99B010  1299 03 31.81    0.3179    1.0000    103.89    116.94    111.00               9.0  4.0  C/1299 B1                                                  1,  419"
No match for "    CD04C010  1304 02  5.5     0.840     1.000      25.0      88.7      65.0                9.0  4.0  C/1304 C1                                                 34,   21"
No match for "    CD04Y010  1305 01 18       0.65      1.00       56       106        99                  9.0  4.0  C/1304 Y1                                                 31,  257"
No match for "    CD15U010  1315 10 15.0     1.650     1.000      27.3     176.3     125.3                9.0  4.0  C/1315 U1                                                CCO    12"
No match for "    CD37M010  1337 06 14.85    0.7490    1.0000     79.61     97.61    143.60               9.0  4.0  C/1337 M1                                                 31,  257"
No match for "    CD40F010  1340 05 13.62    1.1362    1.0000     32.44    187.63    176.48               9.0  4.0  C/1340 F1                                                 15,   67"
No match for "    CD45O010  1345 08 22       0.89      1.00      210       150        23                  9.0  4.0  C/1345 O1                                                 31,  257"
No match for "    CD51W010  1351 11 18       1.01      1.00      165       264         7                  9.0  4.0  C/1351 W1                                                 31,  257"
No match for "    CD62E010  1362 02 24       0.30      1.00      348       291       155                  9.0  4.0  C/1362 E1                                                 31,  257"
No match for "    CD68E010  1368 05  4       0.48      1.00       90       217       131                  9.0  4.0  C/1368 E1                                                 31,  257"
No match for "    CD76M010  1376 07 31.7     0.550     1.000      81.0     300.7      76.0                9.0  4.0  C/1376 M1                                                 31,  257"
No match for "    CE02D010  1402 03 20       0.38      1.00       91       126        55                  9.0  4.0  C/1402 D1                                                 16,   50"
```

**Comment by gzotti** [comment]
Interesting list. Seems the packed date code does not decode for early years. And yes, the naming/bracket issue is not fixed yet, I did not find enough time this week.

**Comment by gzotti** [comment]
Is the line "Done reading..." from importing the MPC CometEls.txt file? So at least that works. Trying to find what's wrong with the other.

**Review by alex-w — APPROVED** [review]

**Pull request merged**
