### PR TITLE
Ignore cmake-build-debug directory

### PR DESCRIPTION
**Pull request by Neniel**
This change is for adding `cmake-build-debug` directory in the `.gitignore` file.

### Description
This change is for adding `cmake-build-debug` directory in the `.gitignore` file. `cmake-build-debug` directory is generated automatically when opening the project with CLion.

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gzotti** [comment]
Usually the build directory should be created outside the stellarium source directory. Is this unavoidable when using this CLion?

**Comment by alex-w** [comment]
Probably `cmake-build-release` need too, but this is coming from default settings of IDE. By default we expected some directories within `builds ` directory

**Comment by Neniel** [comment]
It has to do with the default configuration of the IDE:
image

I'm not sure if this has the same usage as the `build` directory that currently exists on the project ([where builds have to be made](https://github.com/Stellarium/stellarium/blob/master/BUILDING.md#on-macos)

**Review by alex-w — APPROVED** [review]

**Review by gzotti — APPROVED** [review]
Seems it does not hurt.

**Pull request merged**
