### PR TITLE
Great circle partitions

### LINKED ISSUE #428: Add partitions for various circles
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1590575

Anonymous wish from the forum https://sourceforge.net/p/stellarium/discussion/278769/thread/9ec5c9e6/

OP: I had an idea for a small new feature that could be added to Stellarium.
The Axial Precession circles could have 6 or 8 little white arrow heads spaced at regular angles added to them to show the dirrection of the Axial Precession.

It would also be really great if Stellarium could show approxmately where the Celestial North and South Poles were and will be in the future with 25 little white line marks along the circle for every 1000 years starting at year 0 that can be turned on or off. Not that the year 0 has any special significance for Earth's Axial precession. I just thought it would be a convenient year to start with so it matches the calendar. This way, educators can show students how the direction that Earth's North and South Poles point into space change over time and how Pole stars change with time. Currently, the Axial Precession cycle has a rate that corrosponds to one complete cycle in about 25,772 years. However, the rate varies slightly in a not entirely predictable way due to Earth's equatorial buldge gravatationally interacting with the Sun, Moon and to a much lesser extent, the other planets differently all the time according to Wikipedia.

GZ: Yes, thanks for your interest. There have been similar requests for partitioning the ecliptic, Galactic equator etc. While partitioning those into reguar angles should not be too difficult, exactly the inconstant speed makes that feature request a bit more difficult. It should not be forgotten though.

OP: Ok
If the Precession circles just had the arrow heads on them to show the direction of Axial Precession that would be great.

### PR DESCRIPTION
**Pull request by gzotti**
### Description

This adds optional partitions to the great circles like equator, ecliptic, meridian etc.
Each degree is marked, and 5/10/30 degrees are marked with longer lines.
Applications are manifold: 
- Ecliptic 30 degrees partitioning allows rough estimates of monthly positions of the sun (and, yes, zodiac sections).
- Comparing equator and ecliptic with a celestial grid helps explaining the main reason for equation of time (projection effect).
- Altitude marks on meridian and prime verticals are good hints for altitudes and avoids the full grid.

Fixes #428, #471, #744

### Screenshots (if appropriate):
stellarium-019

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Windows 10
* Graphics Card: Geforce 960M (irrelevant)

## Checklist:

- [X] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Georg, thanks for adding the new feature, but the GUI is overloaded now. Why not add just an one option to switch partitions?

Plus I think using 2 lines for define `Q_PROPERTY` will be better for reading (standard line has width in 80 chars and now some lines has width in 193 chars).

**Comment by gzotti** [comment]
Of course the GUI lines are not finished - see commit comment. I think the middle column can have 

[color] [line] [partitions] Label. 

The only thing is that the line and partitions column come unlabeled themselves. It may be possible to add a caption above, or just work with tooltips. I think partitions should be a per-line feature, not a global switch. Maybe later it could be possible to show even only the partitions without lines, or add numerical labels if requested. 

On the property lines: I think the overview and fast readability is better with long lines. Or do you work on a 17" screen?

**Comment by alex-w** [comment]
> [color] [line] [partitions] Label.

Maybe [color] [partitions] [line] Label.

And add tooltip "Drawing line with partitions" or "Drawing partitions" for [partitions] checkbox?

> The only thing is that the line and partitions column come unlabeled themselves. It may be possible to add a caption above, or just work with tooltips. I think partitions should be a per-line feature, not a global switch. Maybe later it could be possible to show even only the partitions without lines, or add numerical labels if requested.

I've assigned to you (and update list of fixes in description) all requests for drawing lines with partitions (with re-opened requests) - I fear the numbers near partitions already requested by users. But yes, I understand why you want to get separate options now and your reasons are acceptable for me.

> On the property lines: I think the overview and fast readability is better with long lines. Or do you work on a 17" screen?

21" screen and I should use horizontal scrollbar for read all line :-/ But this is not reason - I fear not all compilers not on all platforms may parse very long lines correctly and we may got a "surprise".

**Comment by gzotti** [comment]
> > [color] [line] [partitions] Label.
> 
> Maybe [color] [partitions] [line] Label.

I think the line should come before the detail. And maybe now we need another column for the labels...

> And add tooltip "Drawing line with partitions" or "Drawing partitions" for [partitions] checkbox?

Yes, tooltips are a good solution.
 
> > On the property lines: I think the overview and fast readability is better with long lines. Or do you work on a 17" screen?
> 
> 21" screen and I should use horizontal scrollbar for read all line :-/ But this is not reason - I fear not all compilers not on all platforms may parse very long lines correctly and we may got a "surprise".

Oops, I was not aware of that. I know about the 80chars recommendation from the IBM punchcard era (1928; https://hilton.org.uk/blog/source-code-line-length). But which C++ compilers used in 2020 hiccup with long lines? (All lines still <200 chars).
The main point for the admittedly long Q_PROPERTY lines is readability of 4 declarative entries per line which is better in a wide table than in 4 (or 2) lines per entry. At least on QtCreator on Windows, I can Ctrl-Scrollwheel to zoom if needed.

**Comment by alex-w** [comment]
> I think the line should come before the detail. And maybe now we need another column for the labels...

I fear the users will be confused by many checkboxes :(

> Oops, I was not aware of that. I know about the 80chars recommendation from the IBM punchcard era (1928; https://hilton.org.uk/blog/source-code-line-length). But which C++ compilers used in 2020 hiccup with long lines? (All lines still <200 chars). The main point for the admittedly long Q_PROPERTY lines is readability of 4 declarative entries per line which is better in a wide table than in 4 (or 2) lines per entry. At least on QtCreator on Windows, I can Ctrl-Scrollwheel to zoom if needed.

I can't provide the representative data or comparisons for various compilers and platforms, due liming by number of platforms (I have amd64/i386 and, with serious limitations by Qt, PowerPC as hardware platforms and Linux/Windows/macOS (partially *BSD and Solaris) as software platforms) and compilers - GCC/Clang/ICC/MSVC. I hope we do not catch "killer surprise in the clear field".

In any way I see one cosmetic problem and one data problem. The data problem is... both equators should use hours by default and degrees when option "Use decimal degrees" is enabled. Currently both equators uses degrees only. The cosmetic problem is small overlapping the partitions by the labels - I think the distance for labels should be a bit increase.

And final problem - where is partitions and labels for precession circles - just a WIP or no plans for it?

**Comment by gzotti** [comment]
> > I think the line should come before the detail. And maybe now we need another column for the labels...
> 
> I fear the users will be confused by many checkboxes :(

We want fine-tuning with detailed settings. This is how to get them... Or are there 3-state checkboxes? Or combos: Line/Line+partitions/Line+partitions+numbers/partitions+numbers/ ? 

>> [Line length]
> I can't provide the representative data or comparisons for various compilers and platforms, due liming by number of platforms (I have amd64/i386 and, with serious limitations by Qt, PowerPC as hardware platforms and Linux/Windows/macOS (partially *BSD and Solaris) as software platforms) and compilers - GCC/Clang/ICC/MSVC. I hope we do not catch "killer surprise in the clear field".

Do you have percentage of PowerPCs still working?
I propose to keep the readable lines now until we hear a complaint. 

> In any way I see one cosmetic problem and one data problem. The data problem is... both equators should use hours by default and degrees when option "Use decimal degrees" is enabled. Currently both equators uses degrees only. 

Ah, right. TBD.

> The cosmetic problem is small overlapping the partitions by the labels - I think the distance for labels should be a bit increase.

When you move the sky, you will see it looks good on one side and overlaps the line in other orientations. I would prefer some alignment with the lines, but have not played with that yet.

> And final problem - where is partitions and labels for precession circles - just a WIP or no plans for it?
WIP. It's just that I wanted to finish the Great Circles first, these were much easier.

Next steps (weekend?) will be precession parts, then label placement adjustments. Feel free to find a solution!

**Comment by alex-w** [comment]
> We want fine-tuning with detailed settings. This is how to get them... Or are there 3-state checkboxes? Or combos: Line/Line+partitions/Line+partitions+numbers/partitions+numbers/ ?

Let's ask users about current UI after merging the code on CN and SGL forums.

> Do you have percentage of PowerPCs still working?

We do not collect that statistics :)

> Feel free to find a solution!

I hope I'll find the time for updating DSO catalog on this weekend :-/

**Pull request merged**
