### PR TITLE
New Sky Culture is Created in Marathi

### PR DESCRIPTION
**Pull request by santoshasalunke**
This sky culture is prepared with Marathi names of modern constellations,
planets and stars. Marathi names in Devnagari script are in "Native" list,
whereas IAU names are in "Translated". Constellation names in Marathi were
coined by Balshashtri Jambhekar (1812-46) and published in his magazine
"Digdurshun" in year 1842. He translated these names from English to
Marathi.

### Description
1) Constellation names coined in 1842 by an Indian mathematician and
astronomer Balshastri Jambhekar. Some of these are translated from English
names and some are from Indian traditional astronomy and mythology.
2) Planets and star names are from traditional Indian astronomy.
3) All names are in Indian Devanagari script.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?
Tested with adding Marathi sky culture files to "sky cultres" folder of Stellarium desktop.

**Test Configuration**:
* Operating system: Windows 10
* Graphics Card: Intel UHD Graphics 620, driver version - 27.20.100.8854

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works: Screen shot of sky culture in Stellarium desktop
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by santoshasalunke** [comment]
Here is sky culter files. Extract zip file to folder "C:\Program Files\Stellarium\skycultures" and select "Marathi" in sky culter tab in settings.
[marathi.zip](https://github.com/Stellarium/stellarium/files/10410122/marathi.zip)

**Comment by gzotti** [comment]
Thank you for your contribution. However, this pull request has ~1700 changed files in 250 commits, and then you add a ZIP file with the actual changes in a comment? And you want to push your master. 

Please follow https://github.com/Stellarium/stellarium/wiki/Git-Contributor-Workflow

**Comment by santoshasalunke** [comment]
Thank you for support.

This is my first submission in Github and Stellarium and don't know how pull requests work. I just tried to create pull request.

I read Git Contributor Workflow, but need to learn CLI / desktop app.

Meanwhile looking for someone to put sky culture in Stellarium download directories for interested users to download and use.

**Comment by 10110111** [comment]
This PR is broken: it requests to merge `release` branch into `master` from this same repository. This is why we have hundreds of commits in the ever growing queue.

**Comment by gzotti** [comment]
@santoshasalunke I have to close this PR due to the current misconfiguration which floods us with useless notifications. Please start over, following instructions in the FAQ, and make a new PR.

**Pull request closed without merging**
