### PR TITLE
Mark functions static and const

### PR DESCRIPTION
**Pull request by rikardfalkeborn**

### CODE REVIEW

**Comment by alex-w** [comment]
What exactly you want to get?

**Comment by gzotti** [comment]
There are some definitely non-static functions like Landscape::getTexturePath. Some const or static changes seem OK, though. A merge will likely break things, these have to be checked per case.

**Comment by rikardfalkeborn** [comment]
> There are some definitely non-static functions like Landscape::getTexturePath. Some const or static changes seem OK, though. A merge will likely break things, these have to be checked per case.

I'm not following, are you saying ```Landscape::getTexturePath``` can not be static? I'm probably missing something, but can you elaborate why that's the case?

**Comment by gzotti** [comment]
Oops, case of bad memory. This should indeed work.

**Pull request merged**
