### PR TITLE
Very Slight Error in Orion in the Western Constellation Lines + One Extra Asterism

### PR DESCRIPTION
**Pull request by bobmeisterr**
One error in the linked stars in the Orion constellation in the western skyculture, and one extra asterism added (Job’s Coffin - part of Delphinus).

Fixes # (issue)>

### Description

I found a slight error in Orion in the western skyculture lines. In Orion's hand and club ξ Orionis (HIP 29426) was previously connected to 64 Orionis (HIP 28691), however 64 Orionis (HIP 28691) is only a magnitude 5.10 star; there's a brighter star right next to it, χ2 Orionis (HIP 28716), which is a magnitude 4.60 star (so half a magnitude brighter). ξ Orionis (HIP 29426) should be connected to χ2 Orionis (HIP 28716) instead of 64 Orionis (HIP 28691), so I made that single change in the "constellationship.fab" file (attached). No need to worry about the western_hlad, western_rey, and western_SnT skyculture packages; because they don't have to same lines for Orion. In fact, those packages already connect χ2 Orionis (HIP 28716) in their lines, and not 64 Orionis (HIP 28691).

Github.com said that the .fab file extension wasn't supported, so I had to attach it as a .txt file. I'm sure you can download it and just change the file extension back to .fab.

As for the asterisms, I've added the asterism "Job's Coffin" (part of the constellation Delphinus) under the "Form-forming asterisms", although it could probably just as easily go under "Associative and sectional asterisms" or "Binocular asterisms", so please correct as appropriate and let me know :). I also made a couple of tweaks to the W and V asterisms, changing "V" to "V of Taurus" and "W" to "W of Cassiopeia". Please feel free to remove these tweaks if you feel they're not necessary. I updated both the "asterism_lines.fab" and the "asterism_names.eng.fab" files appropriately. On my computer I also copied these files and added them to the western_hlad, western_rey, and western_SnT skyculture packages as well; since they're also variations of western. What do you think about doing this on your end as well?

Once again, I've attached the amended "asterism_lines.fab" and "asterism_names.eng.fab" files as .txt files.

[asterism_lines.txt](https://github.com/Stellarium/stellarium/files/3563317/asterism_lines.txt)
[asterism_names.eng.txt](https://github.com/Stellarium/stellarium/files/3563318/asterism_names.eng.txt)
[constellationship.txt](https://github.com/Stellarium/stellarium/files/3563319/constellationship.txt)

Please let me know what you think? and maybe update Stellarium accordingly, if appropriate.

Thank you  :).

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

I’ve made the changes to my copy of Stellarium, by updating my .dab files accordingly, then run Stellarium and selecting the appropriate skyculture packages.

Stellarium 19.1
PC, Windows 10
Works perfectly.

No other effects.

**Test Configuration**:
* Operating system: Windows 10 Home, 64-bit, version 1703 (OS Build 15063.1418)
* Processor: Intel Core i7-6700HQ 2.6GHz
* Graphics Card: Intel HD Graphics 530 and NVIDIA GeForce GTX 960M

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
Please rebase the PR and resolve conflicts

**Comment by bobmeisterr** [comment]
Is this something I have to action, Alexander?

**Comment by alex-w** [comment]
Oops... Are you tried use web editor?

**Comment by bobmeisterr** [comment]
I opened the PR in Firefox, if that’s what you mean. I edited the .fab files in Notepad.

**Comment by gzotti** [comment]
"Error" in Stellarium's version of the Orion lines is impossible by definition, because this lineset has been created by one of the developers, and the lines are not canonized, so this is an original decision. In the same way you could argue that we "must" close the line from 64 (or chi2) to chi1 Ori.  We could accept a suggestion to change both issues, though.

Western_Rey, Western_SnT and Western_Hlad are immutable, as they are describing particular atlases. These did not add extra asterisms to their lines, and only used particular star names instead of our huge collection, so our versions will not add them as well. Users are free to build their own mix of various skycultures for their own screens, of course.

For whatever reason, you would bring in a whole branch of changes done since February. Did you clone from our master, or from ChrUnger? Do a "git rebase master", so that only the few files from the skycultures directory which you report having been changed by yourself would be affected, or just copy/paste the 5 lines or so suggested to change by you in a simple issue report.

**Comment by bobmeisterr** [comment]
Hi Georg,

Thanks for your reply. I would like to suggest making those two tiny changes, please, yes! :). As well as adding the extra asterism (Job’s Coffin). I’ve already made the changes in the attached .txt files.

As for the git PR, I just made a new PR, I didn’t clone anything. Git asked for two selections when opening a PR - the default was “master” and “Stellarium”, I tried submitting the PR with “Stellarium” and “Stellarium”, but it wouldn’t let me; so I submitted it with “Stellarium” and “0.19” (thinking of version 19.0). As for the files themselves, I just edited them in MS Notepad. They’re just the files from the 19.1 install, I then just tweaked the lines relevant to the constellation I changed (Orion) and the asterism I added (Job’s Coffin), that’s all. So nothing else has been changed.

Thanks again! :)

**Comment by gzotti** [comment]
I will formally reject and close this PR as it's technically flawed, but will add your suggestions, only that I remove HIP20713 from V of Taurus, so that the line follows the constellation. Also, I think "W" is enough.

**Comment by gzotti** [comment]
One more question: Where did you find the "Job's Coffin" asterism?

**Comment by bobmeisterr** [comment]
I originally found it in the Wikipedia article on the constellation Delphinus. But I then googled it and found it in other sources too. Some of the more scholarly sources might be listed as references in the Wikipedia article?

**Comment by bobmeisterr** [comment]
I can to find the other sources, if you’d like?

**Comment by gzotti** [comment]
Would be fine. Please just report then in a new "Issue", not "Pull Request", and for simplicity, you can just copy/paste your added lines in the issue. 
I am just extending the *_names.eng.fab format to allow reference comments.

**Comment by bobmeisterr** [comment]
Ok, got it. Thanks Georg! :).

**Comment by bobmeisterr** [comment]
Hi Georg, how many references would you like per asterism?

**Comment by gzotti** [comment]
Not necessarily many entries per asterism, but some "original" primary source would be especially good. I.e., who invented or described it first. May be difficult to say for generally known large asterisms though, but telescopic asterisms may be traced to single articles or books by observers or popularizers. (There are also differences per culture how well asterisms are known, e.g. USA vs. European amateur traditions.) 

Regarding the format: Add references to reference.fab, and then in asterism_names.eng.fab, add one space and a comma-separated list of numbers which refer to the reference.fab, just like in star_names.fab.

**Pull request closed without merging**
