### PR TITLE
Fix location manager for API changes to GPSd 3.20

### PR DESCRIPTION
**Pull request by michaelld**
### Description

Simple changes to the location manager to provide compatibility with GPSd API through current (3.20); still backwards compatible with GPSd API < 3.20. See also the GPSd website `https://gpsd.io/` for more information on this release, including the release notes describing the use of `GPSD_API_MAJOR_VERSION` .

I've searched through the current PRs and issues, and found nothing dealing with the GPSd API change.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Tested on macOS 10.14 / Xcode 11.3 (11C29) using MacPorts, but the change should be compatible regardless of OS and build system.

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by michaelld** [comment]
I was double checking the formatting, and realized that in one of the changes I used spaces and not tabs. I switched to tabs to match the current code, and just force-pushed that here to keep the commit log clean.

**Comment by alex-w** [comment]
Yes, this patch should resolve problem of building.

**Comment by gzotti** [comment]
I wanted to have a look at this on Sunday. Looks good, thanks!

**Comment by michaelld** [comment]
You're welcome! Thanks for the very prompt attention!

**Pull request merged**
