### PR TITLE
Add to China Sky  Culture

### PR DESCRIPTION
**Pull request by sunshuwei**
Based on the book Chinese and Western Contrast Star Chart and Catalogue 1950.0  by Yi Shitong.

### CODE REVIEW

**Comment by sunshuwei** [comment]
Please check again
Pinyin transliterations for the star names can be added later In fact, except for a few stars, the vast majority of Chinese star names are Xingguan names + a number.  The pinyin translation for the constellation is equivalent to the pinyin translation for the star.

**Comment by alex-w** [comment]
It's OK for me. Georg?

**Comment by gzotti** [comment]
Re star names: OK, I see this. There might still be some experts who prefer to display the Pinyin spelling to others (imagine a lecture by a scholar of Chinese astronomy for Europeans or US Americans. For some reasons, you want to have the star names not translated but "readable for the audience".)   One other thing: "Add-star" looks like an auxiliary translation, is this the official English term? Other than that, we can merge now, but please @sunshuwei stay available for possible further improvements!

**Comment by sunshuwei** [comment]
I can finish the pinyin translation of the star, but this is slow. After all, it has more than 3,000 names,This work can be done later.
Add-star（增pinyin：zeng ，增星pinyin：zengxing） is an official term, but it is not an official English term.It has no  official English term.Its Chinese is "增", direct meaning is added. It means added stars to the xingguans in the Qing Dynasty.These stars are called“增星”。
I have tried “added”,“additional”，“Attached”,“extra”, I am not satisfied with the translation of this word, but I do not know which one to use better.
Native English speakers should have more accurate words, and please help  translate it, thank you very much.

**Comment by sunshuwei** [comment]
I will continue to improve this sky culture, and the Constellation Artwork can be added.And set up a form of China constellation in Description.en.utf8

**Comment by gzotti** [comment]
OK, Alex I think we can merge. Further improvements can be added later.

**Pull request merged**
