### PR TITLE
#100 news bookmarks functionalities

### LINKED ISSUE #100: Favourite or Tracking list Enhancement
Hi,
I am looking for a favourites feature, so I can add a few objects to my list. Then when I click on my list I can see what is up and quickly look at different targets instead of always having to type in the name. A way to sync my list on my pc and my mobile would be great.
Eg.
I am trying to observe comets and typing out their full names is slow and I can't find some on my mobile app either, a feature like this would make it easier to plan a night observing if you can click on a short list and quickly figure out what you want to observe.
I hope this makes sense.
Thanks for this program, it is the BEST!!

### PR DESCRIPTION
**Pull request by Jocelyn1109**
### Description
- sort bookmarks by column,
- possibilty to cretae multiple bookmarks lists.

Fixes #100 

Screenshots (if appropriate): no screenshot, but I can provide it if needed.

Type of change
 - [x] Bug fix (non-breaking change which fixes an issue),
 - [x] New feature (non-breaking change which adds functionality),
 - [ ] Breaking change (fix or feature that would cause existing functionality to change),
 - [x] This change requires a documentation update.

### **How Has This Been Tested ?**
**Test Configuration:**
Operating system: 
 - Linux/Kubuntu 19.0
 - Intel Core i7-9700 8X 3,00 GHz / 16Go DDR4 / HDD: 480Go SSD + HDD: 1To
 - Graphics Card: GeForce RTX2060 6Go

I did many tests:
- creation of multiple bookmarks list,
- deletion of bookmarks list,
- check the loading lists when opening bookmarks windows,
- import/export of bookmarks in(from) a selected list,
- highlight bookmarks from a selected list/clear highlight,
- adding/deleted bookmark.

### **Checklist:**
  - [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project,
  - [x] [checkbox:checked] I have performed a self-review of my own code,
  - [x] I have commented my code, particularly in hard-to-understand areas,
  - [ ] I have made corresponding changes to the documentation,
  - [ ] My changes generate no new warnings,
  - [ ] I have added tests that prove my fix is effective or that my feature works,
  - [ ] New and existing unit tests pass locally with my changes,
  - [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by alex-w** [comment]
The code has lines indentation issues also - are you using QtCreator or some other IDE?

**Comment by Jocelyn1109** [comment]
Hello Alexander no problem for the last review. 
I can understand that your are busy.
It is my case too. I work the day and I work on Stellarium on my free time ;)

I use KDevelop and I don't understand these four errors because I already corrected them :(
I will check again :)

Jocelyn

**Comment by alex-w** [comment]
Please see CodeFactor suggestions for find the places of issues

**Comment by Jocelyn1109** [comment]
Yes I did it but I didn't see the same problem in my code.
I will try to find the problem.

**Comment by Jocelyn1109** [comment]
I checked my code about the 4 problèmes and I do not have them in my code.
I checked my "forked" repository on GitHub and I don't have problems too.
It seems that CodeFactor don't take intoo account last push.

**Comment by Grukz** [comment]
good patch, i hope it will be added to next release

**Pull request closed without merging**
