### PR TITLE
using qDebug() for logs

### PR DESCRIPTION
**Pull request by asiniscalchi**

### CODE REVIEW

**Comment by gzotti** [comment]
This just looks like a branch merged too early, and now showing again the full branch history (?)

@cardinot It seems we need some really clear coaching guidelines in the wiki by people more familiar with git. Not "fix it" but something like "Before finishing a branch and expressing the pull request, please help us getting a cleaned-up history by executing these git commands in your branch: ..."

**Comment by cardinot** [comment]
@gzotti, yes, we should have a few guidelines in the wiki for that.

For this PR, no worries, we can squash all commits in a single one before merging into master.

@asiniscalchi. Many thanks for your contributions.
I noticed that you usually do your changes directly in your master branch. That's fine, but it is usually a much better practice to work on your own branch with:
`git branch myBranchName`  to create a branch called `myBranchName`
`git checkout myBranchName` to make `myBranchName` your active branch.

For example, you started it just to change from `IDLog` to `qDebug` and now, with your last commits, this PR does much more than that; which makes this PR harder to be reviewed. Doing your changes in topic branches prevents you from all those issues. Also, it makes your PRs cleaner and easier to review.

Important note: always try to be as descriptive as possible in your branch names, commit messages, and pull request title.

Moreover, we should try as much as possible to never add the automatic 'merge commits' which looks like:
```
Merge branch 'master' of http://... into master
```
for that, `git pull` should not be invoked if your branch is ahead of master. In this case, always prefer to `git pull --rebase` or `git rebase` as it won't create the auto-merge commits. And will move all your local commits to the top of the tree.

I'll include our suggested git workflow in the wiki soon. Meanwhile, I strongly recommend this one:

https://github.com/phonegap/phonegap/wiki/Git-Contributor-Workflow

**Comment by cardinot** [comment]
@asiniscalchi could you run these commands in your master branch, please?
```
git checkout master
git reset --hard 60b49bb10d9f5c37059e2daf92d4463307014ef1
git pull https://github.com/Stellarium/stellarium.git master
git push origin master
```
It should be enough to fix the master branch of your fork now.
For future contributions, please have a look at:
https://github.com/Stellarium/stellarium/wiki/Git-Contributor-Workflow

Huge thanks for your time and effort! ;)

**Comment by asiniscalchi** [comment]
ok. Thanks.

**Pull request merged**
