### PR TITLE
Replace minus sign and quotation marks to their ASCII version

### PR DESCRIPTION
**Pull request by gongminmin**
1. Some minus signs are in UTF-8 (U+2013),
2. Two quotation marks are in UTF-8 (U+201C and U+201D)

Replace them to avoid warning C4819 in MSVC when computer's locale is in Chinese.

### CODE REVIEW

**Comment by gongminmin** [comment]
At the end of travis-ci, it's waiting for entering an api token. And then time out for 10 mins. The messages are:

> requests 2.18.4 has requirement urllib3<1.23,>=1.21.1, but you'll have urllib3 1.23 which is incompatible.
> Installing collected packages: urllib3, six, idna, chardet, certifi, requests, Unidecode, python-slugify, transifex-client
> Successfully installed Unidecode-1.0.22 certifi-2018.4.16 chardet-3.0.4 idna-2.6 python-slugify-1.2.5 requests-2.18.4 six-1.11.0 transifex-client-0.13.3 urllib3-1.23
> /home/travis/env/local/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
>   RequestsDependencyWarning)
> tx INFO: Pushing resource stellarium.stellarium
> [?] Enter your api token: 
> 
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> The build has been terminated

**Comment by alex-w** [comment]
@gongminmin I've fixed it in the master

**Comment by gongminmin** [comment]
Thanks @alex-w !

**Comment by alex-w** [comment]
@gongminmin Are you build the source code within MSVC or QtCreator?

**Comment by gongminmin** [comment]
Within MSVC. I may not have QtCreator installed.

**Comment by alex-w** [comment]
It's strange, because I cannot reproduce warnings on my Windows instance (Russian locale)

**Comment by gongminmin** [comment]
It could only happen in some locale. My setting is Chinese locale, warning C4819 can be seen in many projects, including https://github.com/assimp/assimp, NVIDIA CUDA samples, FreeImage, etc.

Also, there might be a bug in MSVC when C4819 is triggered. The line number in the warning is random. So it's very hard to tell which line is the problem... I'll fie a bug against MSVC.

**Pull request merged**
