### PR TITLE
Refactoring mouse navigation

### LINKED ISSUE #1317: Ocular Plugin: Mouse Navigation
-->Ocular Plugin: Mouse Navigation disabled in Ocular View

### Expected Behaviour
Ocular View should not disable 'mouse navigation'
You can use the arrow keys to shift the image;
However, there are no arrow keys on a tablet PC.
'Image sensor frame' and 'Telrad sight' do not disable 'mouse navigation'

### Actual Behaviour
Mouse navigation is enabled in the main application.
When switching to 'Ocular View', mouse navigation gets disabled.

### Steps to reproduce
Enable mouse navigation in main application.
Switch to 'Ocular View', Check settings; mouse navigation is disabled

### System
* Stellarium version: stellarium-0.20.3-win64.exe
* Operating system: windows 10 64-bit [Version 10.0.19041.508]
* Graphics Card: Intel(R) HD Graphics 4000
* Screen type (if applicable): 1366x768

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

### PR DESCRIPTION
**Pull request by alex-w**
Splitting the mouse navigation option into 2 options: navigation and zooming

### Description
Splitting the mouse navigation option into 2 options adding the possibility to disable zooming by mouse without disabling the mouse dragging. As result we may disable zooming in the eyepiece mode in Oculars without disabling the dragging via mouse in same time.

Fixes #1317, #2086

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?
Tested on the MacBook Pro with trackpad

**Test Configuration**:
* Operating system: macOS Monterey (12.0.1)

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by alex-w** [comment]
@gzotti I think this PR is ready to merge

**Comment by gzotti** [comment]
Can you move in ocular view now? Or what has changed for the user? 

Ah: I can move when no object is selected and centered. But when something is selected, I cannot move away using the mouse. Or yes, but I have to press the mouse button about 2 seconds until I can move the scene. This is also unexpected.

**Comment by alex-w** [comment]
> Can you move in ocular view now? Or what has changed for the user?
> 
> Ah: I can move when no object is selected and centered. But when something is selected, I cannot move away using the mouse. Or yes, but I have to press the mouse button about 2 seconds until I can move the scene. This is also unexpected.

The behaviour is connected to setting for eyepiece mode, but yes, you may disable zooming through mouse now separately

**Comment by gzotti** [comment]
Well, I don't observe currently. You can merge if you want because working as before is possible, but I expect bug reports with my observations about this funny behaviour that it takes some weird move to finally drag the view in Oculars view.

**Pull request merged**
