### PR TITLE
Add plugin ExtraCalendar

### LINKED ISSUE #1313: Calendar options
Hi.  I can imagine calendar options that would allow people to try different types of calendars.  For example with lunar calendars like the Chinese, Vietnamese, Hindu, and Thai calendars.
I see this a powerful aid in teaching the importance of calendars and how they can help us relate to cosmic influences.
By the way... stellar work so far!

### PR DESCRIPTION
**Pull request by rayw000**
### Description

Plugin `ExtraCalendar` displays multiple calendars (extensible, currently only support Chinese calendar) on the bottom-right corner. It helps user know how different calendars work with the influence of solar/lunar/etc.

Partially fixes #1313

Thanks to https://github.com/isee15/Lunar-Solar-Calendar-Converter/ 

### Screenshots (if appropriate):
image
image
image
image

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

- Test environment
  - macOS 10.15.7 Catalina
  - cmake 3.18.3
  - Qt 5.15.1
  - g++ Apple clang version 12.0.0 (clang-1200.0.32.2)
- Test steps
  - Make directory `build` under project root and enter into it
  - Run command `CMAKE_PREFIX_PATH=/usr/local/opt/qt cmake ..`
  - Run command `make -j4 && ./src/stellarium`
  - Open Configuration window, see if `ExtraCalendar` appears in the plugin tab
  - See if the description of`ExtraCalendar` plugin works as expected
  - See if `ExtraCalendar` plugin works as expected
  - Change default language of Stellarium, see if `ExtraCalendar` changes its name label as expected
  - Increase timespeed, see if `ExtraCalendar` updates correctly on local time 00:00AM
  - Press `+` and `-` to forward/backward dates, see if `ExtraCalendar` updates correctly
  - Press `F5`, change to date out of 1901~2099, see if `ExtraCalendar` disappears as expected
  - Go back to current time, see if `ExtraCalendar` shows again as expected
  - Change date to which is a Chinese leap month, see if `ExtraCalendar` works as expected
- Affected files
  - `/CMakeLists.txt`
  - `/po/stellarium/zh_CN.po`
  - `/src/core/StelApp.cpp`

**Test Configuration**:
* Operating system: macOS 10.15.7 Catalina
* Graphics Card: Intel Iris Plus Graphics 1536 MB

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — CHANGES_REQUESTED** [review]
Please use English names as source strings for days, months and zodiacs. Plus I see troubles for translatable strings in getChineseCalendarDateString method.

P.S. The Chinese calendar may be interested outside China too ;)

**Comment by rayw000** [comment]
@alex-w Many thanks for your sooo quick review! I'll update later. 😃

**Comment by rayw000** [comment]
@alex-w Would you like to give me some advice about translating the year of Chinese Calendar? We have 10 characters called 天干 and 12 characters called 地支, a year name is a combination of one 天干 and one 地支, 60 years a cycle. It's hard to translate into English😂.

How do you think if I change the format of the calendar string such as:
```
[Chinese calendar] 2020-09-05（庚子）
```
Then, when the default language is Chinese, we have
```
[中国农历] 2020年九月初五（庚子）
```

**Comment by alex-w** [comment]
Hmm... It's interesting - I'll check possible solution tonight (I don't have book [Calendrical Calculations](https://www.amazon.com/Calendrical-Calculations-Ultimate-Edward-Reingold/dp/1107683165/) near me right now).

**Comment by rayw000** [comment]
> Hmm... It's interesting - I'll check possible solution tonight (I don't have book [Calendrical Calculations](https://www.amazon.com/Calendrical-Calculations-Ultimate-Edward-Reingold/dp/1107683165/) near me right now).

Great recommendation! That's what I need!😃

**Comment by axd1967** [comment]
A good way to test that this is a flexible implementation is to provide a **second calendar system** (eg a trivial one is the Gregorian calendar, but some other lunar/lunisolar/solar calendar could be even better). Once a second calendar is possible, anyone can add more calendars as needed. This will test that the implementation is a bit more future-proof; otherwise, it might prove po be difficult to maintain in the long term.

Also, indeed as @alex-w points out, this plugin should also be usable outside China (see following comment)
image


So one trivial calendar could be added: a Western character version of this _same_ Chinese calendar. Look at how the HK Observatory presents such a calendar in a fashion that is understandable by Western users: http://www.hko.gov.hk/en/gts/time/conversion.htm

Also, I'm aware that unit testing is dreadful task, but some unit testing should be implemented to check for border cases (i'm thinking of outside range/leap years/invalid inputs).

The user should also be warned - at least in the plugin configuration dialog - that this calendar works for the range 1901-2099 + reason, rather than be facing an UI that returns an empty string (because not many users will go in the log files) . Also, the message should read "Chinese calendar only supports years between **1901** and **2099**." (or else the test should be changed).

**Comment by rayw000** [comment]
@axd1967 quite helpful information, thanks a lot!

**Comment by gzotti** [comment]
Agree with @alex-w on using Calendrical Calculations (CC) for such plugin, as it seems the currently most complete and most computer-friendly collection. They mention 10 tian gan (celestial stems) and 12 di zhi (terrestrial branches). (I left away diacritics here, sorry). The plugin should use dates based on a common day count like Julian Day Number (JD).  CC has introduced another day count (RD), but this is just a simple offset away. It may be tricky to work with counting systems that don't flip days at midnight or noon. 
I also fully agree this must be based in English and be translatable, like all other parts of the program. It should be modular enough so that other developers can implement other calendars, like proleptic Gregorian, various Maya calendars, computable Islamic, Hebrew, Indian, ...
It should if possible also allow entering calendar dates in the supported calendar systems. This may become a GUI monster, with say 17 different calendars similarly displayed, but may be useful. (Maybe split into tabs per cultural area, and show "Western-style" dates as reference on every tab?) Such plugin has been a long-time plan for myself, but if somebody takes it, it's more than welcome.

**Comment by gzotti** [comment]
Re "adding checkboxes and output on transparent panel". This is the screen-space conserving "information" solution that only converts "from JD to culture-specific calendar". Date manipulation will then still be only by the current date panel. 
A more advanced solution would allow manipulating the culture-specific data components directly. This will need lots of GUI boilerplate code, but can also be quite useful. It may even be useful to allow both, a full interface dialog and text-only output.

**Comment by rayw000** [comment]
Hi all,

I've made some changes which makes `ExtraCalendar` can display Chinese calendar internationalized in default. Would you please take a review when you are free? Thanks! 😃

@gzotti Implemented s a new calendar system is really a good idea, but it may requires a lot of work out of my knowledge now. Would you like to accept `ExtraCalender` plugin as a temporary solution before we can manipulate the culture-specific data components? 🙂

**Comment by axd1967** [comment]
Hello,

- [ ] forgive me if I'm mistaken, but I thought there could be between 12 and **13** months in a Chinese calendar, I don't see this in the code; but again, I might be mistaken
- [ ] why not turn the lower and upper limits (1901/2100) into constants? this is asking for a bug: assume someone someday manages to change the code, updates the constants but forgets one place? these are logically the same values everywhere (also in error messages etc)
- [ ] there is still only one calendar, consider adding a trivial conversion such as a conversion from Gregorian to Gregorian (and to be commented out prior to shipping)
- [ ] small obs: if you construct a warning message for the user, consider using it everywhere

```c++
// DRY!
msg = q_("[%1] %2").arg(calendarName, q_("Only support years from 1901 to 2100"))
qDebug() << msg;
return (msg);
```



refs:
- https://en.wikipedia.org/wiki/Chinese_calendar

**Comment by rayw000** [comment]
Thanks for your review! @axd1967 

> * [x]  forgive me if I'm mistaken, but I thought there could be between 12 and **13** months in a Chinese calendar, I don't see this in the code; but again, I might be mistaken
If you set your Stellarium date between `2033-12-22` and `2034-01-19`, you will see a `[Leap]` sign (or `闰` in Chinese) before the month number `11`, because that month is a leap month in Chinese calendar. Is it what you are looking for?

> * [ ]  why not turn the lower and upper limits (1901/2100) into constants? this is asking for a bug: assume someone someday manages to change the code, updates the constants but forgets one place? these are logically the same values everywhere (also in error messages etc)
Great suggestion. I'll update later.

> * [ ]  there is still only one calendar, consider adding a trivial conversion such as a conversion from Gregorian to Gregorian (and to be commented out prior to shipping)
Currently I'm studying Islamic calendar. I'd like to introduce it into `ExtraCalendar` later. How would you think if I add some code examples to show how to add a new calendar to the later contributor?

> * [ ]  small obs: if you construct a warning message for the user, consider using it everywhere
> 
> ```c++
> // DRY!
> msg = q_("[%1] %2").arg(calendarName, q_("Only support years from 1901 to 2100"))
> qDebug() << msg;
> return (msg);
> ```
Great suggestion. I'll update later.

**Comment by sunshuwei** [comment]
Chinese calendar https://en.wikipedia.org/wiki/Chinese_calendar
天干 celestial stem; heavenly stem
地支 terrestrial branch; earthly branch
http://www.lamost.org/astrodict/index.php
干支 Sexagenary cycle
https://en.wikipedia.org/wiki/Sexagenary_cycle
甲，乙，丙，丁...pinyin:  jiǎ yǐ bǐng dīng
子，丑，寅，卯...pinyin: zǐ chǒu yín mǎo

It seems that we need to introduce the operation of Chinese calendar and Sexagenary cycle.
Otherwise, it is difficult for non-East Asians to understand it.

**Comment by alex-w** [comment]
I think the plugin should contain the GUI for calendars, not just display the data “on the sky”

**Comment by rayw000** [comment]
Thanks for your help! @sunshuwei 

This link http://www.hko.gov.hk/en/gts/time/conversion.htm uses pinyin instead of translating directly into English. Perhaps it is enough for non-Asian people who are not familiar with Chinese culture. Do you agree?😀

@alex-w I'd like to. It may take time. That's what I'm currently working on. 🙂

**Comment by axd1967** [comment]
> > * [x]   forgive me if I'm mistaken, but I thought there could be between 12 and **13** months in a Chinese calendar, I don't see this in the code; but again, I might be mistaken
> 
> If you set your Stellarium date for example between `2033-12-22` and `2034-01-19`, you will see a `[Leap]` sign (or `闰` in Chinese) before the month number `11` (or `十一` in Chinese), because that month is a leap month (the 13th month) in Chinese calendar. Is it what you are looking for?

This is probably the intercalary month, indeed. (And this is a good example of unit testing).

> > * [ ]   there is still only one calendar, consider adding a trivial conversion such as a conversion from Gregorian to Gregorian (and to be commented out prior to shipping)
> 
> Currently I'm studying Islamic calendar. I'd like to introduce it into `ExtraCalendar` later. How would you think if I add some code examples to show how to add a new calendar to the later contributor?

The main point would be to demonstrate that the plugin is capable of providing multiple extra calendars, so providing guidelines and examples is nice, but IMHO not convincing (I think it is likely that this might require some small re-engineering, you are the best positioned to lay the scaffolds). But this requires extra work and is easier said than done, I'm just probing (and a small fish here - @gzotti and @alex-w have the last word), so don't feel obliged, the community is already grateful that you are doing this. But I believe that once we know in advance that several calendars can exist, it is good to foresee the place for them. Maybe once the plugin is working, as a next task?

Note: I built 3ddc8943efd41908d70056b25eb929c1abe2a28b;  logfile says the plugin is started, but I see no time info:

image

**Comment by alex-w** [comment]
> Note: I built [3ddc894](https://github.com/Stellarium/stellarium/commit/3ddc8943efd41908d70056b25eb929c1abe2a28b); logfile says the plugin is started, but I see no time info:

Same problem here

**Comment by rayw000** [comment]
@axd1967 Thanks for your kindly suggestion. Indeed, it needs some re-engineering to add a new calendar. I'll describe it in document later.

@axd1967 @alex-w Ah.. Maybe some test cases are not covered in my previous testing. Probably working with languages other than English and Chinese I guess, not sure. I'm not at my laptop now. I'll fix it this morning.

**Comment by rayw000** [comment]
Or maybe I use an incorrect way to calculate text position, which makes it out of screen on your device.

**Comment by rayw000** [comment]
> Note: I built 3ddc894; logfile says the plugin is started, but I see no time info:

@axd1967 @alex-w 

Would you like to provide more details?

It's weird that I've tried these following steps but still can't reproduce the problem you two encountered.
1. Run command `git clean -fx .` to build from a totally clean repo (head at 3ddc894).
2. Run command `mkdir build` and enter into the `build` directory.
3. Run command `CMAKE_PREFIX_PATH=/usr/local/opt/qt cmake .. && make -j4 && ./src/stellarium` to launch the program.
4. Set this plugin to load at startup, and then restart program.
5. Try different languages, calendar text displays as expected.
6. Try to use window mode instead of full-screen mode and resize window, calendar text displays as expected.
7. Try different available resolutions, calendar text displays as expected.

Again, could you please give me some a clue so that I can find out what the problem is? Thank you!

**Comment by alex-w** [comment]
@rayw000 please check your email account

**Comment by rayw000** [comment]
> @rayw000 please check your email account

Just got email notification. So nice you are! I'll take time to read it carefully.

**Comment by axd1967** [comment]
Meanwhile, the HKO pages give interesting information, such as "Solar terms" and stems and branches - looks like this belongs in a calendar too.

https://www.hko.gov.hk/en/gts/time/24solarterms.htm
https://www.hko.gov.hk/en/gts/time/stemsandbranches.htm
https://www.hko.gov.hk/en/gts/time/12animals.htm

**Comment by axd1967** [comment]
>     1. Run command `git clean -fx .` to build from a totally clean repo (head at [3ddc894](https://github.com/Stellarium/stellarium/commit/3ddc8943efd41908d70056b25eb929c1abe2a28b)).
> 
>     2. Run command `mkdir build` and enter into the `build` directory.
> 
>     3. Run command `CMAKE_PREFIX_PATH=/usr/local/opt/qt cmake .. && make -j4 && ./src/stellarium` to launch the program.
> 
>     4. Set this plugin to load at startup, and then restart program.
> 

The plugin loads fine, so the previous steps should all work

>     5. Try different languages, calendar text displays as expected.

Tried several languages

> 
>     6. Try to use window mode instead of full-screen mode and resize window, calendar text displays as expected.

Tried too

>     7. Try different available resolutions, calendar text displays as expected.

I'm using HD 1920x1080, can't see anything unusual in the corner area.

> 
> 
> Again, could you please give me a clue so that I can find out what the problem is? Thank you!

Maybe we should ask more people to compile your branch and see if it happens there too? I think you are working on Mac, I'm on Dell XPS-13 laptop.

**Comment by rayw000** [comment]
> Meanwhile, the HKO pages give interesting information, such as "Solar terms" and stems and branches - looks like this belongs in a calendar too.
> 
> https://www.hko.gov.hk/en/gts/time/24solarterms.htm
> https://www.hko.gov.hk/en/gts/time/stemsandbranches.htm
> https://www.hko.gov.hk/en/gts/time/12animals.htm

Thank you!

**24 solar terms**: It's on my list to add it into Chinese calendar later. Indeed it is an important part of Chinese calendar.
**Stems and branches** and **12 Animals**: Already included. Currently `ExtraCalendar` uses pinyin as what HKO does (something link Geng-zi year of Mouse) to display stems and branches when user's language is not Chinese.
Your previous reply that mentioned the website of HKO helps me a lot! Again, thank you!

------------------------------

> I'm using HD 1920x1080, can't see anything unusual in the corner area.
> 
> > Again, could you please give me a clue so that I can find out what the problem is? Thank you!
> 
> Maybe we should ask more people to compile your branch and see if it happens there too? I think you are working on Mac, I'm on Dell XPS-13 laptop.

Yes, I'm working on a MacBook Pro with macOS 10.15.7 Catalina installed. Maybe this issue is caused by something related to retina display. I'll find an HD display to debug later. Thank you!

**Comment by rayw000** [comment]
@axd1967 

Could you please edit [this line](https://github.com/Stellarium/stellarium/pull/1339/files#diff-5d333d6f0dd5d36add228d817ac97ee0ab104551601df4638d0e8660820e8846R122) to something like
```c++
painter.drawText(300, 300, text);
```
and rebuild your branch so that we can confirm if this problem is related to text position? Thank you!

**Comment by axd1967** [comment]
> @axd1967
> 
> Could you please edit [this line](https://github.com/Stellarium/stellarium/pull/1339/files#diff-5d333d6f0dd5d36add228d817ac97ee0ab104551601df4638d0e8660820e8846R122) to something like
> 
> ```c++
> painter.drawText(300, 300, text);
> ```
> 
> and rebuild your branch so that we can confirm if this problem is related to text position? Thank you!
> 
> I guess it is very likely because I use a retina display and yours is not.
> Previously when I used `gui->getSkyGui()->getSkyGuiWidth()` and `fs.width()` to get the GUI width and text width, I saw calendar text in the middle of the screen. So I plainly multiplied these value with 2 to get a correct position. It should be the problem.
> If so, the question may turn to being compatible with both HD display and retina display.

With pleasure! And with that same pleasure I can confirm a (better :-) ) output:

image

**Comment by rayw000** [comment]
@axd1967 That's great! So next, I need to find out how to draw text properly to be compatible with Retina display. You helps me a lot! 😃

**Comment by rayw000** [comment]
Hi @axd1967 @alex-w 
I found that there is a method named `getDevicePixelsPerPixel` in `StelApp`.

https://github.com/Stellarium/stellarium/blob/4fc941e2ff740147a03032031c940069dcc491b3/src/core/StelApp.hpp#L189

It is exactly what I was looking for to distinguish retina/non-retina display. On my MacBook Pro, it's value is `2`.

I just pushed a commit to fix the issue not displaying calendar text on your devices. Now `ExtraCalendar` should work fine. Would you like to have a try and give me some feedback? 😃

**Comment by axd1967** [comment]
> I just pushed a commit to fix the issue not displaying calendar text on your devices. Now `ExtraCalendar` should work fine. Would you like to have a try and give me some feedback? 

looks OK:

image

image

a small issue: once the user selects an invalid date, the plugin keeps _appending_ the warning in the log, which might make the log grow _very_ large.

**Comment by axd1967** [comment]
@rayw000 allow me this small tip: avoid squashing all the time, because you are making your life more difficult; it's normal to try things with may small commits and then back out. one day you might squash the wrong way and cause loss of some work, let alone having to face problematic merges and also making life difficult for co-developers on the branch. so once you have pushed a branch for others to see it, avoid rebase/squashing. (and possibly, a rebase/squash might impact GitHub PR comments)

just before the final pull request, do a final rebase + squash + test + PR.

note that the safest and cleanest way remains to simply merge master in, test, then merge to master (thus, without rebasing, even if that means extra git spaghetti).

**Comment by gzotti** [comment]
Please don't criss-cross-merge, but rebase before PR. 

Our usual strategy for larger changes is "develop in a branch, rebase before pull request". https://github.com/Stellarium/stellarium/wiki/Branching-Strategy

Usually branches are squashed on merge. 
In rare cases like long-time branches, I sometimes squash a few commits during the occasional rebase.

**Comment by rayw000** [comment]
@axd1967 @gzotti 
Your advices are very helpful to me, thank you very much!

**Comment by rayw000** [comment]
@axd1967 @gzotti 
Excuse me for disturbing. So what I should do is to avoid squashing (such as what I did in `plugin-calendars-suqashed` branch this time) before PR the next time, just feel free to open a PR and push commits to fix bugs and apply review suggestions. Once the PR gets approved, I should do a final rebase and then we can merge this PR into master. Am I right?

I've been asked for a squashing in some other repos before. I may misunderstand why we need to do this.

**Comment by gzotti** [comment]
Yes. Just add regular commits and don't bother with manual squashing unless you need it for your own peace of mind. We can see here whether a PR can be merged. If not, we will ask you to rebase to current master before we accept a PR. The merge will usually include a squash, so the merge is just a single commit for us.

**Comment by axd1967** [comment]
Unless I'm mistaken, MJD and JD are two examples of alternative calendars. (And a future, nice to have is [HJD](https://en.wikipedia.org/wiki/Heliocentric_Julian_Day), that is to be calculated from RA/Dec of an object).

image

So maybe in a future iteration of this plugin, these _could_ be taken into account too (or they could be used as trivial extra calendars, as everything is already precomputed!)

**Comment by gzotti** [comment]
JD is a continuous time count that avoids complications about month lengths and year counts. MJD is a trivial derivative. Both are no calendars. A calendar for most cultures splits either the solar year (or close approximation) into smaller bits, or follows the lunar cycles, or does both. Another calendar that splits days into larger packages (also not fully independent from the Solar year or a rough approximation) is the Maya Long Count. Yet other schemes exist that are not primordially solar or lunar (the other Maya calendars are again examples.) 
While the plugin should likely indeed do internal computations on JD, there need not be a duplicate output. 

HJD is something best left to programs which really provide all temporal corrections, including relativistic effects. I don't think many users need it. You could just observe from the center of the sun...

**Comment by axd1967** [comment]
> JD is a continuous time count that avoids complications about month lengths and year counts. MJD is a trivial derivative. Both are no calendars. A calendar for most cultures splits either the solar year (or close approximation) into smaller bits, or follows the lunar cycles, or does both. Another calendar that splits days into larger packages (also not fully independent from the Solar year or a rough approximation) is the Maya Long Count. Yet other schemes exist that are not primordially solar or lunar (the other Maya calendars are again examples.)
> While the plugin should likely indeed do internal computations on JD, there need not be a duplicate output.
> 
> HJD is something best left to programs which really provide all temporal corrections, including relativistic effects. I don't think many users need it. You could just observe from the center of the sun...

JD is just an _example_ of a super trivial "calendar" to test the _capability of the plugin_ to provide true additional calendars. It allows to focus on the GUI and mechanism rather than present a complex calendar that might introduce two types of bugs: (1) in the (second) calendar, and (2) in the management code of the calendars. And it can be retained after all, so the user can display date/time _together_ with JD and MJD! Additionally, it auto-documents how to set up more calendars: which is much better than write instructions on how to do so.

(HJD is indeed a different beast that belongs in the info section of the selected object, not in the calendar plugin, that's why I put it in parentheses.)

**Comment by alex-w** [comment]
I found the code (under GPLv2+) which supports conversions between JD and eight calendrical systems: Julian,  Gregorian,  Hebrew,  Islamic,  Jalaali (Persian),  Chinese, (French) revolutionary,  and Modern Persian: https://github.com/Bill-Gray/lunar/blob/master/date.cpp

So, probably porting this code is not very difficult task now.

**Comment by gzotti** [comment]
Good!

It probably would be nice to have the usual separation into a CalendarMgr, CalendarGui, and an abstract base class Calendar with methods 
```
double toJD(QVector components);
QVector fromJD(double JD);
```
which then should be available in all derived calendar subclasses. 

The `update()` will then just apply `fromJD(core->getJD()));`

Components is a QVector of calendar-dependent length. Most will have year-month-day, but there are more and other partitions. E.g. week, decade in French Revolution calendars, 5 numbers in Maya Long Count, etc. Some calendars may have a disputable zero date (again e.g. the Maya Long Count), so we may even need a setEpoch(double JD) and in the GUI offer a few candidates from the literature. 

The GUI tabs can then specialize on e.g. one cultural region and access the components of the various subclasses. 

I could try to add that in the next few days, including the first few calendars if I neglect other tasks, and then let @rayw000 's integrate his code as ChineseCalendar. (Is there just one running unchanged since antiquity, or were there historically other rules in earlier times?)

**Comment by axd1967** [comment]
> It probably would be nice to have the usual separation into a CalendarMgr, CalendarGui, and an abstract base class Calendar with methods

> I could try to add that in the next few days, including the first few calendars if I neglect other tasks, and then let @rayw000 's integrate his code as ChineseCalendar.

Sounds good.

Just be careful not to add too much requirements at once, or the plugin will never be released. @gzotti 's comment "_if I neglect other tasks_" is already a **red flag**. 

I would start with (1) releasing the current implementation, **as is**, let it sink in, then (2) an implementation with structure in place and one **trivial** extra calendar, and then (3) start adding more complexcalendars. Calendars can become a source of extra bugs, that's almost guaranteed (plus - there will always be someone asking for yet another calendar, etc).

>  (Is there just one running unchanged since antiquity, or were there historically other rules in earlier times?)

I think it is unlikely to find calendars that have survived unchanged since antiquity...
https://en.wikipedia.org/wiki/Calendar_reform
https://en.wikipedia.org/wiki/List_of_calendars

**Comment by axd1967** [comment]
> So, probably porting this code is not very difficult task now.

The difficulty is not the porting of existing calendars ("famous last words"), but the framework to allow multiple calendars to coexist.

**Comment by gzotti** [comment]
At least the Julian calendar has not changed since 8AD and is still in use in the Orthodox church.

**Comment by sunshuwei** [comment]
@gzotti 

I will answer in Chinese. My English is not good, and I am worried that my English will cause misunderstandings.

@rayw000 可以的话请帮我用英语转述下o(∩_∩)o ，谢谢

基本规则是接近的。但是现在的农历规则可能不能用于回溯历史。
但是由于历史上历法的精度问题（包括是否考虑岁差，二十四节气是最初按照一年时间24等分，后来按照黄道圆周弧度24等分，这类问题），以及历代观测地点的变化等因素，特别是发现日食和月食预测错误的时候，中国古代经常“更新历法”（至少有几十次）。
这就导致闰月的规则，大小月的规则出现变化。
 


@rayw000

https://github.com/yuangu/sxtwl_cpp
https://github.com/HongchenMeng/SharpSxwnl

这是寿星天文历，是我见过最好用的农历程序。它用于4713BC-9999AD，它在722BC以后和实历相符，在1960以后和772BC之前采用农历现代算法，并且它还包含伊斯兰历。

**Comment by gzotti** [comment]
OK. Google translate produced this: 
>The basic rules are close. But the current lunar calendar may not be used to trace history. However, due to the historical accuracy of the calendar (including whether to consider precession, the twenty-four solar terms were initially divided into 24 equal parts according to the time of the year, and later according to the 24 equal divisions of the ecliptic circle arc, this kind of problem), and factors such as changes in observation locations in the past. , Especially when it is found that the prediction of solar and lunar eclipses is wrong, ancient China often "updated the calendar" (at least dozens of times). This has led to changes in the rules of leap months and the rules of large and small months.
> [urls]
> This is the astronomical calendar for birthdays, the best lunar calendar program I have ever seen. It is used in 4713BC-9999AD, it is consistent with the actual calendar after 722BC, the modern lunar calendar is used after 1960 and before 772BC, and it also contains the Islamic calendar.

Thanks. This means we may have to have more than one "Chinese Calendar" in the end (if rules are well-known enough to implement them!), but add enough documentation...
Calendars are an interesting topic, and often related to astronomy. I made a larger library for HP48 calculators ages ago, based on the CC book, so this is a natural successor. It will just delay v1.0 further...

**Comment by gzotti** [comment]
@alex-w please don't rush. I try to initiate our own Calendars plugin by Monday. The current conversion starts with a date in Gregorian calendar. This is not good to start with. I welcome @rayw000 's work, but we should build up this plugin based on a solid interface.

**Comment by alex-w** [comment]
I don’t rush, but you definitely should be reviewer for this plugin too

**Comment by gzotti** [comment]
OK. Then I say I formally reject addition of this plugin as it is because it will hopefully be superseded by a better constructed one within 2-3 weeks. I will however be happy if @rayw000 will add his code into the framework that will be provided with the new plugin.

**Comment by rayw000** [comment]
Hi @sunshuwei . Sorry for replying your late. It's my pleasure! But Google translation posted by @gzotti is good enough. 😃

**Comment by rayw000** [comment]
> @alex-w please don't rush. I try to initiate our own Calendars plugin by Monday. The current conversion starts with a date in Gregorian calendar. This is not good to start with. I welcome @rayw000 's work, but we should build up this plugin based on a solid interface.

> OK. Then I say I formally reject addition of this plugin as it is because it will hopefully be superseded by a better constructed one within 2-3 weeks. I will however be happy if @rayw000 will add his code into the framework that will be provided with the new plugin.

Thank you @gzotti ! I'm currently just working on displaying calendars in a graphic panel like what plugin `Oculars` does. And then I'll provide enough code snippets to show how to add a new calendar to extend `ExtraCalendar` plugin.

Also, It's my pleasure to make contributions in your plugin constructions. 🙂

**Comment by axd1967** [comment]
> OK. Google translate produced this:
> 
> > The basic rules are close. But the current lunar calendar may not be used to trace history. However, due to the historical accuracy of the calendar (including whether to consider precession, the twenty-four solar terms were initially divided into 24 equal parts according to the time of the year, and later according to the 24 equal divisions of the ecliptic circle arc, this kind of problem), and factors such as changes in observation locations in the past. , Especially when it is found that the prediction of solar and lunar eclipses is wrong, ancient China often "updated the calendar" (at least dozens of times). This has led to changes in the rules of leap months and the rules of large and small months.
> > [urls]
> > This is the astronomical calendar for birthdays, the best lunar calendar program I have ever seen. It is used in 4713BC-9999AD, it is consistent with the actual calendar after 722BC, the modern lunar calendar is used after 1960 and before 772BC, and it also contains the Islamic calendar.

BTW - I was already wondering about the 1901-2100 limitation.

**Comment by gzotti** [comment]
> BTW - I was already wondering about the 1901-2100 limitation. It might be good to document this?

Even better: remove the limitation. The CC book provides "the 1645 version" and some information going back to 104BCE. For dates before introduction, it may the be wise to just show -- -- -- -- -- indicators and no useless algorithmic artifacts.

**Comment by rayw000** [comment]
> BTW - I was already wondering about the 1901-2100 limitation. It might be good to document this?

It is because popular algorithms including HKO's are based on a table with some hard-coded data. This table stores Chinese New Years in Gregorian and days of months, and we use it with offsets to calculate dates in Chinese calendar. The limitation comes from the table size.

Of course, a generic algorithm, if exists, is way better than what we currently do. I'm happy to have a look at what CC provides.

**Comment by gzotti** [comment]
OK, my first draft for such a long overdue plugin is here. Basically, each calendar should be a subclass of Calendar with JD-based interface. I hope the CC book's solution for the Chinese calendar is easy to implement.

**Comment by rayw000** [comment]
Sorry for not responding too long, because I have too much work to do near the end of the year, and don't have uge continuous time. I'll close this PR, and come back here later in this month.

**Comment by gzotti** [comment]
OK. I also have massively too little time for what I wanted to do by now. However, I think it's a good and viable start so far.

**Pull request closed without merging**
