### PR TITLE
angle measure plugin: user option for measurement to follow the cursor

### PR DESCRIPTION
**Pull request by axd1967**
### Description

This patch allows to attach the running measurements to the cursor instead of the base of the measurement.

This helps in searching for a point in the sky.

### Screenshots

image

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: 
* Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-73-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by alex-w — CHANGES_REQUESTED** [review]
Please rename "Format" to "Options".

For me "Follow cursor" is bad name, because it has not obvious behaviour. Please rename the option.

**Comment by axd1967** [comment]
- [ ] Please rename "Format" to "Options".
- [ ] For me "Follow cursor" is bad name, because it has not obvious behaviour. Please rename the name of option.

**Comment by t4saha** [comment]
I have some suggestions

"**Display measurements next to cursor**" or "**Show measurements at cursor end**"

**Comment by alex-w** [comment]
@axd1967 please review the suggestions

**Comment by axd1967** [comment]
how about dff3d4e43cadc4e0b7c477888e4bae296a8d61a3 ?

**Review by alex-w — APPROVED** [review]
Thanks!

**Pull request merged**
