### PR TITLE
Simplify dev setup

### LINKED ISSUE #2779: ShowMySky is not working in Stellarium 1.1 RC2 on Linux
Testing Stellarium-1.1-RC2-x86_64.AppImage.

### Expected Behaviour
ShowMySky works.

### Actual Behaviour
Failed to load ShowMySky library: Cannot load library ShowMySky-Qt5: (ShowMySky-Qt5: cannot open shared object file: No such file or directory)

### Steps to reproduce
Run the AppImage and enable ShowMySky.

### System
* Stellarium version: 1.1 RC2
* Operating system: Manjaro Linux 22.0

### PR DESCRIPTION
**Pull request by DarthGandalf**
ShowMySky isn't required to be installed manually anymore, but is installed automatically if necessary.

CI setup can be simplified too

### Description

Fixes #2779 (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

### How Has This Been Tested?

By building it

**Test Configuration**:
* Operating system: Gentoo Linux
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by DarthGandalf** [comment]
@10110111

**Comment by alex-w** [comment]
I'm afraid that the file `ShowMySky.so` now not added into AppImage

**Comment by DarthGandalf** [comment]
> I'm afraid that the file ShowMySky.so now not added into AppImage.

That should be handled by the new `install(ShowMySky::ShowMySky)` command in CMakeLists.txt, which is conditioned on whether it's downloaded or not

But I didn't consider the transitive dependencies, because during my local tests they were installed, so it worked; I'll probably need to handle them inside CalcMySky with CPM instead of requiring Stellarium to have them installed

**Comment by DarthGandalf** [comment]
> I'm afraid that the file ShowMySky.so now not added into AppImage.

Выделение_436

https://github.com/Stellarium/stellarium/actions/runs/3295789333/jobs/5434698958

**Review by alex-w — CHANGES_REQUESTED** [review]
Compiling on Windows is broken and what is happened with unit tests?

**Comment by DarthGandalf** [comment]
I know:) that's why I initially marked it draft. Until ci passes without
broken tests on all platforms, it can't be merged yet

пт, 21 окт. 2022 г., 16:05 Alexander V. Wolf ***@***.***>:

**Comment by DarthGandalf** [comment]
fixed

**Review by alex-w — APPROVED** [review]
Thanks!

**Comment by 10110111** [comment]
How much does this increase build time? Stellarium is already quite long to build in the CI, and adding CalcMySky to rebuild each time will make it even longer.

**Comment by DarthGandalf** [comment]
Only showmysky library is built, not whole calcmysky, so not by too much

ср, 26 окт. 2022 г., 10:54 Ruslan Kabatsayev ***@***.***>:

**Review by 10110111 — APPROVED** [review]

**Pull request merged**
