### PR TITLE
Change encoding format in Korean.isl

### LINKED ISSUE #2988: Character Error in Korean Installer
### Expected Behaviour
When installing Stellarium, some Korean text appears as rather 'strange'. I tried to find original texts of these messages, but since they are too corrupted, I can't find them.

### Actual Behaviour
캡처

And when creating links for desktop, links were not generated. I think the links' names were also corrupted.

This warning message is repeated about 8 times, with slightly different link addresses. Warning message and error code itself doesn't change.

### Steps to reproduce
Select "Korean" (or whatever the corrupt text thing is) in Installer. I only tested with Windows because that's the one I only have, but I doubt it'll be different.

### System
* Stellarium version: 1.2 (Latest)
* Operating system: Windows 10
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

Since this happens in installer, I don't think there is any log generated, but if I'm wrong, let me know and I'll find it.

### PR DESCRIPTION
**Pull request by ysjbserver**
### Description
About the text error I reported, I think it's just the encoding format problem of the installer file. I changed nothing except encoding format (from EUC-KR to UTF-8).

Fixes #2988

### Type of change

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [ ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gzotti — APPROVED** [review]
Ah yes, encoding is a probable cause. Thank you!

**Review by 10110111 — APPROVED** [review]
Makes perfect sense.

**Comment by alex-w** [comment]
In the file you can see string `LanguageCodePage=949` - it should be changed too after changing encoding IMHO.

**Comment by alex-w** [comment]
Stop! Did you check Qt5-based Stellarium?

**Comment by ysjbserver** [comment]
Since the language code for EUC-KR is 51949, not 949, I don't think that should matter. I guess it kinda needs to be changed to 65001 (UTF-8), but I'm unsure if it's necessary.

And sorry for my lack of programming knowledge, but I don't get what you mean check Qt5-based.

**Comment by alex-w** [comment]
> And sorry for my lack of programming knowledge, but I don't get what you mean check Qt5-based.

Please try download and install version 1.2-qt5 of Stellarium - we use ISS5 for Qt5-based planetarium and ISS6 for Qt6-based edition respectively.

**Comment by ysjbserver** [comment]
> Please try download and install version 1.2-qt5 of Stellarium - we use ISS5 for Qt5-based planetarium and ISS6 for Qt6-based edition respectively.

Thank you! I just checked and the issue was the same. Exact same text at the exact same position. I checked Qt6 again, just to be sure, and it was the same.

**Pull request merged**
