### PR TITLE
Added support of Gujrati language

### PR DESCRIPTION
**Pull request by jayendra13**
I have created a new sky-culture named indian_guj which is basically a copy of eariler indian vedic.
The changes are just that the names are being rendered in Gujrati.

I have tested this thing which works on my ubuntu-18 machine.
stel

### CODE REVIEW

**Comment by gzotti** [comment]
If this is the same as Vedic, just translated, we must reject this PR:

It does not adhere to the standards described in chapter 9 of the User Guide. Esp. file asterism_names.eng.fab totally breaks any rules of translatability. The shown string must be in English (so that it can be translated into other languages; diacritical marks are allowed), and any translation from there should be done with our usual tools: 

Basically everything can be translated via Transifex. See https://github.com/Stellarium/stellarium/wiki#translation

Help translating All of Stellarium (or only the Skyculture strings for only partial happiness) to Gujrati:
https://www.transifex.com/stellarium/stellarium/language/gu/

If you want to provide a Gujrati version of the description of the Vedic skyculture, please simply send one file, description.gu.utf8, as translation of the description.en.utf8.  

If there is a slight variant or difference worth mentioning, you can edit description.en.utf8 as well, so that the rest of the world will profit and learn from your work.

**Comment by jayendra13** [comment]
I can work with Transifex, I have sent a request for it. I was unaware of how translation works. Please accept my request to join me in Transifex.

I may also work on description.gu.utf8 later.

Moreover, I have purchased Stellarium+ mobile app. Would adding Gujrati Language support here be eventually migrated there?

**Comment by gzotti** [comment]
On Transifex acceptance: I hope the responsible person will do that in the next few days.
On Stellarium+mobile: This is not discussed here, but hopefully @xalioth can answer.

**Comment by jayendra13** [comment]
hi @gzotti I have added some translations via transifex for Gujrati, which are not reviewed yet. Who reviews it ? how does those finally get used in the build procedure ? Can you shed a light upon it ?
Thanks

**Comment by alex-w** [comment]
@jayendra13 I've added you as reviewer on Transifex too. I'm apply translations before releasing beta and final versions. A new beta version with fresh translations for testing producing every week.

**Comment by jayendra13** [comment]
That's great, Thank you. 
How can test locally those translations, while building?

**Comment by alex-w** [comment]
Just download from Transifex *.po files and put them into /po directory

**Pull request closed without merging**
