### PR TITLE
GUI fixes and minor redesign of remaining icons

### LINKED ISSUE #752: Change buttons to make UI more intuitive
When someone has time to do UI work (if you agree it could be improved), in the script edit window the 'Clear' button, the 'File Open' button, the SSC button, and even the stop script button all look like they are disabled. The File Save button looks enabled, and useful, but it is a little hard to tell what the others are because of the greyness used in the colors. If they used the same blues as the File Save button, the problem would be eliminated.

This may apply to other windows as well, but I haven't played with them as much.

### LINKED ISSUE #937: dialogs are difficult to resize
### Expected Behaviour

It is very difficult to resize Stellarium dialogs. It looks like the borders are a single pixel wide, forcing the user to aim very precisely before being able to grab a dialog border in order to resize it. 

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: 0.19.3
* Operating system: Ubuntu 18.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

### PR DESCRIPTION
**Pull request by martinber**
Hello,

I want to try to fix some minor GUI problems:

- [x] Remove unused icons
- [x] Rename icon filenames to match better their purpose\
- [x] Draw some new small icons (new, edit, add, remove, delete, download, etc.)
- [x] Bad contrast and consistency of small button icons (E.g. icons on F12 debug window). Fixes #752 
- [x] Fix that oculars window titlebar was too thin
- [x] Disabled state of buttons, checkboxes, radio buttons and spinners not clear enough
- [x] Changed slightly some colors on the windows, particularly the backgrounds. Decreased the radius of some corners
- [x] Change selection color of window tab icons, right now they look light blue, I want to make them white
- [x] Fix an astroCalcDialog button using `8-off-settings.png` icon
- [x] Investigate if I can add warnings when the QT stylesheet is invalid

More problems to fix (in another PR):

- The satellites plugin GUI is setting buttons styles in a CPP file. Move to UI and CSS
- Tweak on the satellites plugin, the buttons that can change color
- Make the oculars plugin bar smaller
- Change backgrounds to make unselected icons more visible during the day
- Fix some margins on the GUI, at the same time fix #937 
- Fix various AstroCalc window issues, especially the bottom tabs on the Graphs tab
- Fix that some QComboBoxes are unnecessarily editable
- "Get location from GPS" button on the location window looks strange
  - Harder to fix than I thought. The button is a QToolButton instead of a QPushButton so it has a different style. Also the style should be set in the CSS file instead of the `locationDialog.cpp`. See below
- Stop using `setStyleSheet()` to change the style of widgets dinamically. It would be nice to set change properties with `setProperty()` and leave all the CSS inside of `normalStyle.css`. But a workaround is necessary: [source 1](https://stackoverflow.com/questions/22562716/changing-stylesheet-dynamically), [source 2](https://wiki.qt.io/Dynamic_Properties_and_Stylesheets).

### Screenshots (if appropriate):

Images of almost every button I could find with an icon on it:

Buttons with icons

The overall style of windows has changed slightly:

View Window

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?

I just run the program with the new icons, doing screenshots to see diferences between old and new icons.

**Test Configuration**:
* Operating system: Debian GNU/Linux
* Graphics Card: Graphics Card: AMD Radeon R7 360. Driver: radeon

## Checklist:
- [X] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by martinber** [comment]
Mockup

This is a mockup (New version on top). Can you confirm me that you like how it looks? Look at the disabled versions of the checkboxes, radio buttons and buttons.

**Comment by alex-w** [comment]
Gray text on buttons is OK for me. Gray checkboxes looks weird - maybe it should be more gray?

**Comment by martinber** [comment]
Hello, I wanted to show some changes before continuing:

- I renamed every icon to make the names more consistent:
  - `btButtonName-on.png`, `btButtonName-off.png`: Bottom bar icons were already named this way
  - `bbtButtonName-on.png`, `bbtButtonName-off.png`: Left bar icons were renamed this way weeks ago by you (I think)
  - `uibtButtonName.png`, `uibtButtonName-pressed.png`: Every button on the GUI windows.
  - `uieElementName.png`: Every GUI window element, e.g. `uieCloseButton.png`, `uieCheckbox-checked.png`, `uieSpindown.png`.
  - `miscElementName.png`: Misc things, like `miscWorldMap.png`, `miscGlow.png`.
- I removed lots of unused icons, for example the night vision ones, or the ones named `tabicon-???-active.png`. If they are needed again I need to redesign all of them anyway, so they are not useful anymore.

Do you like the naming scheme? If not I should revert now before continuing otherwise it is going to be a mess.

Also, this is a screenshot containing the updated icons, I'm not very good at drawing the new ones (e.g. the trashcan) but I hope that at least you can understand what they mean. I still have to see how they fit into the GUI

new icons

**Comment by alex-w** [comment]
Your naming scheme is OK for me

**Comment by martinber** [comment]
Hi, I've made some progress. I'm struggling a bit with the GUI code, right now looks like the style of the application is defined on several places:

- UI files available in `/src/gui/*.ui`: GUI elements and layout are defined here. Most icons have an icon image defined in this file.

- CPP files in `/src/gui/*.cpp`: Some icons have an image defined here, for example bottom bar buttons.

- `/data/gui/normalStyle.css`: Has the style of most common GUI elements, for example has the style for every button and every checkbox. But also it has some custom styles where the style of a specific element is set (e.g. `QPushButton#saveSatelliteButton` has an icon image defined here). This stylesheet also is quite messy, It would be nice to move some things around.

I'm already seeing that this will be a mess for you to review. Do you prefer me to do minimal changes trying to leave everything as it is now? Or do you prefer me to move things around and try to leave everything as tidy as I can?

-----------------

I've updated the image on the top, so you can see how the icons are starting to look like.

Also, below is a screenshot where:

- Disabled checkboxes are greyed out
- "GRS details..." button is disabled
- The spinner right of "Only for N latest selected objects:" also looks disabled
- The "Scale Moon" spinner has focus so it looks yellowish
- The "Scale Moon" checkbox is hovered so it looks yellowish

Previously I found a bit hard to differentiate disabled and enabled elements, what do you think?

73210248-9c992180-4128-11ea-9897-0873fb8af8e9

**Comment by alex-w** [comment]
> I'm already seeing that this will be a mess for you to review. Do you prefer me to do minimal changes trying to leave everything as it is now? Or do you prefer me to move things around and try to leave everything as tidy as I can?

Some time ago (around 5-8 years ago) each plugin had separate QSS file and code for manage it. This was obviously and logical, but all those plugins many years build as static plugins and all QSS stuff mas was moved into main QSS file to simplificate code and QSS base.

I think you may review the QSS file and move defined icons directly onto buttons (maybe with some exceptions). Maybe text on few buttons should be replace by icons (e.g.: Add, Delete).

>Previously I found a bit hard to differentiate disabled and enabled elements, what do you think?

It looks good at the moment (except for GRS button, but I think I just accustomed to old version)

>PD: Sorry, @alex-w I've added you as a reviewer for you to see the previous comment. I see that you are notified of every commit I do? Now I can't remove it

Don't worry about it :)

**Comment by martinber** [comment]
Sorry for the delay. There I wrapped it up because I don't want to make this wait for so long.

If you think that this is worth merging, I will rebase again and squash the commits a little (reducing these 31 commits into 5-10 commits)

**Comment by alex-w** [comment]
Please rebase your PR to resolve conflicts

**Comment by martinber** [comment]
There I rebased and reviewed the changes again

**Comment by NotSoRandomOne** [comment]
Yay! Thanks, and I look forward to seeing them in the next release!

**Pull request merged**
